Repository kcp-dev/kcp, pull requests merged in 2022-08, with the labels that each got.

#1652 Misc syncer e2e cleanups and fixes
  test/e2e/framework/config.go
  test/e2e/framework/fixture.go
  test/e2e/framework/kcp.go
  test/e2e/framework/kubectl.go
  test/e2e/framework/syncer.go
  test/e2e/framework/workspaces.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/ingress/controller_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#1572 wire TemporaryRootShardKcpSharedInformerFactory
  cmd/sharded-test-server/shard.go
  pkg/server/bootstrap/identity.go
  pkg/server/config.go
  pkg/server/server.go
Labels: approved, lgtm

#1629 Cleanup Syncer to prepare for Syncer Virtual Workspace transformations
  pkg/syncer/shared/finalizer.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_process.go
  pkg/syncer/status/status_process_test.go
Labels: approved, lgtm

#1656 syncer: move namespace locator normalization to indexer
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
Labels: approved, lgtm

#1649 Fix flaky informers
  go.mod
  go.sum
Labels: approved, lgtm

#1659 Makefile: allow WAIT=1 to keep server running in test-e2e-{sharded,shared} targets
  Makefile
Labels: approved, lgtm

#1600 SyncTarget Uniqueness
  go.mod
  pkg/apis/workload/v1alpha1/helpers.go
  pkg/reconciler/workload/namespace/namespace_reconcile_scheduling.go
  pkg/reconciler/workload/namespace/namespace_reconcile_scheduling_test.go
  pkg/reconciler/workload/placement/placement_reconcile_scheduling.go
  pkg/reconciler/workload/placement/placement_reconcile_scheduling_test.go
  pkg/syncer/shared/finalizer.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_controller.go
  pkg/syncer/status/status_process.go
  pkg/syncer/status/status_process_test.go
  pkg/syncer/syncer.go
  pkg/virtual/syncer/builder/build.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_controller.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/ingress/controller_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/syncer/syncer_test.go
Labels: approved, lgtm, kind/api-change

#1658 apis: add age column where it makes sense
  config/crds/apis.kcp.dev_apibindings.yaml
  config/crds/apis.kcp.dev_apiexports.yaml
  config/crds/apis.kcp.dev_apiresourceschemas.yaml
  config/crds/scheduling.kcp.dev_locations.yaml
  config/crds/scheduling.kcp.dev_placements.yaml
  config/crds/tenancy.kcp.dev_clusterworkspaces.yaml
  config/crds/tenancy.kcp.dev_clusterworkspaceshards.yaml
  config/crds/tenancy.kcp.dev_workspaces.yaml
  config/crds/workload.kcp.dev_synctargets.yaml
  config/root-phase0/apiexport-scheduling.kcp.dev.yaml
  config/root-phase0/apiexport-shards.tenancy.kcp.dev.yaml
  config/root-phase0/apiexport-tenancy.kcp.dev.yaml
  config/root-phase0/apiexport-workload.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspaces.tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspaceshards.tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-locations.scheduling.kcp.dev.yaml
  config/root-phase0/apiresourceschema-placements.scheduling.kcp.dev.yaml
  config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
  config/root-phase0/apiresourceschema-workspaces.tenancy.kcp.dev.yaml
  pkg/apis/apis/v1alpha1/types_apibinding.go
  pkg/apis/apis/v1alpha1/types_apiexport.go
  pkg/apis/apis/v1alpha1/types_apiresourceschema.go
  pkg/apis/scheduling/v1alpha1/types_location.go
  pkg/apis/scheduling/v1alpha1/types_placement.go
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/apis/tenancy/v1beta1/types.go
  pkg/apis/workload/v1alpha1/synctarget_types.go
  pkg/openapi/zz_generated.openapi.go
Labels: approved, lgtm, kind/api-change

#1648 Part 9: Scope client calls in test/e2e
  test/e2e/apibinding/apibinding_authorizer_test.go
  test/e2e/apibinding/apibinding_deletion_test.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
  test/e2e/apibinding/apibinding_protected_test.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/apibinding/apibinding_webhook_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/authorizer/rootcacertconfigmap_test.go
  test/e2e/authorizer/serviceaccounts_test.go
Labels: approved, lgtm

#1660 apis/workload/v1alpha1: Fix comment as the value of InternalSyncTargetPlacementAnnotationKey changed
  pkg/apis/workload/v1alpha1/types.go
Labels: approved, lgtm, kind/api-change

#1662 e2e: undo ForeverTestTimeout/30
  test/e2e/framework/syncer.go
Labels: approved, lgtm

#1657 [0.6] Fix flaky informers
  go.mod
  go.sum
  test/e2e/framework/fixture.go
Labels: approved, lgtm

#1664 e2e/apibinding: improve log output and workspace names
  test/e2e/apibinding/apibinding_test.go
Labels: approved, lgtm

#1655 apis/scheduling: remove unused PlacementState struct and constants
  pkg/apis/scheduling/v1alpha1/types_location.go
  pkg/apis/scheduling/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, kind/api-change

#1663 e2e: fix long api groups exhausting label value length
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/framework/util.go
  test/e2e/quota/quota_test.go
  test/e2e/reconciler/namespace/controller_test.go
Labels: approved, lgtm

#1668 apis/workload: remove unused func
  pkg/apis/workload/v1alpha1/helpers.go
  pkg/apis/workload/v1alpha1/synctarget_types.go
Labels: approved, lgtm

#1669 api change: adds VirtualWorkspaceURL to ClusterWorkspaceShard
  config/crds/tenancy.kcp.dev_clusterworkspaceshards.yaml
  config/root-phase0/apiexport-shards.tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspaceshards.tenancy.kcp.dev.yaml
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/openapi/zz_generated.openapi.go
Labels: approved, lgtm, kind/api-change

#1673 Switch to cluster name annotation
  go.mod
  go.sum
  pkg/admission/apibinding/apibinding_admission_test.go
  pkg/admission/clusterworkspace/admission_test.go
  pkg/admission/clusterworkspacetypeexists/admission_test.go
  pkg/admission/crdnooverlappinggvr/crdnooverlappinggvr_admission_test.go
  pkg/admission/finalizer/finalizer_admission_test.go
  pkg/admission/webhook/generic_webhook_test.go
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/authorization/workspace_content_authorizer_test.go
  pkg/reconciler/apis/apibinding/apibinding_indexes_test.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
  pkg/reconciler/apis/apibinding/conflict_checker_test.go
  pkg/reconciler/apis/apiexport/apiexport_controller_test.go
  pkg/reconciler/apis/apiresource/negotiation.go
  pkg/reconciler/scheduling/location/location_reconcile_test.go
  pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller_reconcile_test.go
  pkg/reconciler/workload/apiexport/workload_apiexport_reconcile_test.go
  pkg/reconciler/workload/basecontroller/controller.go
  pkg/reconciler/workload/deploymentsplitter/deploymentsplitter_reconcile.go
  pkg/reconciler/workload/ingresssplitter/tracker_test.go
  pkg/reconciler/workload/virtualworkspaceurls/virtualworkspaceurls_reconcile_test.go
  pkg/server/home_workspaces_test.go
  pkg/syncer/apiimporter.go
  pkg/syncer/spec/mutators/deployment_test.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_process_test.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
  pkg/virtual/workspaces/authorization/watch.go
  pkg/virtual/workspaces/cache/cache.go
  pkg/virtual/workspaces/registry/rest_test.go
Labels: approved, lgtm, kind/api-change

#1672 Labels sync targets with the SyncTargetKey for reverse lookup
  config/crds/workload.kcp.dev_synctargets.yaml
  config/root-phase0/apiexport-workload.kcp.dev.yaml
  config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
  pkg/apis/workload/v1alpha1/synctarget_types.go
  pkg/apis/workload/v1alpha1/types.go
  pkg/reconciler/workload/synctarget/synctarget_controller.go
  pkg/reconciler/workload/synctarget/synctarget_reconcile.go
  pkg/reconciler/workload/synctarget/synctarget_reconcile_test.go
  pkg/server/controllers.go
  pkg/server/server.go
Labels: approved, lgtm, kind/api-change

#1678 Part 12: Scope syncer and workspacetype tests
  test/e2e/syncer/syncer_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm

#1670 use ClusterWorkspaceShard.VirtualWorkspaceURL
  config/root/bootstrap.go
  config/root/clusterworkspaceshard.yaml
  pkg/admission/clusterworkspaceshard/admission.go
  pkg/admission/clusterworkspaceshard/admission_test.go
  pkg/server/options/flags.go
  pkg/server/options/options.go
  pkg/server/server.go
Labels: approved, lgtm, kind/api-change

#1681 apiexport controller: assigns ClusterWorkspaceShard.VirtualWorkspaceURL
  pkg/reconciler/apis/apiexport/apiexport_reconcile.go
  test/e2e/apibinding/apibinding_test.go
Labels: approved, lgtm, kind/api-change

#1653 runs e2e-sharded with two shards
  Makefile
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm, kind/api-change

#1667 Part 10: scope cross_logical_cluster tests
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/conformance/webhook_test.go
  test/e2e/fixtures/wildwest/bootstrap.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: approved, lgtm

#1686 VW: Fix permission checking in `root`
  config/root/clusterrolebinding-tenancy-workspace-reader.yaml
  pkg/authorization/bootstrap/policy.go
  pkg/virtual/workspaces/registry/rest.go
  pkg/virtual/workspaces/registry/rest_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
Labels: approved, lgtm

#1692 Add more logging
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
  pkg/server/home_workspaces.go
  pkg/server/home_workspaces_test.go
Labels: approved, lgtm

#1676 make internal apis available for apiexport permission claims
  config/crds/apis.kcp.dev_apibindings.yaml
  config/crds/apis.kcp.dev_apibindings.yaml-patch
  config/crds/apis.kcp.dev_apiexports.yaml
  config/crds/apis.kcp.dev_apiexports.yaml-patch
  pkg/apis/apis/v1alpha1/types_apibinding_test.go
  pkg/apis/apis/v1alpha1/types_apiexport_test.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
  pkg/virtual/framework/internalapis/import.go
  pkg/virtual/framework/internalapis/import_test.go
  pkg/virtual/framework/internalapis/init.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm, kind/api-change

#1695 reconciler/{apis,scheduling,tenancy}: use structured, contextual logging
  pkg/logging/constants.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_permissionclaim.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/reconciler/apis/apiexport/apiexport_reconcile.go
  pkg/reconciler/apis/apiexport/crypto.go
  pkg/reconciler/apis/apiresource/controller.go
  pkg/reconciler/apis/apiresource/negotiation.go
  pkg/reconciler/scheduling/location/location_controller.go
  pkg/reconciler/scheduling/placement/placement_controller.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_reconcile.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_scheduling.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/clusterworkspace_deletion_controller.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go
  pkg/reconciler/tenancy/clusterworkspaceshard/clusterworkspaceshard_controller.go
  pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller.go
  pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller_reconcile.go
Labels: approved, lgtm

#1687 Syncer: refuse to work on sync target UID discrepancy.
  cmd/syncer/cmd/syncer.go
  cmd/syncer/options/options.go
  pkg/cliplugins/workload/plugin/sync.go
  pkg/cliplugins/workload/plugin/sync_test.go
  pkg/cliplugins/workload/plugin/syncer.yaml
  pkg/reconciler/workload/synctarget/synctarget_reconcile.go
  pkg/syncer/syncer.go
  pkg/virtual/syncer/builder/build.go
  test/e2e/framework/syncer.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#1685 Completely cleanup support of personal workspaces in top-level organizations
  pkg/cliplugins/workspace/cmd/cmd.go
  pkg/cliplugins/workspace/plugin/helpers.go
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/cliplugins/workspace/plugin/kubeconfig_test.go
  pkg/cliplugins/workspace/plugin/options.go
  pkg/server/handler.go
  pkg/virtual/workspaces/builder/build.go
  pkg/virtual/workspaces/registry/rest.go
  pkg/virtual/workspaces/registry/rest_test.go
  test/e2e/framework/auth-tokens.csv
  test/e2e/homeworkspaces/home_workspaces_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
Labels: approved, lgtm

#1704 Makefile: set UNSAFE_E2E_HACK_DISABLE_ETCD_FSYNC=true in all e2e tests
  Makefile
Labels: approved, lgtm

#1711 *: remove member verb
  contrib/demos-unmaintained/demo/prototype2-script/user-rbac.yaml
  docs/authorization.md
  pkg/authorization/toplevel_org_authorizer.go
  test/e2e/apibinding/apibinding_authorizer_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm

#1712 Replace clusterworkspaces/{content,workspace} subresources in RBAC with workspaces{/content,}
  config/root/clusterrole-clusterworkspace-home-create.yaml
  config/root/clusterrole-clusterworkspace-home-prefix-access.yaml
  config/root/clusterrole-tenancy-maximal-permission-policy.yaml
  contrib/demos-unmaintained/demo/prototype2-script/user-rbac.yaml
  docs/authorization.md
  pkg/authorization/bootstrap/policy.go
  pkg/authorization/toplevel_org_authorizer.go
  pkg/authorization/workspace_content_authorizer.go
  pkg/authorization/workspace_content_authorizer_test.go
  pkg/server/home_workspaces.go
  pkg/server/home_workspaces_test.go
  pkg/virtual/workspaces/builder/build.go
  pkg/virtual/workspaces/builder/clusterworkspaces.go
  pkg/virtual/workspaces/registry/rest.go
  pkg/virtual/workspaces/registry/rest_test.go
  test/e2e/authorizer/org-resources.yaml
  test/e2e/framework/users.go
  test/e2e/homeworkspaces/home_workspaces_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
Labels: approved, lgtm

#1710 virtual/workspace: use real authorizer
  pkg/virtual/workspaces/builder/build.go
  pkg/virtual/workspaces/registry/rest.go
  pkg/virtual/workspaces/registry/rest_test.go
  test/e2e/homeworkspaces/home_workspaces_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
Labels: approved, lgtm

#1700 server: hardens the remote shard registration
  pkg/server/server.go
Labels: approved, lgtm

#1713 pkg/virtual/syncer/builder: fix incorrect comment
  pkg/virtual/syncer/builder/build.go
Labels: approved, lgtm

#1688 Add --batteries-included
  cmd/kcp/kcp.go
  config/helpers/bootstrap.go
  config/homebucket/bootstrap.go
  config/homeroot/bootstrap.go
  config/root-phase0/bootstrap.go
  config/root/bootstrap.go
  config/root/clusterworkspacetype-organization.yaml
  config/root/clusterworkspacetype-root.yaml
  config/root/clusterworkspacetype-team.yaml
  config/system-crds/bootstrap.go
  config/universal/bootstrap.go
  pkg/authorization/bootstrap/policy.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_reconcile.go
  pkg/server/config.go
  pkg/server/controllers.go
  pkg/server/options/authentication.go
  pkg/server/options/batteries/batteries.go
  pkg/server/options/flags.go
  pkg/server/options/options.go
  pkg/server/server.go
  test/e2e/apibinding/apibinding_authorizer_test.go
  test/e2e/apibinding/apibinding_deletion_test.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
  test/e2e/apibinding/apibinding_protected_test.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/apibinding/apibinding_webhook_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/customresourcedefinition/customresourcedefinition_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm

#1699 updates the tests building a list of VirtualWorkspaceURLs assigned to ClusterWorkspaceShards
  test/e2e/apibinding/apibinding_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm

#1716 exclude authn/authz apis from claimable list
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm

#1705 logging: use kind-prefixed fields instead of string-formatting
  pkg/logging/constants.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apiexport/apiexport_reconcile.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_scheduling.go
Labels: approved, lgtm

#1718 Fixes log line formatting
  pkg/syncer/status/status_process.go
Labels: approved, lgtm, ok-to-test

#1709 Part 14: scope clients in tests/e2e/framework
  test/e2e/framework/config.go
  test/e2e/framework/syncer.go
  test/e2e/framework/workspaces.go
Labels: approved, lgtm

#1706 Remove the redirect from shard to virtual workspaces
  pkg/server/config.go
  pkg/server/handler.go
  pkg/server/options/flags.go
  pkg/server/options/virtual.go
  pkg/server/server.go
  pkg/server/virtual.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
Labels: approved, lgtm

#1721 Add goreleaser
  .github/workflows/ci.yaml
  .github/workflows/goreleaser.yml
  .goreleaser.yaml
  Makefile
Labels: approved, lgtm

#1728 0.7: Add goreleaser
  .github/workflows/ci.yaml
  .github/workflows/goreleaser.yml
  .goreleaser.yaml
  Makefile
Labels: approved, lgtm

#1731 goreleaser: increase timeout and reduce archs
  .github/workflows/goreleaser.yml
  .goreleaser.yaml
Labels: approved, lgtm

#1735 goreleaser: add write permissions to GITHUB_TOKEN
  .github/workflows/goreleaser.yml
Labels: approved, lgtm

#1737 Dockerfile: add kubectl
  Dockerfile
Labels: approved, lgtm, kind/api-change

#1730 logging: stop using formatted strings for object identifiers
  pkg/logging/constants.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/reconciler/apis/apiexport/apiexport_reconcile.go
  pkg/reconciler/apis/apiexport/crypto.go
  pkg/reconciler/kubequota/kubequota_controller.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
  pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller.go
  pkg/reconciler/workload/deploymentsplitter/deploymentsplitter_reconcile.go
  pkg/reconciler/workload/ingresssplitter/ingresssplitter_reconcile.go
  pkg/reconciler/workload/placement/placement_reconcile.go
Labels: approved, lgtm

#1707 Part 13: Scope clients in test/e2e/virtual
  test/e2e/virtual/apiexport/virtualworkspace_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: approved, lgtm

#1617 Refactor permission claim labels reconciler
  .github/workflows/kcp-image.yaml
  .github/workflows/kcp-test-image.yaml
  .github/workflows/syncer-image.yaml
  config/crds/apis.kcp.dev_apibindings.yaml
  pkg/admission/permissionclaims/mutating_permission_claims.go
  pkg/apis/apis/v1alpha1/permissionclaims/labels.go
  pkg/apis/apis/v1alpha1/types_apibinding.go
  pkg/apis/apis/v1alpha1/types_apiexport.go
  pkg/apis/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/indexers/apibinding.go
  pkg/indexers/indexers.go
  pkg/openapi/zz_generated.openapi.go
  pkg/permissionclaim/permissionclaim_labeler.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_permissionclaim.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile_test.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_reconcile.go
  pkg/server/controllers.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm, kind/api-change

#1726 cli/workspace: don't get Workspace in parent on absolute use, but check inside the workspace
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/cliplugins/workspace/plugin/kubeconfig_test.go
  pkg/virtual/workspaces/registry/rest.go
  pkg/virtual/workspaces/registry/rest_test.go
Labels: approved, lgtm

#1744 Update Slack channel name
  README.md
Labels: approved, lgtm

#1747 virtual: stutter less in constructors
  pkg/virtual/apiexport/options/options.go
  pkg/virtual/options/options.go
  pkg/virtual/syncer/options/options.go
  pkg/virtual/workspaces/options/options.go
Labels: approved, lgtm

#1748 syncer: handle only the k8s export
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
Labels: approved, lgtm

#1745 Permission claim fixes / cleanups
  pkg/admission/permissionclaims/mutating_permission_claims.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_reconcile.go
Labels: approved, lgtm, kind/api-change

#1732 Part 15: Scope clients in test/e2e/fixtures
  test/e2e/fixtures/apifixtures/sheriffs.go
  test/e2e/quota/quota_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm

#1727 the identity provider gets data from a local cm too
  cmd/kcp-front-proxy/main.go
  cmd/virtual-workspaces/command/cmd.go
  config/shard/bootstrap.go
  pkg/server/bootstrap/api-export-identity_controller.go
  pkg/server/bootstrap/identity.go
  pkg/server/config.go
  pkg/server/server.go
Labels: approved, lgtm

#1757 Add ppc64le support
  .goreleaser.yaml
Labels: approved, lgtm, ok-to-test

#1746 docs/syncer.md: add missing instructions
  docs/syncer.md
Labels: approved, lgtm

#1766 .github: fix community meeting link
  .github/ISSUE_TEMPLATE/community-meeting-agenda.md
Labels: approved, lgtm

#1769 Generate CRD defaults for known types
  pkg/crdpuller/discovery.go
Labels: approved, lgtm, ok-to-test

#1765 [release-0.7] Start centralizing APIExport indexers
  pkg/indexers/apiexport.go
  pkg/indexers/indexers.go
  pkg/indexers/util.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
Labels: approved, lgtm

#1762 Start centralizing APIExport indexers
  pkg/indexers/apiexport.go
  pkg/indexers/indexers.go
  pkg/indexers/util.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
Labels: approved, lgtm

#1771 Fix image build
  Dockerfile
  Makefile
Labels: approved, lgtm

#1767 Add content, toplevel audit annotations
  pkg/authorization/toplevel_org_authorizer.go
  pkg/authorization/workspace_content_authorizer.go
Labels: approved, lgtm

#1754 Generic helper for consistent post-reconcile spec and status updates
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/reconciler/committer/committer.go
Labels: approved, lgtm

#1783 Set service protocol defaults
  pkg/crdpuller/discovery.go
Labels: approved, lgtm, ok-to-test

#1785 Add missing autoscaling single-word group name
  pkg/admission/apiresourceschema/validation.go
Labels: approved, lgtm, ok-to-test, kind/api-change

#1782 bootstrap: create the default ns in the system:shard ws
  config/shard/bootstrap.go
  config/shard/default-namespace.yaml
  pkg/server/server.go
Labels: approved, lgtm

#1789 Ignore .goreleaser.yaml in GH CI
  .github/workflows/ci-docs-only.yaml
  .github/workflows/ci.yaml
Labels: approved, lgtm

#1781 wires the APIIdentityCacheController
  pkg/server/controllers.go
  pkg/server/server.go
Labels: approved, lgtm

#1798 Introduce staticcheck linter for deprecations
  Makefile
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/third_party/library-go/crypto/crypto.go
  pkg/authorization/apibinding_authorizer.go
  pkg/crdpuller/discovery.go
  pkg/localenvoy/controlplane/controlplane.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
  pkg/reconciler/workload/apiexport/apiresourceschema.go
  pkg/reconciler/workload/deploymentsplitter/deploymentsplitter_reconcile.go
  pkg/server/options/options.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_process_test.go
  pkg/virtual/framework/authorization/authorizer.go
  pkg/virtual/framework/fixedgvs/apiserver/apiserver.go
  pkg/virtual/framework/forwardingregistry/rest_test.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/framework/config.go
  test/e2e/framework/syncer.go
  test/e2e/reconciler/clusterworkspace/controller_test.go
  test/e2e/syncer/syncer_test.go
Labels: approved, lgtm

#1802 Fix schemacompat npe
  pkg/schemacompat/schemacompat.go
  pkg/schemacompat/schemacompat_test.go
Labels: approved, lgtm

#1805 ddsif: exclude v1beta1 Workspaces
  pkg/informer/informer.go
Labels: approved, lgtm

#1809 Fix bug allowing metadata edits to e.g. creationTimestamp for built-in types as CRDs
  go.mod
  go.sum
  test/e2e/conformance/metadata_test.go
Labels: approved, lgtm

#1743 Fix leftover resource when deleting a namespace
  pkg/syncer/spec/spec_process.go
  pkg/syncer/status/status_process.go
Labels: approved, lgtm

#1624 synctarget export controller
  pkg/reconciler/workload/synctargetexports/synctarget_indexes.go
  pkg/reconciler/workload/synctargetexports/synctargetcompatible_reconcile.go
  pkg/reconciler/workload/synctargetexports/synctargetcompatible_reconcile_test.go
  pkg/reconciler/workload/synctargetexports/synctargetexports_controller.go
  pkg/reconciler/workload/synctargetexports/synctargetexports_reconcile.go
  pkg/reconciler/workload/synctargetexports/synctargetexports_reconcile_test.go
  pkg/server/controllers.go
  pkg/server/server.go
  test/e2e/fixtures/kube/core.k8s.io_services.yaml
  test/e2e/reconciler/locationworkspace/apiresourceschema_cowboys.yaml
  test/e2e/reconciler/locationworkspace/apiresourceschema_service.yaml
  test/e2e/reconciler/locationworkspace/synctarget_test.go
Labels: approved, lgtm, kind/api-change

#1196 Change issue template to newer issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/community-meeting-agenda.md
  .github/ISSUE_TEMPLATE/community_meeting.yaml
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/epic.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: approved, lgtm, ok-to-test

#1811 cache-server: starts empty apiextentions-server
  cmd/cache-server/main.go
  pkg/cache/server/config.go
  pkg/cache/server/options/options.go
  pkg/cache/server/server.go
Labels: approved, lgtm

#1780 controllers: avoid double copy of the rest config
  cmd/cluster-controller/main.go
  go.mod
  go.sum
  pkg/reconciler/tenancy/bootstrap/bootstrap_reconcile.go
  pkg/server/controllers.go
  test/e2e/apibinding/apibinding_authorizer_test.go
  test/e2e/apibinding/apibinding_deletion_test.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
  test/e2e/apibinding/apibinding_protected_test.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/apibinding/apibinding_webhook_test.go
  test/e2e/conformance/metadata_test.go
  test/e2e/framework/kcp.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/clusterworkspace/controller_test.go
  test/e2e/reconciler/clusterworkspaceshard/controller_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: approved, lgtm

#1797 pkg/server: use structured, contextual logging
  pkg/logging/constants.go
  pkg/server/apiextensions.go
  pkg/server/bootstrap/identity.go
  pkg/server/controllers.go
  pkg/server/handler.go
  pkg/server/home_workspaces.go
  pkg/server/home_workspaces_test.go
  pkg/server/options/controllers.go
  pkg/server/options/options.go
  pkg/server/server.go
  pkg/server/virtual.go
Labels: approved, lgtm

#1817 Part 18: Scope ingress controller
  cmd/ingress-controller/main.go
  pkg/localenvoy/controllers/ingress/envoyingresscontroller.go
Labels: approved, lgtm

#1739 authorization: add system:masters-only deep SAR via X-Kcp-Internal-Deep-SubjectAccessReview header
  pkg/admission/apibinding/apibinding_admission.go
  pkg/admission/clusterworkspacetypeexists/admission.go
  pkg/admission/initializers/initializer.go
  pkg/admission/initializers/interfaces.go
  pkg/authorization/deep_sar.go
  pkg/authorization/toplevel_org_authorizer.go
  pkg/authorization/workspace_content_authorizer.go
  pkg/authorization/workspace_content_authorizer_test.go
  pkg/server/config.go
  test/e2e/apibinding/apibinding_authorizer_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/authorizer/org-resources.yaml
  test/e2e/authorizer/workspace1-resources.yaml
  test/e2e/virtual/apiexport/virtualworkspace_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm, kind/api-change

#1819 Part 19: Scoped cmd/front-proxy
  cmd/kcp-front-proxy/main.go
  cmd/virtual-workspaces/command/cmd.go
  pkg/proxy/index/index_controller.go
  pkg/server/bootstrap/identity.go
  pkg/server/config.go
Labels: approved, lgtm

#1761 e2e/watchcache: remove ddsif testing
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: approved, lgtm

#1815 cache-server: expose apiresourceschemas and apiexports
  config/crds/bootstrap.go
  pkg/cache/server/bootstrap/bootstrap.go
  pkg/cache/server/config.go
  pkg/cache/server/crd_lister.go
  pkg/cache/server/server.go
  pkg/server/controllers.go
  pkg/server/server.go
  pkg/util/util.go
Labels: approved, lgtm

#1832 bump to the latest kube level
  go.mod
  go.sum
Labels: approved, lgtm

#1837 various: logging cleanups
  pkg/cache/server/bootstrap/bootstrap.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/clusterworkspace_deletion_controller.go
  pkg/reconciler/workload/deploymentsplitter/deploymentsplitter_reconcile.go
  pkg/reconciler/workload/synctarget/synctarget_controller.go
  pkg/server/server.go
Labels: approved, lgtm

#1825 Fix GH issue template labels
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/community_meeting.yaml
  .github/ISSUE_TEMPLATE/epic.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: approved, lgtm

#1834 Watch cache: use resource.group for object type in log messages and metrics
  go.mod
  go.sum
Labels: approved, lgtm

#1839 etcd3: include GroupResource in logs/metrics
  go.mod
  go.sum
Labels: approved, lgtm

#1844 Fix NewNamespaceLocator param name
  pkg/syncer/shared/namespace.go
Labels: approved, lgtm

#1831 Add exported claims
  config/crds/apis.kcp.dev_apibindings.yaml
  pkg/admission/permissionclaims/mutating_permission_claims.go
  pkg/apis/apis/v1alpha1/types_apibinding.go
  pkg/apis/apis/v1alpha1/types_apiexport.go
  pkg/apis/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/openapi/zz_generated.openapi.go
  pkg/permissionclaim/permissionclaim_labeler.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_controller.go
  pkg/server/controllers.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
Labels: approved, lgtm, kind/api-change

#1835 Lint for contextual logging
  Makefile
  hack/bump-k8s.sh
  hack/logcheck.out
  hack/verify-contextual-logging.sh
Labels: approved, lgtm, ¯\_(ツ)_/¯

#1846 Cluster scoped quota
  go.mod
  go.sum
  pkg/admission/kubequota/kubequota_admission.go
  pkg/reconciler/kubequota/scoped_generic_shared_informer_factory.go
  test/e2e/quota/quota_test.go
Labels: approved, lgtm, kind/api-change

#1800 sharded-test-server: support standalone vw server
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/main.go
  cmd/sharded-test-server/virtual.go
  cmd/virtual-workspaces/command/cmd.go
  cmd/virtual-workspaces/options/options.go
  hack/logcheck.out
Labels: approved, lgtm

#1850 cache-server: set the storage prefix to /cache
  pkg/cache/server/config.go
Labels: approved, lgtm

#1860 deletors: skip projected resources
  pkg/informer/informer.go
  pkg/projection/projected_apis.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go
Labels: approved, lgtm

#1861 e2e: save data in some temporary directory
  test/e2e/framework/config.go
  test/e2e/framework/syncer.go
  test/e2e/framework/util.go
  test/e2e/reconciler/ingress/controller_test.go
Labels: approved, lgtm

#1862 [release-0.7] deletors: skip projected resources
  pkg/informer/informer.go
  pkg/projection/projected_apis.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go
Labels: approved, lgtm

#1864 Add more e2e test cases for permission claims
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm

#1833 pkg/authorization: add audit logging
  pkg/authorization/apibinding_authorizer.go
  pkg/authorization/bootstrap_policy_authorizer.go
  pkg/authorization/decision.go
  pkg/authorization/local_authorizer.go
  pkg/authorization/system_crd_authorizer.go
  pkg/authorization/toplevel_org_authorizer.go
  pkg/authorization/workspace_content_authorizer.go
Labels: approved, lgtm

#1869 sharded-test-server: log the full command line with parameters
  cmd/sharded-test-server/virtual.go
Labels: approved, lgtm, ok-to-test

#1872 home-ws: wait for tenancy binding readiness
  pkg/server/home_workspaces.go
  test/e2e/homeworkspaces/home_workspaces_test.go
Labels: approved, lgtm

#1853 cache-server: provides client-related functionality for dealing with a shard on the HTTP level
  pkg/cache/client/context.go
  pkg/cache/client/round_tripper.go
  pkg/cache/client/round_tripper_test.go
  pkg/cache/client/shard/shard.go
Labels: approved, lgtm
