Repository kcp-dev/kcp, pull requests merged in 2022-10, with the labels that each got.

#2115 🐛 Fix link rendering in FAQ.md
  FAQ.md
Labels: approved, lgtm, ok-to-test

#2121 :bug: Detect kubectl plugin via FlagSet Name
  cmd/kubectl-kcp/main.go
  cmd/kubectl-workspace/main.go
  go.mod
  go.sum
  pkg/cliplugins/workspace/cmd/cmd.go
Labels: approved, lgtm

#2118 ✨ Add reservednames admission plugin to surface clearer error messages
  pkg/admission/plugins.go
  pkg/admission/reservednames/OWNERS
  pkg/admission/reservednames/admission.go
  pkg/admission/reservednames/admission_test.go
  pkg/apis/tenancy/v1alpha1/types.go
Labels: approved, lgtm, ok-to-test, kind/api-change

#2125 🐛 kubectl-kcp: remove duplicated NewFlagSet
  cmd/kubectl-kcp/cmd/kubectlKcp.go
Labels: approved, lgtm

#2124 ✨ pkg/admission/apibinding: more informative authorization failure message
  pkg/admission/apibinding/apibinding_admission.go
  pkg/admission/apibinding/apibinding_admission_test.go
  test/e2e/apibinding/apibinding_authorizer_test.go
Labels: approved, lgtm, kind/api-change

#1995 ✨ feature: sync resources from syncer virtual server
  hack/logcheck.out
  pkg/apis/workload/v1alpha1/synctarget_types.go
  pkg/cliplugins/workload/plugin/sync.go
  pkg/cliplugins/workload/plugin/sync_test.go
  pkg/cliplugins/workload/plugin/syncer.yaml
  pkg/syncer/apiimporter.go
  pkg/syncer/resourcesync/controller.go
  pkg/syncer/shared/finalizer.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_controller.go
  pkg/syncer/status/status_process.go
  pkg/syncer/status/status_process_test.go
  pkg/syncer/syncer.go
  test/e2e/framework/syncer.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/locationworkspace/apiresourceschema_cowboys.yaml
  test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
  test/e2e/reconciler/locationworkspace/synctarget_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#2126 :bug: Fix bugs in the resource controller
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/reconciler/workload/resource/resource_reconcile.go
  pkg/reconciler/workload/resource/resource_reconcile_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
Labels: approved, lgtm

#2129 🐛 Syncer AdvancedScheduling fixes: Avoid syncing down the experimental status annotation.
  pkg/syncer/spec/spec_process.go
Labels: approved, lgtm

#2137 :bug: fix: apigen to write files when previous versions are not present
  cmd/apigen/main.go
Labels: approved, lgtm

#1708 ✨ Support for local cluster services DNS resolution
  cmd/syncer/cmd/dns.go
  cmd/syncer/cmd/syncer.go
  cmd/syncer/options/options.go
  go.mod
  go.sum
  hack/logcheck.out
  pkg/cliplugins/workload/plugin/sync.go
  pkg/cliplugins/workload/plugin/sync_test.go
  pkg/cliplugins/workload/plugin/syncer.yaml
  pkg/dns/plugin/nsmap/README.md
  pkg/dns/plugin/nsmap/config.go
  pkg/dns/plugin/nsmap/namespace.go
  pkg/dns/plugin/nsmap/nsmap.go
  pkg/dns/plugin/nsmap/setup.go
  pkg/syncer/namespace/namespace_downstream_controller.go
  pkg/syncer/namespace/namespace_downstream_process.go
  pkg/syncer/namespace/namespace_downstream_process_test.go
  pkg/syncer/spec/mutators/deployment.go
  pkg/syncer/spec/mutators/deployment_test.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/syncer.go
  test/e2e/framework/syncer.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
  third_party/coredns/coremain/run.go
  third_party/coredns/name.go
Labels: approved, lgtm, ok-to-test

#2142 📖 Link to apigen source in quickstart API doc
  docs/quickstart-tenancy-and-apis.md
Labels: approved, lgtm

#2143 🌱 bump controller gen
  Makefile
  config/crds/apiresource.kcp.dev_apiresourceimports.yaml
  config/crds/apiresource.kcp.dev_negotiatedapiresources.yaml
  config/crds/apis.kcp.dev_apibindings.yaml
  config/crds/apis.kcp.dev_apiexports.yaml
  config/crds/apis.kcp.dev_apiresourceschemas.yaml
  config/crds/scheduling.kcp.dev_locations.yaml
  config/crds/scheduling.kcp.dev_placements.yaml
  config/crds/tenancy.kcp.dev_clusterworkspaces.yaml
  config/crds/tenancy.kcp.dev_clusterworkspaceshards.yaml
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml
  config/crds/tenancy.kcp.dev_workspaces.yaml
  config/crds/workload.kcp.dev_synctargets.yaml
  config/root-phase0/apiexport-scheduling.kcp.dev.yaml
  config/root-phase0/apiexport-tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspaces.tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-locations.scheduling.kcp.dev.yaml
  config/root-phase0/apiresourceschema-placements.scheduling.kcp.dev.yaml
Labels: approved, lgtm, kind/api-change

#2134 :seedling: Syncer: Complete the move to structural logging
  hack/logcheck.out
  pkg/logging/constants.go
  pkg/logging/tmc.go
  pkg/syncer/apiimporter.go
  pkg/syncer/namespace/namespace_downstream_controller.go
  pkg/syncer/namespace/namespace_downstream_process.go
  pkg/syncer/namespace/namespace_upstream_controller.go
  pkg/syncer/namespace/namespace_upstream_process.go
  pkg/syncer/resourcesync/controller.go
  pkg/syncer/shared/finalizer.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_controller.go
  pkg/syncer/status/status_process.go
  pkg/syncer/status/status_process_test.go
  pkg/syncer/syncer.go
  pkg/syncer/tunneler.go
Labels: approved, lgtm

#2149 :bug: fix 'make install' on mac
  Makefile
Labels: approved, lgtm

#2150 :bug: cmd/Sync: remove serviceaccounts from default resource list
  pkg/cliplugins/workload/plugin/sync.go
Labels: approved, lgtm

#2157 :sparkles: Allow use of JSON logging format
  cmd/kcp-front-proxy/main.go
  cmd/kcp/kcp.go
  cmd/syncer/main.go
  go.mod
  go.sum
  pkg/server/options/flags.go
Labels: approved, lgtm

#2145 🐛 Fix wrong annotation in logging call
  pkg/server/bootstrap/identity.go
Labels: approved, lgtm

#1971 :sparkles: :book: tmc: storage docs and apis
  docs/locations-and-scheduling.md
  docs/storage.md
  pkg/apis/workload/v1alpha1/types.go
Labels: approved, lgtm, ok-to-test, kind/api-change

#2163 🌱 crd-puller: replace fakes in tests
  cmd/crd-puller/pull-crds.go
  go.mod
  hack/logcheck.out
  pkg/crdpuller/discovery.go
  pkg/crdpuller/discovery_test.go
  pkg/syncer/apiimporter.go
Labels: approved, lgtm

#2135 🐛 Create VirtualWorkSpaceURL on first APIBinding
  pkg/indexers/apibinding.go
  pkg/indexers/apiexport.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/reconciler/apis/apiexport/apiexport_controller_test.go
  pkg/reconciler/apis/apiexport/apiexport_reconcile.go
  pkg/server/controllers.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm

#2171 :seedling: proxy: remove unused/duplicated Authentication code
  pkg/proxy/authentication/groups.go
Labels: approved, lgtm

#2162 🌱 Remove fake client from namespacelifecycle test
  pkg/admission/namespacelifecycle/admission.go
  pkg/admission/namespacelifecycle/admission_test.go
Labels: approved, lgtm, kind/api-change

#2168 :seedling: identitycache: refactor to not use fake clients in testing
  pkg/reconciler/apis/identitycache/api_export_identity_controller.go
  pkg/reconciler/apis/identitycache/api_export_identity_reconcile.go
  pkg/reconciler/apis/identitycache/api_export_identity_reconcile_test.go
Labels: approved, lgtm

#2174 🐛 Fix permissionclaim patch thrashing
  config/crds/apis.kcp.dev_apibindings.yaml
  config/crds/workload.kcp.dev_synctargets.yaml
  config/root-phase0/apiexport-workload.kcp.dev.yaml
  config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
  pkg/apis/apis/v1alpha1/types_apibinding.go
  pkg/apis/apis/v1alpha1/types_apiexport.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
Labels: approved, lgtm, kind/api-change

#2090 🌱 cache: extend the replication controller to reconcile apiresourceschema
  pkg/reconciler/cache/replication/replication_controller.go
  pkg/reconciler/cache/replication/replication_reconcile.go
  pkg/reconciler/cache/replication/replication_reconcile_test.go
  pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
Labels: area/sharding, approved, lgtm

#1998 :sparkles: Add cluster-wide resources support to the resource reconciler
  hack/logcheck.out
  pkg/indexers/indexers.go
  pkg/reconciler/workload/placement/placement_controller.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/reconciler/workload/resource/resource_reconcile.go
  pkg/reconciler/workload/resource/resource_reconcile_test.go
  pkg/server/controllers.go
  pkg/server/server.go
  pkg/syncer/shared/finalizer.go
  pkg/syncer/shared/helpers.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/status/status_process.go
  test/e2e/fixtures/kube/core.k8s.io_persistentvolumes.yaml
  test/e2e/syncer/persistentvolume.yaml
  test/e2e/syncer/syncer_test.go
Labels: approved, lgtm, kind/api-change

#2177 🐛 types_apibinding,types_apiexport: revert applied/export permission claims
  config/crds/apis.kcp.dev_apibindings.yaml
  config/crds/workload.kcp.dev_synctargets.yaml
  config/root-phase0/apiexport-workload.kcp.dev.yaml
  config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
  pkg/apis/apis/v1alpha1/types_apibinding.go
  pkg/apis/apis/v1alpha1/types_apiexport.go
  pkg/openapi/zz_generated.openapi.go
Labels: approved, lgtm, kind/api-change

#2144 🌱 remove API export reference from API binding status, make API export reference in API binding immutable
  config/crds/apis.kcp.dev_apibindings.yaml
  config/root-phase0/apiexport-workload.kcp.dev.yaml
  config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
  pkg/admission/webhook/generic_webhook.go
  pkg/admission/webhook/generic_webhook_test.go
  pkg/apis/apis/v1alpha1/types_apibinding.go
  pkg/apis/apis/v1alpha1/types_apibinding_test.go
  pkg/apis/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/authorization/apibinding_authorizer.go
  pkg/openapi/zz_generated.openapi.go
  pkg/permissionclaim/permissionclaim_labeler.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
  test/e2e/apibinding/apibinding_test.go
Labels: approved, lgtm, kind/api-change

#2183 🌱 cache: indroduce cache-server-kubeconfig-file flag
  pkg/server/options/cache.go
  pkg/server/options/flags.go
  pkg/server/options/options.go
Labels: area/sharding, approved, lgtm

#2186 🌱 bump to the latest kube level
  go.mod
  go.sum
Labels: approved, lgtm

#2193 :bug: virtualworkspace/workspaces: fix generateName
  pkg/virtual/workspaces/registry/rest.go
Labels: approved, lgtm

#2188 🐛 cache: take into account EmbeddedEtcd options
  pkg/server/options/options.go
Labels: approved, lgtm

#2198 🌱 Syncer: update vscode launch configuation
  contrib/kcp.code-workspace
Labels: approved, lgtm

#2169 ✨ Check for identityHash in APIExport admission and support multiple versions for APIs in permission claims
  pkg/admission/apiexport/OWNERS
  pkg/admission/apiexport/admission.go
  pkg/admission/apiexport/admission_test.go
  pkg/admission/plugins.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
  pkg/virtual/apiexport/schemas/builtin/builtin.go
  pkg/virtual/apiexport/schemas/builtin/builtin_test.go
  pkg/virtual/framework/internalapis/import.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
  pkg/virtual/syncer/schemas/builtin/builtin.go
  pkg/virtual/syncer/schemas/builtin/builtin_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm, kind/api-change

#2202 🐛 Isolate tmc-related logging constants in a dedicated package
  hack/logcheck.out
  pkg/syncer/namespace/namespace_downstream_process.go
  pkg/syncer/namespace/namespace_upstream_process.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/status/status_process.go
  pkg/syncer/syncer.go
  tmc/pkg/logging/constants.go
Labels: approved, lgtm

#2120 :book: update docs and docs-gen according to hugo syntax
  cmd/kubectl-kcp/cmd/kubectlKcp.go
  docs/authorization.md
  docs/cache-server.md
  docs/cli/kcp.md
  docs/cli/kcp_crd.md
  docs/cli/kcp_crd_snapshot.md
  docs/cli/kcp_workload.md
  docs/cli/kcp_workload_cordon.md
  docs/cli/kcp_workload_drain.md
  docs/cli/kcp_workload_sync.md
  docs/cli/kcp_workload_uncordon.md
  docs/cli/kcp_workspace.md
  docs/cli/kcp_workspace_create-context.md
  docs/cli/kcp_workspace_create.md
  docs/cli/kcp_workspace_current.md
  docs/cli/kcp_workspace_tree.md
  docs/cli/kcp_workspace_use.md
  docs/cluster-mapper.md
  docs/concepts.md
  docs/developers/_index.md
  docs/developers/controllers.md
  docs/developers/library-usage.md
  docs/developers/releasing.md
  docs/investigations/_index.md
  docs/investigations/logical-clusters.md
  docs/investigations/minimal-api-server.md
  docs/investigations/self-service-policy.md
  docs/investigations/transparent-multi-cluster.md
  docs/kubectl-kcp-plugin.md
  docs/locations-and-scheduling.md
  docs/quickstart-tenancy-and-apis.md
  docs/syncer.md
  docs/virtual-workspaces.md
  docs/workspaces.md
  go.mod
  go.sum
  hack/generate/cli-doc/gen-cli-doc.go
  hack/third_party/github.com/spf13/cobra/doc/md_docs.go
  hack/third_party/github.com/spf13/cobra/doc/util.go
Labels: approved, lgtm

#2210 📖 Update syncer doc on apiexports flag
  docs/syncer.md
Labels: approved, lgtm

#2205 🌱 cmd/kcp: use structural logging
  cmd/kcp/kcp.go
  hack/logcheck.out
Labels: approved, lgtm

#2197 🌱 e2e framework: introduce KcpConfigOption function
  test/e2e/audit/audit_log_test.go
  test/e2e/framework/kcp.go
  test/e2e/homeworkspaces/home_workspaces_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
Labels: approved, lgtm

#2153 :book: add github actions to push docs
  .github/workflows/docs-gen-and-push.yaml
  Makefile
  hack/generate/cli-doc/gen-cli-doc.go
  hack/generate/crd-ref/config.yaml
  hack/generate/crd-ref/crd.template.md
  hack/generate/crd-ref/run-crd-ref-gen.sh
  hack/verify-go-versions.sh
Labels: approved, lgtm

#2213 🌱 cache: replicate all APIExports and APIResourceSchemas
  pkg/reconciler/cache/replication/replication_controller.go
Labels: area/sharding, approved, lgtm

#2206 🌱 cmd/syncer: switch to contextual logging
  cmd/syncer/cmd/syncer.go
  hack/logcheck.out
Labels: approved, lgtm

#2223 :book: Fix docs deploy github action
  .github/workflows/docs-gen-and-push.yaml
  docs/content/en/main/cli/_index.md
Labels: approved, lgtm

#2227 🐛 kcp: run the embeeded cache server only when a kubeconfig was provided
  pkg/server/server.go
Labels: approved, lgtm

#2228 🐛 replication: fix the Kind for APIResourceSchema
  pkg/reconciler/cache/replication/replication_reconcile.go
Labels: approved, lgtm

#2224 :seedling: pkg/authorization: rename apibinding_authorizer to maximal_permission_policy_authorizer
  config/crds/apis.kcp.dev_apiexports.yaml
  docs/content/en/main/concepts/authorization.md
  pkg/apis/apis/v1alpha1/types_apiexport.go
  pkg/authorization/maximal_permission_policy_authorizer.go
  pkg/openapi/zz_generated.openapi.go
  pkg/server/options/authorization.go
  test/e2e/apibinding/maximalpermissionpolicy_authorizer_test.go
Labels: approved, lgtm, kind/api-change

#2226 🐛 cache: fix a datarace
  pkg/cache/server/server.go
Labels: approved, lgtm

#2238 :bug: Fix Dockerfile by copying tmc directory into build directory
  Dockerfile
Labels: approved, lgtm, ok-to-test

#2027 :sparkles: Add command to create APIBindings
  cmd/kubectl-kcp/cmd/kubectlKcp.go
  contrib/demos-unmaintained/demo/prototype3-script/apibinding/cert-manager-apibinding.yaml
  pkg/cliplugins/bind/cmd/cmd.go
  pkg/cliplugins/bind/plugin/bind.go
Labels: approved, lgtm

#2242 :bug: fix CLI tree not showing bottom leafs
  pkg/cliplugins/workspace/plugin/kubeconfig.go
Labels: approved, lgtm, needs-ok-to-test

#2246 :sparkles: virtual/workspaces: add metrics for authorization cache syncs
  pkg/virtual/workspaces/authorization/cache.go
  pkg/virtual/workspaces/authorization/cache_test.go
  pkg/virtual/workspaces/authorization/metrics/metrics.go
  pkg/virtual/workspaces/builder/build.go
  pkg/virtual/workspaces/builder/clusterworkspaces.go
Labels: approved, lgtm

#2248 🌱 Register workspace authz metrics
  pkg/virtual/workspaces/builder/build.go
Labels: approved, lgtm

#2189 🐛 Correctly serve APIBindings in the APIExport virtual workspace
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
  pkg/reconciler/apis/apibinding/conflict_checker.go
  pkg/reconciler/apis/apibinding/conflict_checker_test.go
  pkg/virtual/apiexport/builder/build.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
  test/e2e/virtual/apiexport/apibindings_access_binding1.yaml
  test/e2e/virtual/apiexport/apibindings_access_binding2.yaml
  test/e2e/virtual/apiexport/apibindings_access_binding3.yaml
  test/e2e/virtual/apiexport/apibindings_access_export1.yaml
  test/e2e/virtual/apiexport/apibindings_access_export2.yaml
  test/e2e/virtual/apiexport/apibindings_access_export3.yaml
  test/e2e/virtual/apiexport/apibindings_access_schema1.yaml
  test/e2e/virtual/apiexport/apibindings_access_schema2.yaml
  test/e2e/virtual/apiexport/apibindings_access_schema3.yaml
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: area/apiexports, approved, lgtm

#2250 🌱 remove unused informer
  pkg/syncer/status/status_controller.go
  pkg/syncer/status/status_process_test.go
  pkg/syncer/syncer.go
Labels: approved, lgtm

#2253 :bug: permissionclaim_labeler: use accepted claims in spec to drive labels
  pkg/permissionclaim/permissionclaim_labeler.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
Labels: approved, lgtm

#2203 :sparkles: Add command for fetching permission claims
  cmd/kubectl-kcp/cmd/kubectlKcp.go
  pkg/cliplugins/claims/cmd/cmd.go
  pkg/cliplugins/claims/plugin/claims.go
Labels: approved, lgtm

#2257 :sparkles: *: migrate to use cluster-aware apiextensions-apiserver clients, listers and informers
  cmd/cluster-controller/main.go
  cmd/crd-puller/pull-crds.go
  config/crds/bootstrap.go
  config/rootcompute/bootstrap.go
  go.mod
  go.sum
  pkg/admission/kubequota/kubequota_admission.go
  pkg/admission/limitranger/admission.go
  pkg/admission/mutatingwebhook/plugin.go
  pkg/admission/namespacelifecycle/admission.go
  pkg/admission/validatingwebhook/plugin.go
  pkg/cache/server/bootstrap/bootstrap.go
  pkg/cache/server/config.go
  pkg/cache/server/crd_lister.go
  pkg/cliplugins/workload/plugin/sync.go
  pkg/informer/informer.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apiresource/controller.go
  pkg/reconciler/apis/apiresource/negotiation.go
  pkg/reconciler/kubequota/kubequota_controller.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_reconcile.go
  pkg/server/apiextensions.go
  pkg/server/config.go
  pkg/server/controllers.go
  pkg/syncer/apiimporter.go
  pkg/syncer/namespace/namespace_downstream_controller.go
  pkg/syncer/namespace/namespace_downstream_process.go
  pkg/syncer/namespace/namespace_downstream_process_test.go
  pkg/syncer/namespace/namespace_upstream_controller.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_controller.go
  pkg/syncer/status/status_process.go
  pkg/syncer/status/status_process_test.go
  pkg/syncer/syncer.go
  pkg/virtual/framework/client/dynamic/client.go
  pkg/virtual/framework/forwardingregistry/store.go
  pkg/virtual/framework/wrappers/rbac/cluster_filtering.go
  pkg/virtual/framework/wrappers/rbac/merging.go
  pkg/virtual/workspaces/authorization/cache.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/conformance/metadata_test.go
  test/e2e/conformance/webhook_test.go
  test/e2e/customresourcedefinition/customresourcedefinition_test.go
  test/e2e/fixtures/kcp-test-image/icc-test.go
  test/e2e/fixtures/kube/bootstrap.go
  test/e2e/fixtures/wildwest/bootstrap.go
  test/e2e/framework/syncer.go
  test/e2e/quota/quota_test.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/virtual/apiexport/authorizer_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: approved, lgtm, kind/api-change

#2209 🌱 cmd/test-server/kcp/shard.go: use contextual logging
  cmd/test-server/kcp/shard.go
  hack/logcheck.out
Labels: approved, lgtm

#2178 :seedling: proxy: Optionally enable token auth
  Makefile
  cmd/sharded-test-server/shard.go
  pkg/proxy/config.go
  pkg/proxy/filters/filters.go
  pkg/proxy/mapping.go
  pkg/proxy/options/authentication.go
  pkg/proxy/proxy.go
  pkg/proxy/server.go
Labels: approved, lgtm

#2255 📖 Updated README.md links
  README.md
Labels: approved, lgtm, ok-to-test

#2259 :seedling: hack: remove run-sharded-kcp.sh
  hack/run-sharded-kcp.sh
Labels: approved, lgtm

#2265 :seedling: make: add non-kind shared and sharded e2e
  .github/workflows/ci.yaml
  Makefile
  test/e2e/audit/audit_log_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/authorizer/serviceaccounts_test.go
  test/e2e/framework/accessory.go
  test/e2e/framework/expect.go
  test/e2e/framework/kcp.go
  test/e2e/framework/syncer.go
  test/e2e/homeworkspaces/home_workspaces_test.go
  test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/syncer/tunnels_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm

#2266 :seedling: test/e2e: add the concept of suites, allow selecting
  Makefile
  test/e2e/apibinding/apibinding_deletion_test.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
  test/e2e/apibinding/apibinding_protected_test.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/apibinding/apibinding_webhook_test.go
  test/e2e/apibinding/maximalpermissionpolicy_authorizer_test.go
  test/e2e/audit/audit_log_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/authorizer/rootcacertconfigmap_test.go
  test/e2e/authorizer/serviceaccounts_test.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/conformance/metadata_test.go
  test/e2e/conformance/webhook_test.go
  test/e2e/customresourcedefinition/customresourcedefinition_test.go
  test/e2e/framework/config.go
  test/e2e/framework/suites.go
  test/e2e/framework/syncer.go
  test/e2e/homeworkspaces/home_workspaces_test.go
  test/e2e/quota/quota_test.go
  test/e2e/reconciler/apiexport/apiexport_controller_test.go
  test/e2e/reconciler/cache/replication_test.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/clusterworkspace/apibinding_initializer_test.go
  test/e2e/reconciler/clusterworkspace/controller_test.go
  test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
  test/e2e/reconciler/clusterworkspaceshard/controller_test.go
  test/e2e/reconciler/locationworkspace/local_apiexport_test.go
  test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
  test/e2e/reconciler/locationworkspace/rootcompute_test.go
  test/e2e/reconciler/locationworkspace/synctarget_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/syncer/tunnels_test.go
  test/e2e/virtual/apiexport/authorizer_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
  test/e2e/watchcache/watchcache_enabled_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm

#2267 📖 Fix grammar of kcp command help message
  cmd/kcp/kcp.go
Labels: approved, lgtm, ok-to-test

#2264 :bug: Avoid syncers deleting namespace from other synctargets.
  pkg/syncer/namespace/namespace_downstream_process.go
  pkg/syncer/namespace/namespace_downstream_process_test.go
Labels: approved, lgtm

#2221 ✨ Add transformations during request forwarding...
  pkg/virtual/framework/client/dynamic/client.go
  pkg/virtual/framework/transforming/client.go
  pkg/virtual/framework/transforming/transformer.go
  pkg/virtual/framework/transforming/transformer_test.go
  pkg/virtual/framework/transforming/watcher.go
Labels: approved, lgtm

#2270 :bug: quota: use a workqueue to manage updating monitors
  pkg/reconciler/kubequota/kubequota_controller.go
Labels: approved, lgtm

#2252 :sparkles: virtual/workspaces: allow configuring authorization cache resync
  cmd/sharded-test-server/shard.go
  cmd/test-server/kcp/shard.go
  pkg/server/options/flags.go
  pkg/virtual/workspaces/authorization/cache.go
  pkg/virtual/workspaces/builder/build.go
  pkg/virtual/workspaces/builder/clusterworkspaces.go
  pkg/virtual/workspaces/options/options.go
  test/e2e/framework/kcp.go
Labels: approved, lgtm

#2276 :sparkles: virtual/workspaces: allow configuring authorization cache resync
  cmd/sharded-test-server/shard.go
  cmd/test-server/kcp/shard.go
  pkg/server/options/flags.go
  pkg/virtual/workspaces/authorization/cache.go
  pkg/virtual/workspaces/builder/build.go
  pkg/virtual/workspaces/builder/clusterworkspaces.go
  pkg/virtual/workspaces/options/options.go
  test/e2e/framework/kcp.go
Labels: approved, lgtm

#2273 :seedling: test/e2e: stop dumping YAML
  test/e2e/framework/workspaces.go
  test/e2e/quota/quota_test.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/syncer/syncer_test.go
Labels: approved, lgtm

#2277 :bug: .github: cache Go build output
  .github/workflows/ci.yaml
Labels: approved, lgtm

#2275 :seedling: .github: restrict kind tests to those that require it
  .github/workflows/ci.yaml
  Makefile
Labels: approved, lgtm

#2279 :seedling: test/e2e: add more logging for syncer e2e
  test/e2e/syncer/syncer_test.go
Labels: approved, lgtm

#2222 :seedling: pkg/../types_apiexport: add name, namespace
  config/crds/apis.kcp.dev_apibindings.yaml
  config/crds/apis.kcp.dev_apiexports.yaml
  pkg/apis/apis/v1alpha1/types_apiexport.go
  pkg/apis/apis/v1alpha1/types_apiexport_test.go
  pkg/apis/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/go.mod
  pkg/apis/test/pattern.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
  test/e2e/reconciler/clusterworkspace/apibinding_initializer_test.go
  test/e2e/virtual/apiexport/authorizer_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm, kind/api-change

#2258 ✨ Add bind workload cmd
  pkg/cliplugins/bind/cmd/cmd.go
  pkg/cliplugins/bind/plugin/bind_compute.go
  pkg/cliplugins/workload/plugin/sync.go
  pkg/reconciler/workload/defaultplacement/defaultplacement_controller.go
  pkg/reconciler/workload/defaultplacement/defaultplacement_indexes.go
  pkg/server/controllers.go
  pkg/server/server.go
  test/e2e/framework/bind.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/locationworkspace/local_apiexport_test.go
  test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
  test/e2e/reconciler/locationworkspace/rootcompute_test.go
  test/e2e/reconciler/locationworkspace/synctarget_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/syncer/tunnels_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm
