Repository kcp-dev/kcp, pull requests merged in 2022-09, with the labels that each got.

#1756 modified cmd.Use for kubectl-workspaces
  pkg/cliplugins/workspace/cmd/cmd.go
Labels: approved, lgtm, ok-to-test

#1851 bump to the latest kube level
  go.mod
  go.sum
Labels: approved, lgtm

#1876 Makefile: add update-contextual-logging
  Makefile
  hack/verify-contextual-logging.sh
Labels: approved, lgtm

#1880 resource controller: fix NPE
  pkg/reconciler/workload/resource/resource_controller.go
Labels: approved, lgtm

#1883 KCP: stop messing with the RawPath
  pkg/server/handler.go
  pkg/virtual/framework/rootapiserver/root_apiserver.go
Labels: approved, lgtm

#1841 cache-server: adds WithShardScope HTTP filter
  pkg/cache/server/config.go
  pkg/cache/server/handler.go
  pkg/cache/server/options/options.go
Labels: approved, lgtm

#1854 virtual: Support SSA patch requests for non-existent objects
  pkg/virtual/framework/forwardingregistry/rest_test.go
  pkg/virtual/framework/forwardingregistry/store.go
  pkg/virtual/framework/forwardingregistry/store_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm

#1563 virtual/apiexport: serve wildcard apibindings
  config/crds/bootstrap.go
  hack/logcheck.out
  pkg/admission/apibinding/apibinding_admission.go
  pkg/admission/apibinding/apibinding_admission_test.go
  pkg/admission/permissionclaims/mutating_permission_claims.go
  pkg/apis/apis/v1alpha1/permissionclaims/labels.go
  pkg/apis/apis/v1alpha1/types_apibinding.go
  pkg/permissionclaim/permissionclaim_labeler.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_reconcile.go
  pkg/virtual/apiexport/builder/build.go
  pkg/virtual/apiexport/builder/forwarding.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
  pkg/virtual/apiexport/schemas/apis.go
  pkg/virtual/framework/forwardingregistry/rest.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/initializingworkspaces/builder/forwarding.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Labels: approved, lgtm, kind/api-change

#1775 Syncer docs: adds a guide on running the syncer locally and updates slightly outdated doc
  docs/syncer.md
Labels: approved, lgtm, ok-to-test

#1799 bump strategic-merge-diff to 4.2.3
  go.mod
  go.sum
Labels: approved, lgtm

#1827 Delete downstream namespace on upstream deletion
  pkg/cliplugins/workload/plugin/sync_test.go
  pkg/cliplugins/workload/plugin/syncer.yaml
  pkg/syncer/namespace/namespace_controller.go
  pkg/syncer/namespace/namespace_process.go
  pkg/syncer/namespace/namespace_process_test.go
  pkg/syncer/syncer.go
  test/e2e/syncer/syncer_test.go
Labels: approved, lgtm

#1884 Update usage text for virtual-workspaces to be accurate
  cmd/virtual-workspaces/command/cmd.go
Labels: approved, lgtm, ok-to-test

#1776 virtual/workspaces: do not filter if able to get all
  pkg/authorization/toplevel_org_authorizer.go
  pkg/authorization/workspace_content_authorizer.go
  pkg/virtual/workspaces/builder/build.go
  pkg/virtual/workspaces/registry/rest.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
Labels: approved, lgtm

#1886 Add initial release process docs
  docs/developers/releasing.md
Labels: approved, lgtm

#873 Syncer Tunneler: Pod logs, ....
  cmd/syncer/options/options.go
  go.mod
  go.sum
  hack/logcheck.out
  hack/verify-contextual-logging.sh
  pkg/cliplugins/workload/cmd/cmd.go
  pkg/cliplugins/workload/plugin/sync.go
  pkg/cliplugins/workload/plugin/sync_test.go
  pkg/cliplugins/workload/plugin/syncer.yaml
  pkg/features/kcp_features.go
  pkg/server/config.go
  pkg/syncer/syncer.go
  pkg/syncer/tunneler.go
  pkg/tunneler/dialer.go
  pkg/tunneler/integration_test.go
  pkg/tunneler/listener.go
  pkg/tunneler/listener_test.go
  pkg/tunneler/tunnel.go
  test/e2e/framework/kcp.go
  test/e2e/framework/syncer.go
  test/e2e/syncer/tunnels_test.go
Labels: approved, lgtm

#1889 pkg/virtual/workspaces/registry: fix panic sending to a closed channel
  pkg/virtual/workspaces/registry/rest.go
Labels: lgtm

#1892 docs/architecture: remove because totally outdated
  docs/architecture/README.md
  docs/architecture/cluster-controller.png
  docs/architecture/deployment-splitter.png
  docs/architecture/kcp.png
  docs/architecture/syncer.png
Labels: approved, lgtm

#1894 Update README.md golang version and add to verify script
  README.md
  hack/verify-go-versions.sh
Labels: approved, lgtm, ok-to-test

#1900 Fix ctrl-c not gracefully terminating
  go.mod
  go.sum
Labels: approved, lgtm

#1701 Simplify plugin code
  pkg/cliplugins/base/options.go
  pkg/cliplugins/crd/cmd/cmd.go
  pkg/cliplugins/crd/plugin/options.go
  pkg/cliplugins/crd/plugin/snapshot.go
  pkg/cliplugins/crd/plugin/snapshot_test.go
  pkg/cliplugins/workload/cmd/cmd.go
  pkg/cliplugins/workload/plugin/config.go
  pkg/cliplugins/workload/plugin/sync.go
  pkg/cliplugins/workload/plugin/workload.go
  pkg/cliplugins/workspace/cmd/cmd.go
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/cliplugins/workspace/plugin/kubeconfig_test.go
Labels: approved, lgtm

#1911 Update readme
  README.md
  docs/concepts.md
  hack/verify-go-versions.sh
Labels: approved, lgtm, kind/documentation

#1920 pkg/authorization/apibinding_authorizer: fix nil panic
  pkg/authorization/apibinding_authorizer.go
Labels: approved, lgtm

#1925 fix readme typo
  README.md
Labels: approved, lgtm, ok-to-test

#1917 fix filename for negotiatedapiresources
  pkg/apis/apiresource/v1alpha1/negotiatedapiresource_helpers.go
  pkg/apis/apiresource/v1alpha1/negotiatedapiresource_types.go
Labels: approved, lgtm, ok-to-test

#1927 cache-client: fix npe when the context wasn't set
  pkg/cache/client/context.go
Labels: approved, lgtm

#1915 verify-go-versions.sh make CONTRIBUTING.md check conditional
  hack/verify-go-versions.sh
Labels: approved, lgtm

#1926 cache-server: adds ShardNameFromObjectRoundTripper
  pkg/cache/client/round_tripper.go
  pkg/cache/client/shard/shard.go
Labels: approved, lgtm

#1940 🐛 Fix generated APIResourceSchema names
  config/root-phase0/apiexport-scheduling.kcp.dev.yaml
  config/root-phase0/apiexport-tenancy.kcp.dev.yaml
  config/root-phase0/apiexport-workload.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspaces.tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-placements.scheduling.kcp.dev.yaml
  config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
Labels: approved, lgtm

#1941 Enable PR verifier
  .github/pull_request_template.md
  .github/workflows/pr-verifier.yaml
Labels: approved, lgtm

#1928 🌱 cache: makes all internal clients shard and cluster aware
  pkg/cache/client/round_tripper.go
  pkg/cache/server/bootstrap/bootstrap.go
  pkg/cache/server/config.go
  pkg/cache/server/handler.go
Labels: approved, lgtm

#1947 :seedling: cache: moves common HTTP handlers to a shared pkg
  pkg/cache/server/config.go
  pkg/server/apiextensions.go
  pkg/server/apiextensions_test.go
  pkg/server/config.go
  pkg/server/filters/filters.go
  pkg/server/filters/filters_test.go
  pkg/server/handler.go
  pkg/server/handler_test.go
Labels: approved, lgtm

#1896 📝 documents the cache-server
  docs/cache-server.md
Labels: approved, lgtm

#1953 🐛 Don't calculate new placements for resources that are being deleted
  pkg/reconciler/workload/resource/resource_reconcile.go
  pkg/reconciler/workload/resource/resource_reconcile_test.go
Labels: approved, lgtm

#1951 🌱 pkg/util: delete
  pkg/cache/server/server.go
  pkg/server/controllers.go
  pkg/server/server.go
  pkg/util/util.go
Labels: approved, lgtm

#1957 :bug: *: split meta namespace keys correctly
  pkg/admission/kubequota/kubequota_clusterworkspace_monitor.go
  pkg/reconciler/apis/identitycache/api_export_identity_controller.go
  pkg/reconciler/kubequota/kubequota_controller.go
  pkg/reconciler/scheduling/location/location_controller.go
  pkg/reconciler/scheduling/placement/placement_controller.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
  pkg/reconciler/workload/namespace/namespace_controller.go
  pkg/reconciler/workload/placement/placement_controller.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
Labels: approved, lgtm, kind/api-change

#1949 :seedling: cache: small refactor to make wiring into kcp easier
  cmd/cache-server/main.go
  pkg/cache/server/options/options.go
  pkg/cache/server/server.go
Labels: approved, lgtm

#1907 🌱 Update golangci-lint / enable more linters
  .golangci.yaml
  Makefile
  cmd/crd-puller/pull-crds.go
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/main.go
  cmd/sharded-test-server/virtual.go
  cmd/test-server/helpers/writer.go
  cmd/test-server/kcp/shard.go
  cmd/test-server/main.go
  pkg/admission/apiresourceschema/admission_test.go
  pkg/admission/clusterworkspacetypeexists/admission_test.go
  pkg/admission/mutatingwebhook/plugin.go
  pkg/admission/reservedmetadata/admission.go
  pkg/admission/validatingwebhook/plugin.go
  pkg/authorization/apibinding_authorizer.go
  pkg/cache/server/server.go
  pkg/cliplugins/workload/plugin/sync.go
  pkg/crdpuller/discovery.go
  pkg/embeddedetcd/config.go
  pkg/localenvoy/controllers/ingress/envoyingress.go
  pkg/localenvoy/controlplane/translator.go
  pkg/proxy/mapping.go
  pkg/proxy/proxy.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go
  pkg/reconciler/apis/apiresource/negotiation.go
  pkg/reconciler/apis/apiresource/startup.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_phase.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go
  pkg/reconciler/workload/ingresssplitter/ingresssplitter_controller.go
  pkg/server/config.go
  pkg/server/controllers.go
  pkg/server/options/authentication.go
  pkg/server/options/options.go
  pkg/server/server.go
  pkg/syncer/apiimporter.go
  pkg/syncer/shared/namespace.go
  pkg/syncer/status/status_process.go
  pkg/syncer/syncer.go
  pkg/virtual/framework/dynamic/apiserver/handler_test.go
  pkg/virtual/workspaces/builder/build.go
  pkg/virtual/workspaces/builder/org_listener.go
  test/e2e/apibinding/apibinding_authorizer_test.go
  test/e2e/fixtures/apifixtures/apibinding.go
  test/e2e/fixtures/apifixtures/sheriffs.go
  test/e2e/fixtures/webhook/webhook.go
  test/e2e/framework/accessory.go
  test/e2e/framework/kubectl.go
  test/e2e/reconciler/ingress/controller_test.go
  test/e2e/syncer/tunnels_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash, kind/api-change

#1978 :bug: syncer: bifurcate the namespace controller
  pkg/syncer/namespace/namespace_downstream_controller.go
  pkg/syncer/namespace/namespace_downstream_process.go
  pkg/syncer/namespace/namespace_downstream_process_test.go
  pkg/syncer/namespace/namespace_upstream_controller.go
  pkg/syncer/namespace/namespace_upstream_process.go
  pkg/syncer/namespace/namespace_upstream_process_test.go
  pkg/syncer/syncer.go
Labels: approved, lgtm

#1985 :bug: syncer: use the correct key splitter
  hack/logcheck.out
  pkg/syncer/status/status_process.go
Labels: approved, lgtm

#1958 :sparkles: *: use cluster-aware keyfuncs & splitters
  go.mod
  go.sum
  pkg/admission/kubequota/kubequota_clusterworkspace_monitor.go
  pkg/indexers/apiexport.go
  pkg/localenvoy/controllers/ingress/envoyingresscontroller.go
  pkg/localenvoy/controlplane/translator.go
  pkg/proxy/index/index_controller.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/reconciler/apis/apiresource/controller.go
  pkg/reconciler/apis/apiresource/negotiation.go
  pkg/reconciler/apis/identitycache/api_export_identity_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_controller.go
  pkg/reconciler/kubequota/kubequota_controller.go
  pkg/reconciler/scheduling/location/location_controller.go
  pkg/reconciler/scheduling/placement/placement_controller.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/clusterworkspace_deletion_controller.go
  pkg/reconciler/tenancy/clusterworkspaceshard/clusterworkspaceshard_controller.go
  pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller.go
  pkg/reconciler/workload/apiexport/workload_apiexport_controller.go
  pkg/reconciler/workload/apiexportcreate/apiexportcreate_controller.go
  pkg/reconciler/workload/basecontroller/controller.go
  pkg/reconciler/workload/defaultplacement/defaultplacement_controller.go
  pkg/reconciler/workload/deploymentsplitter/deploymentsplitter_controller.go
  pkg/reconciler/workload/deploymentsplitter/deploymentsplitter_reconcile.go
  pkg/reconciler/workload/ingresssplitter/ingresssplitter_controller.go
  pkg/reconciler/workload/ingresssplitter/tracker.go
  pkg/reconciler/workload/ingresssplitter/tracker_test.go
  pkg/reconciler/workload/namespace/namespace_controller.go
  pkg/reconciler/workload/placement/placement_controller.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/reconciler/workload/synctarget/synctarget_controller.go
  pkg/reconciler/workload/synctargetexports/synctargetexports_controller.go
  pkg/syncer/apiimporter.go
  pkg/syncer/namespace/namespace_upstream_controller.go
  pkg/syncer/namespace/namespace_upstream_process.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_process_test.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_controller.go
  pkg/virtual/workspaces/authorization/cache.go
  test/e2e/framework/expect.go
  test/e2e/reconciler/cluster/controller_test.go
Labels: approved, lgtm, kind/api-change

#1871 🌱 WithClusterScope: should not assign a default cluster name
  pkg/server/filters/filters.go
  pkg/server/home_workspaces.go
  pkg/server/home_workspaces_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
Labels: approved, lgtm

#1962 :sparkles: feature: Add root compute workspace
  config/rootcompute/bootstrap.go
  config/rootcompute/clusterworkspace-compute.yaml
  config/rootcompute/kube-1.24/apiexport-kubernetes.k8s.io.yaml
  config/rootcompute/kube-1.24/apiresourceschema_deployments.apps.yaml
  config/rootcompute/kube-1.24/apiresourceschema_ingresses.networking.k8s.io.yaml
  config/rootcompute/kube-1.24/apiresourceschema_services.yaml
  config/rootcompute/kube-1.24/bootstrap.go
  pkg/server/options/batteries/batteries.go
  pkg/server/server.go
  test/e2e/fixtures/kube/apps.k8s.io_deployments.yaml
  test/e2e/fixtures/kube/core.k8s.io_services.yaml
  test/e2e/reconciler/locationworkspace/apiresourceschema_service.yaml
  test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
  test/e2e/reconciler/locationworkspace/rootcompute_test.go
  test/e2e/reconciler/locationworkspace/synctarget_test.go
Labels: approved, lgtm

#2003 🌱 Update Kubernetes to reduce schema validation allocations
  go.mod
  go.sum
Labels: approved, lgtm, tide/merge-method-squash

#2001 :seedling: Update batteries-included option usage
  pkg/server/options/options.go
Labels: approved, lgtm

#2026 :bug: Fix scripts to run on mac with gnu sed
  hack/bump-k8s.sh
  hack/verify-contextual-logging.sh
Labels: approved, lgtm, ok-to-test

#2029 :bug: pkg/admission/webhook: fix nil panic
  pkg/admission/webhook/generic_webhook.go
Labels: approved, lgtm, kind/api-change

#2031 :bug: pkg/admission/webhook: differentiate states
  pkg/admission/webhook/generic_webhook.go
Labels: approved, lgtm, kind/api-change

#1954 🌱 Wire the cache server into the kcp server
  cmd/cache-server/main.go
  pkg/cache/server/config.go
  pkg/cache/server/server.go
  pkg/server/cache.go
  pkg/server/options/cache.go
  pkg/server/options/options.go
  pkg/server/server.go
Labels: approved, lgtm

#2033 🐛 bug fix Add maximal permission policy for compute APIExport
  config/rootcompute/kube-1.24/clusterrole-kubernetes-maximal-permission-policy.yaml
  config/rootcompute/kube-1.24/clusterrolebinding-kubernetes-maximal-permission-policy.yaml
  test/e2e/reconciler/locationworkspace/rootcompute_test.go
Labels: approved, lgtm

#2040 🌱 Update community meeting template
  .github/ISSUE_TEMPLATE/community_meeting.yaml
Labels: approved, lgtm

#2042 :seedling: pkg/proxy use contextual logging
  hack/logcheck.out
  pkg/proxy/handler.go
  pkg/proxy/index/index_controller.go
Labels: approved, lgtm

#2043 :seedling: cmd/kcp-front-proxy move filters into module
  cmd/kcp-front-proxy/filters/filters.go
  cmd/kcp-front-proxy/main.go
Labels: approved, lgtm

#2045 :seedling: test/e2e: enable audit logs
  test/e2e/framework/audit-policy.yaml
  test/e2e/framework/kcp.go
  test/e2e/framework/util.go
Labels: approved, lgtm

#2047 :seedling: pkg/server: enable audit logging in virtual workspace apiserver
  cmd/virtual-workspaces/command/cmd.go
  cmd/virtual-workspaces/options/options.go
  pkg/server/server.go
  pkg/server/virtual.go
Labels: approved, lgtm

#1996 🌱 authorisation: stop using the ValidClusterFrom method
  pkg/authorization/local_authorizer.go
  pkg/authorization/system_crd_authorizer.go
  pkg/authorization/toplevel_org_authorizer.go
  pkg/authorization/workspace_content_authorizer.go
Labels: approved, lgtm

#1882 ✨ pkg/virtual/apiexport: add maximal permission policy authorization
  docs/authorization.md
  pkg/authorization/anonymizer.go
  pkg/authorization/apibinding_authorizer.go
  pkg/authorization/audit_logger.go
  pkg/authorization/bootstrap_policy_authorizer.go
  pkg/authorization/decision.go
  pkg/authorization/local_authorizer.go
  pkg/authorization/toplevel_org_authorizer.go
  pkg/server/apiextensions.go
  pkg/server/config.go
  pkg/server/handler.go
  pkg/virtual/apiexport/authorizer/content.go
  pkg/virtual/apiexport/authorizer/content_test.go
  pkg/virtual/apiexport/authorizer/maximal_permission_policy.go
  pkg/virtual/apiexport/authorizer/maximal_permission_policy_test.go
  pkg/virtual/apiexport/builder/build.go
  pkg/virtual/apiexport/options/options.go
  pkg/virtual/framework/forwardingregistry/store.go
  test/e2e/fixtures/apifixtures/apibinding.go
  test/e2e/framework/auth-tokens.csv
  test/e2e/virtual/apiexport/authorizer_test.go
  test/e2e/virtual/apiexport/crd_cowboys.yaml
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm, tide/merge-method-squash

#2058 🐛 Fix kubectl overrides in 'kubectl workspace' plugin commands
  pkg/cliplugins/workspace/cmd/cmd.go
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/cliplugins/workspace/plugin/options.go
Labels: approved, lgtm

#2060 :seedling: apibinding, types: remove ancestor check
  config/crds/apis.kcp.dev_apibindings.yaml
  config/crds/workload.kcp.dev_synctargets.yaml
  config/root-phase0/apiexport-workload.kcp.dev.yaml
  config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
  pkg/admission/apibinding/apibinding_admission.go
  pkg/admission/apibinding/apibinding_admission_test.go
  pkg/apis/apis/v1alpha1/types_apibinding.go
  pkg/openapi/zz_generated.openapi.go
  pkg/virtual/framework/internalapis/fixtures/synctargets.yaml
Labels: approved, lgtm, kind/api-change

#2067 :bug: apis: use correct annotation to require fields
  pkg/apis/apis/v1alpha1/types_apiexport.go
  pkg/apis/scheduling/v1alpha1/types_location.go
  pkg/apis/scheduling/v1alpha1/types_placement.go
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/apis/workload/v1alpha1/synctarget_types.go
Labels: approved, lgtm, kind/api-change

#2044 🌱 proxy: pass context for contextual logging
  cmd/kcp-front-proxy/main.go
  hack/logcheck.out
  pkg/proxy/index/index_controller.go
  pkg/proxy/mapping.go
Labels: approved, lgtm

#2053 🌱 kcp: controllers don't have to check if caches have been synced during startup
  pkg/reconciler/kubequota/kubequota_controller.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
Labels: approved, lgtm

#2020 :seedling: tenancy: allow single-character logical cluster names
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/tenancy/v1alpha1/helper/helper.go
  pkg/apis/tenancy/v1alpha1/helper/helper_test.go
Labels: approved, lgtm, ok-to-test

#2055 🐛 syncer: remove finalizer if downstream resource has been deleted
  pkg/syncer/shared/finalizer.go
  pkg/syncer/status/status_process_test.go
Labels: approved, lgtm

#2074 :seedling: turn off goreleaser from PRs and pushes to main
  .github/workflows/goreleaser.yml
Labels: approved, lgtm, ok-to-test

#2070 🌱 Upgrade to logicalcluster v2.0.0-alpha.3
  go.mod
  go.sum
Labels: approved, lgtm

#2069 :seedling: Move VW registry's rest file to contextual logging
  hack/logcheck.out
  pkg/virtual/workspaces/registry/rest.go
Labels: approved, lgtm

#2054 :seedling: syncer(apiimporter,syncer,tunneler}: use structured, contextual logging
  hack/logcheck.out
  pkg/syncer/apiimporter.go
  pkg/syncer/syncer.go
  pkg/syncer/tunneler.go
Labels: approved, lgtm, needs-ok-to-test

#2063 🌱 cache server: stop serving subresources for built-in resources
  pkg/cache/server/bootstrap/bootstrap.go
Labels: approved, lgtm

#2019 :seedling: Add ppc64le support to e2e test workflow
  .github/workflows/OWNERS
  .github/workflows/e2e-ci-ppc64le.yml
  Makefile
Labels: approved, lgtm, ok-to-test

#2077 :bug: Add trailing slash to COPY command in Dockerfile
  Dockerfile
Labels: approved, lgtm

#2079 :seedling: Combine Dockerfile kubectl layers to save space
  Dockerfile
Labels: approved, lgtm

#1877 ✨Add support for default APIBindings to create per ClusterWorkspaceType when initializing a workspace
  config/crds/tenancy.kcp.dev_clusterworkspaces.yaml
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml
  config/crds/tenancy.kcp.dev_workspaces.yaml
  config/homebucket/bootstrap.go
  config/homeroot/bootstrap.go
  config/root-phase0/apiexport-tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspaces.tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspacetypes.tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-workspaces.tenancy.kcp.dev.yaml
  config/root/clusterworkspacetype-homebucket.yaml
  config/root/clusterworkspacetype-homeroot.yaml
  config/root/clusterworkspacetype-universal.yaml
  config/universal/bootstrap.go
  hack/logcheck.out
  pkg/admission/clusterworkspacetypeexists/admission.go
  pkg/admission/clusterworkspacetypeexists/admission_test.go
  pkg/apis/tenancy/projection/workspaces.go
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  pkg/authorization/apibinding_authorizer.go
  pkg/authorization/bootstrap/policy.go
  pkg/indexers/apibinding.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/committer/committer.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_phase.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_reconcile.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_reconcile_test.go
  pkg/server/config.go
  pkg/server/controllers.go
  pkg/server/handler.go
  pkg/server/home_workspaces.go
  pkg/server/server.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/workspaces/registry/rest.go
  test/e2e/reconciler/clusterworkspace/apibinding_initializer_test.go
  test/e2e/reconciler/clusterworkspace/apiresourceschema_cowboys.yaml
  test/e2e/reconciler/clusterworkspace/support.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
Labels: approved, lgtm, kind/api-change

#2084 :seedling: Remove deploy task from github actions
  .github/workflows/kcp-image.yaml
Labels: lgtm

#2095 🐛 apibinder: don't use external address for now
  pkg/server/controllers.go
Labels: approved, lgtm

#2086 🐛 Avoid redundant delete in workspace deletion
  pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor_test.go
Labels: approved, lgtm

#2091 :bug: Allow go to determine ARCH and OS during build
  Makefile
Labels: approved, lgtm, ok-to-test

#2049 🐛 syncer/status: make sure the resource is owned by this syncer before updating the status
  hack/logcheck.out
  pkg/syncer/status/status_process.go
  pkg/syncer/status/status_process_test.go
Labels: approved, lgtm

#2097 🐛 fix OS and ARCH not being properly initialized
  Makefile
Labels: approved, lgtm, ok-to-test

#2083 :seedling: authz: remove the concept of a merged informer
  pkg/authorization/apibinding_authorizer.go
  pkg/authorization/local_authorizer.go
  pkg/authorization/toplevel_org_authorizer.go
  pkg/authorization/workspace_content_authorizer.go
  pkg/virtual/framework/wrappers/rbac/merging.go
Labels: approved, lgtm

#2098 🐛 Fix make install
  Makefile
Labels: approved, lgtm, ok-to-test

#2023 :sparkles: Add profiler support to front proxy and virtual workspaces
  cmd/kcp-front-proxy/main.go
  cmd/kcp-front-proxy/options/options.go
  cmd/virtual-workspaces/command/cmd.go
  cmd/virtual-workspaces/options/options.go
  hack/logcheck.out
  pkg/virtual/options/options.go
Labels: approved, lgtm, ok-to-test

#2096 🐛 syncer: apply name transformations to spec controller downstream informer
  pkg/syncer/shared/helpers.go
  pkg/syncer/shared/helpers_test.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/status/status_process.go
  test/e2e/syncer/syncer_test.go
Labels: approved, lgtm

#2100 📖 Update FAQ links to point to renamed concepts.md
  FAQ.md
Labels: approved, lgtm, ok-to-test

#2085 🌱 pkg/apis: update logicalcluster to v2.0.0-alpha.3
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: approved, lgtm

#2064 :book:Add a quickstart doc for tenancy and APIs
  docs/quickstart-tenancy-and-apis.md
Labels: approved, lgtm, ok-to-test

#2103 :seedling: Remove ingress splitter and deployment splitter which do not work currently...
  cmd/deployment-splitter/README.md
  cmd/deployment-splitter/main.go
  cmd/ingress-controller/README.md
  cmd/ingress-controller/main.go
  go.mod
  go.sum
  hack/logcheck.out
  pkg/localenvoy/OWNERS
  pkg/localenvoy/controllers/ingress/envoyingress.go
  pkg/localenvoy/controllers/ingress/envoyingresscontroller.go
  pkg/localenvoy/controlplane/controlplane.go
  pkg/localenvoy/controlplane/translator.go
  pkg/reconciler/workload/deploymentsplitter/deploymentsplitter_controller.go
  pkg/reconciler/workload/deploymentsplitter/deploymentsplitter_reconcile.go
  pkg/reconciler/workload/ingresssplitter/ingresssplitter_controller.go
  pkg/reconciler/workload/ingresssplitter/ingresssplitter_reconcile.go
  pkg/reconciler/workload/ingresssplitter/tracker.go
  pkg/reconciler/workload/ingresssplitter/tracker_test.go
  test/e2e/reconciler/ingress/controller_test.go
  test/e2e/reconciler/ingress/ingress.yaml
Labels: approved, lgtm

#2072 :seedling: Remove klog from tests
  hack/logcheck.out
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/clusterworkspace/controller_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
Labels: approved, lgtm

#2106 :bug: fix- nil context in workspace-use plugin
  pkg/cliplugins/workspace/cmd/cmd.go
Labels: approved, lgtm

#2109 🌱 cache-server: disable ServerSideApply feature
  pkg/cache/server/config.go
Labels: approved, lgtm

#1901 ✨ Add kubectl workspace plugin and adjust usage output
  .goreleaser.yaml
  Dockerfile
  Makefile
  cmd/kubectl-workspace/main.go
  cmd/kubectl-ws/main.go
  hack/logcheck.out
  pkg/cliplugins/workspace/cmd/cmd.go
Labels: approved, lgtm

#2024 🌱 cache: introduce the replication controller
  pkg/reconciler/cache/replication/indexers.go
  pkg/reconciler/cache/replication/replication_controller.go
  pkg/reconciler/cache/replication/replication_reconcile.go
  pkg/reconciler/cache/replication/replication_reconcile_apiexports_test.go
  pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
  pkg/reconciler/cache/replication/replication_reconcile_unstructured_test.go
Labels: approved, lgtm

#2108 :seedling: cmd/kcp-front-proxy: use component-base/cli Run
  cmd/kcp-front-proxy/main.go
Labels: approved, lgtm
