Repository kcp-dev/kcp, pull requests merged in 2022-07, with the labels that each got.

#1391 Noticed typo on the log
  pkg/virtual/workspaces/builder/build.go
Labels: approved, lgtm, ok-to-test

#1377 brings back the watch cache
  pkg/server/options/options.go
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: approved, lgtm

#1418 Exit build process if Kubernetes version is missing
  Makefile
Labels: approved, lgtm, ok-to-test

#1424 e2e: stop spamming entire objects
  test/e2e/framework/fixture.go
Labels: approved, lgtm

#1422 config: generate APIResourceSchemas and APIExports robustly
  cmd/apigen/main.go
  config/root-phase0/apiexport-apiresource.kcp.dev.yaml
  config/root-phase0/apiexport-scheduling.kcp.dev.yaml
  config/root-phase0/apiexport-shards.tenancy.kcp.dev.yaml
  config/root-phase0/apiexport-tenancy.kcp.dev.yaml
  config/root-phase0/apiexport-workload.kcp.dev.yaml
  config/root-phase0/apiresourceschema-apibindings.apis.kcp.dev.yaml
  config/root-phase0/apiresourceschema-apiexports.apis.kcp.dev.yaml
  config/root-phase0/apiresourceschema-apiresourceimports.apiresource.kcp.dev.yaml
  config/root-phase0/apiresourceschema-apiresourceschemas.apis.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspaces.tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspaceshards.tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspacetypes.tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-locations.scheduling.kcp.dev.yaml
  config/root-phase0/apiresourceschema-negotiatedapiresources.apiresource.kcp.dev.yaml
  config/root-phase0/apiresourceschema-placements.scheduling.kcp.dev.yaml
  config/root-phase0/apiresourceschema-workloadclusters.workload.kcp.dev.yaml
  config/root-phase0/apiresourceschema-workspaces.tenancy.kcp.dev.yaml
  go.mod
  go.sum
  hack/update-codegen.sh
Labels: approved, lgtm

#1436 e2e/virtual/apiexport: fix authz flake
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm

#1437 e2e/framework: fix root dir for in-process server
  Makefile
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/main.go
  cmd/sharded-test-server/shard.go
  cmd/test-server/kcp/shard.go
  test/e2e/framework/kcp.go
Labels: approved

#1439 syncer: avoid fatal WorkloadCluster get
  pkg/syncer/syncer.go
Labels: approved, lgtm

#1443 syncer/apiimporter: log what it does
  pkg/syncer/apiimporter.go
Labels: approved, lgtm

#1438 Hunting APIBinding flake
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
Labels: approved, lgtm

#1444 config/universal: mark default ns create-only
  config/root/namespace-default.yaml
  config/universal/default-namespace.yaml
Labels: approved, lgtm

#1442 e2e/watchcache: fix missing identity logic
  cmd/virtual-workspaces/command/cmd.go
  pkg/server/server.go
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: approved, lgtm

#1435 Add kcp start options for embedded etcd server Prometheus scrape URLs
  pkg/etcd/etcd.go
  pkg/server/options/embeddedetcd.go
  pkg/server/options/flags.go
  pkg/server/server.go
Labels: approved, lgtm, ok-to-test

#1423 apis: add omitempty to optional fields
  config/root-phase0/apiexport-apiresource.kcp.dev.yaml
  config/root-phase0/apiexport-scheduling.kcp.dev.yaml
  config/root-phase0/apiexport-shards.tenancy.kcp.dev.yaml
  config/root-phase0/apiexport-tenancy.kcp.dev.yaml
  config/root-phase0/apiexport-workload.kcp.dev.yaml
  pkg/admission/clusterworkspacetypeexists/admission_test.go
  pkg/apis/apis/v1alpha1/types.go
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/apis/tenancy/v1beta1/types.go
  pkg/openapi/zz_generated.openapi.go
Labels: approved, lgtm

#1430 Add kcp start option --embedded-etcd-quota-backend-bytes
  pkg/etcd/etcd.go
  pkg/server/options/embeddedetcd.go
  pkg/server/options/flags.go
  pkg/server/server.go
Labels: approved, lgtm, ok-to-test

#1451 README: update docs for starting
  README.md
Labels: approved, lgtm

#1432 Add --version flag for kubectl-kcp plugin
  cmd/kubectl-kcp/main.go
Labels: approved, lgtm, ok-to-test

#1395 server/apiextensions: disable non-system-CRD non-identity wildcard requests
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/reconciler/apis/apiexport/apiexport_reconcile.go
  pkg/reconciler/scheduling/location/location_controller.go
  pkg/reconciler/scheduling/location/location_reconcile.go
  pkg/reconciler/scheduling/location/location_reconcile_test.go
  pkg/reconciler/scheduling/placement/placement_controller.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/clusterworkspace_deletion_controller.go
  pkg/reconciler/workload/apiexport/apiexport_controller.go
  pkg/reconciler/workload/apiexportcreate/apiexportcreate_controller.go
  pkg/reconciler/workload/namespace/namespace_controller.go
  pkg/reconciler/workload/namespace/namespace_reconcile_scheduling.go
  pkg/reconciler/workload/namespace/namespace_reconcile_scheduling_test.go
  pkg/server/apiextensions.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
Labels: approved, lgtm

#1429 tenancy: fully qualify type references
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml-patch
  config/root-phase0/apiexport-tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspacetypes.tenancy.kcp.dev.yaml
  config/root/clusterworkspacetype-organization.yaml
  config/root/clusterworkspacetype-team.yaml
  config/root/clusterworkspacetype-universal.yaml
  pkg/admission/clusterworkspacetype/admission.go
  pkg/admission/clusterworkspacetype/admission_test.go
  pkg/admission/clusterworkspacetypeexists/admission.go
  pkg/admission/clusterworkspacetypeexists/admission_test.go
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller_reconcile.go
  pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller_reconcile_test.go
  test/e2e/framework/util.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm

#1464 config/root: fix CWTs
  config/root/clusterworkspacetype-home.yaml
  config/root/clusterworkspacetype-homebucket.yaml
  config/root/clusterworkspacetype-homeroot.yaml
Labels: approved, lgtm

#1466 Add e2e-sharded docs only job
  .github/workflows/ci-docs-only.yaml
Labels: approved, lgtm

#1463 Add flake hunting docs
  CONTRIBUTING.md
Labels: approved, lgtm

#1460 docs: link to virtual workspaces demo
  docs/virtual-workspaces.md
Labels: approved, lgtm, ok-to-test

#1411 authorizer/apibinding: prefix users and groups in MaximalPermissionPolicy
  cmd/apigen/main.go
  config/crds/apis.kcp.dev_apiexports.yaml
  config/root-phase0/apiexport-apiresource.kcp.dev.yaml
  config/root-phase0/apiexport-scheduling.kcp.dev.yaml
  config/root-phase0/apiexport-shards.tenancy.kcp.dev.yaml
  config/root-phase0/apiexport-tenancy.kcp.dev.yaml
  config/root/clusterrole-apiresource-apiexport-bind.yaml
  config/root/clusterrole-apiresource-maximal-permission-policy.yaml
  config/root/clusterrole-clusterworkspacetype-use.yaml
  config/root/clusterrole-scheduling-apiexport-bind.yaml
  config/root/clusterrole-scheduling-maximal-permission-policy.yaml
  config/root/clusterrole-tenancy-apiexport-bind.yaml
  config/root/clusterrole-tenancy-maximal-permission-policy.yaml
  config/root/clusterrole-workload-apiexport-bind.yaml
  config/root/clusterrole-workload-maximal-permission-policy.yaml
  config/root/clusterrolebinding-apiresource-apiexport-bind.yaml
  config/root/clusterrolebinding-apiresource-maximal-permission-policy.yaml
  config/root/clusterrolebinding-clusterworkspacetype-use.yaml
  config/root/clusterrolebinding-scheduling-apiexport-bind.yaml
  config/root/clusterrolebinding-scheduling-maximal-permission-policy.yaml
  config/root/clusterrolebinding-tenancy-apiexport-bind.yaml
  config/root/clusterrolebinding-tenancy-maximal-permission-policy.yaml
  config/root/clusterrolebinding-workload-apiexport-bind.yaml
  config/root/clusterrolebinding-workload-maximal-permission-policy.yaml
  hack/update-codegen.sh
  pkg/apis/apis/v1alpha1/types.go
  pkg/apis/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/authorization/apibinding_authorizer.go
  pkg/authorization/system_crd_authorizer.go
  pkg/authorization/workspace_content_authorizer.go
  pkg/openapi/zz_generated.openapi.go
  pkg/virtual/workspaces/registry/rest.go
  pkg/virtual/workspaces/registry/rest_test.go
  test/e2e/apibinding/apibinding_authorizer_test.go
Labels: approved, lgtm

#1392 CLI: Support home workspace through `~`
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/cliplugins/workspace/plugin/kubeconfig_test.go
Labels: approved, lgtm

#1459 e2e: add user-agents to hand-crafted rest configs
  test/e2e/apibinding/apibinding_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#1478 Add shard-base-url flag to default clusterworkspaceshards
  pkg/admission/clusterworkspaceshard/admission.go
  pkg/admission/initializers/initializer.go
  pkg/admission/initializers/interfaces.go
  pkg/server/options/flags.go
  pkg/server/options/options.go
  pkg/server/server.go
Labels: approved, lgtm

#1475 cli/workload/sync: improve usability
  config/crds/workload.kcp.dev_synctargets.yaml
  config/crds/workload.kcp.dev_synctargets.yaml-patch
  config/root-phase0/apiexport-workload.kcp.dev.yaml
  config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
  docs/syncer.md
  pkg/cliplugins/workload/cmd/cmd.go
  pkg/cliplugins/workload/plugin/sync.go
  pkg/cliplugins/workload/plugin/sync_test.go
  pkg/cliplugins/workload/plugin/syncer.yaml
  pkg/syncer/syncer.go
  test/e2e/framework/fixture.go
  test/e2e/syncer/syncer_test.go
Labels: approved, lgtm

#1420 reconciler/apis/apibinding: make phase=Bound permanent
  cmd/test-server/main.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
Labels: approved, lgtm

#1472 Update placement doc
  docs/locations-and-scheduling.md
Labels: approved, lgtm

#1485 API: Rename and make ClusterResourceStateLabelPrefix public
  cmd/syncer/options/options.go
  docs/locations-and-scheduling.md
  pkg/apis/workload/v1alpha1/helpers.go
  pkg/apis/workload/v1alpha1/types.go
  pkg/reconciler/workload/deploymentsplitter/deploymentsplitter_reconcile.go
  pkg/reconciler/workload/ingresssplitter/ingresssplitter_reconcile.go
  pkg/reconciler/workload/namespace/namespace_reconcile_scheduling.go
  pkg/reconciler/workload/namespace/namespace_reconcile_scheduling_test.go
  pkg/reconciler/workload/namespace/namespace_reconcile_status_test.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/reconciler/workload/resource/resource_reconcile.go
  pkg/reconciler/workload/resource/resource_reconcile_test.go
  pkg/syncer/shared/finalizer.go
  pkg/syncer/shared/helpers.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_process.go
  pkg/syncer/status/status_process_test.go
  pkg/syncer/syncer.go
  pkg/virtual/syncer/builder/build.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/ingress/controller_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
Labels: approved, lgtm

#1486 Syncer: add support for qps and burst
  cmd/syncer/cmd/syncer.go
  cmd/syncer/options/options.go
  pkg/cliplugins/workload/cmd/cmd.go
  pkg/cliplugins/workload/plugin/sync.go
  pkg/cliplugins/workload/plugin/sync_test.go
  pkg/cliplugins/workload/plugin/syncer.yaml
  test/e2e/framework/fixture.go
Labels: approved, lgtm

#1479 adds a shard-name flag for assigning a name to a shard instance
  pkg/server/options/flags.go
  pkg/server/options/options.go
  pkg/server/server.go
Labels: approved, lgtm

#1487 *: remove the vestigial attempt at cross-shard resourceversions
  pkg/server/options/flags.go
  pkg/server/options/options.go
  pkg/server/server.go
  pkg/sharding/apiserver/delegating_storage.go
  pkg/sharding/apiserver/handler.go
  pkg/sharding/apiserver/request.go
  pkg/sharding/apiserver/sharded_storage.go
  pkg/sharding/apiserver/state.go
  pkg/sharding/apiserver/state_test.go
  pkg/sharding/apiserver/storage.go
  pkg/sharding/clients.go
  pkg/sharding/handler.go
Labels: approved, lgtm

#1491 config/root: avoid race of bootstrapping with controller
  config/root/clusterrole-clusterworkspace-home-create.yaml
  config/root/clusterrole-clusterworkspace-home-get.yaml
  config/root/clusterrole-clusterworkspace-users-access.yaml
  config/root/clusterrolebinding-clusterworkspace-home-create.yaml
  config/root/clusterrolebinding-clusterworkspace-home-get.yaml
  config/root/clusterrolebinding-clusterworkspace-users-access.yaml
  config/root/clusterworkspace-homeroot-users.yaml
Labels: approved, lgtm

#1492 admission/clusterworkspace: move owner annotation code here
  pkg/admission/clusterworkspace/admission.go
  pkg/admission/clusterworkspace/admission_test.go
  pkg/admission/clusterworkspacetypeexists/admission.go
  pkg/admission/clusterworkspacetypeexists/admission_test.go
Labels: approved, lgtm

#1480 server/home: check owner on 'GET ~' and fix flake
  pkg/server/home_workspaces.go
  pkg/server/home_workspaces_test.go
  test/e2e/homeworkspaces/home_workspaces_test.go
Labels: approved, lgtm

#1494 Wipe owner info as soon as possible
  pkg/apis/tenancy/projection/workspaces.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata_test.go
Labels: approved, lgtm

#1484 sharded-test-server: allows for specifying the number of shards to create
  cmd/sharded-test-server/main.go
  cmd/sharded-test-server/shard.go
Labels: approved, lgtm

#1481 apis/workload: move workload.kcp.dev/skip-default-object-creation here from apis.kcp.dev/v1alpha1
  pkg/admission/reservedmetadata/admission.go
  pkg/apis/apis/v1alpha1/types.go
  pkg/apis/workload/v1alpha1/types.go
  pkg/reconciler/workload/apiexportcreate/apiexportcreate_controller.go
  pkg/reconciler/workload/defaultplacement/defaultplacement_controller.go
Labels: approved, lgtm

#1489 e2e: require two failed pings to fail the test
  test/e2e/framework/kcp.go
Labels: approved, lgtm

#1244 Adding permissions claims API for granting more resource for VirtualWorkspace
  config/crds/apis.kcp.dev_apibindings.yaml
  config/crds/apis.kcp.dev_apiexports.yaml
  config/crds/apis.kcp.dev_apiexports.yaml-patch
  pkg/admission/permissionclaims/mutating_permission_claims.go
  pkg/admission/plugins.go
  pkg/admission/reservedmetadata/admission.go
  pkg/apis/apis/v1alpha1/permissionclaims/labels.go
  pkg/apis/apis/v1alpha1/types.go
  pkg/apis/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/indexers/indexers.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_permissionclaim.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/server/controllers.go
  pkg/server/server.go
  pkg/virtual/apiexport/builder/build.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
  test/e2e/apibinding/apibinding_authorizer_test.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm

#1503 admission/clusteworkspacetypeexists: in-place validation, fixes
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml-patch
  config/root-phase0/apiexport-tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspacetypes.tenancy.kcp.dev.yaml
  config/root/clusterworkspacetype-home.yaml
  config/root/clusterworkspacetype-homebucket.yaml
  config/root/clusterworkspacetype-homeroot.yaml
  config/root/clusterworkspacetype-organization.yaml
  config/root/clusterworkspacetype-team.yaml
  config/root/clusterworkspacetype-universal.yaml
  pkg/admission/clusterworkspacetype/admission.go
  pkg/admission/clusterworkspacetype/admission_test.go
  pkg/admission/clusterworkspacetypeexists/admission.go
  pkg/admission/clusterworkspacetypeexists/admission_test.go
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller_reconcile.go
  pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller_reconcile_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
  test/e2e/workspacetype/controller_test.go
Labels: milestone-blocker, approved, lgtm

#1511 Waiting for the binding to have observed the permission claims in test
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm

#1513 pkg/apis: fix go mod
  go.mod
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: approved, lgtm

#1498 use a more minimal k8s fork
  go.mod
  go.sum
  hack/bump-k8s.sh
  pkg/virtual/framework/dynamic/apiserver/serving_info.go
  pkg/virtual/framework/forwardingregistry/rest_test.go
Labels: approved, lgtm

#1508 Add stub livez handler in the proxy
  pkg/proxy/mapping.go
Labels: approved, lgtm

#1519 cli: deprecate list command
  pkg/cliplugins/workspace/cmd/cmd.go
Labels: approved, lgtm

#1441 test-servers: enable audit logs
  cmd/sharded-test-server/shard.go
  cmd/test-server/kcp/audit-policy.yaml
  cmd/test-server/kcp/shard.go
  cmd/test-server/main.go
  pkg/server/controllers.go
Labels: approved, lgtm

#1525 Fix a typo s/matchins/matching
  docs/locations-and-scheduling.md
Labels: approved, lgtm

#1515 Don't unschedule a resource if blocked by a cluster or syncer finalizer
  pkg/reconciler/workload/resource/resource_reconcile.go
  pkg/reconciler/workload/resource/resource_reconcile_test.go
Labels: kind/bug, milestone-blocker, approved, lgtm

#1522 Remove non-existing scheduling-disabled label from ReservedMetadata allow list
  pkg/admission/reservedmetadata/admission.go
Labels: approved, lgtm

#1521 cli: switch meaning of 'kubectl ws' to go to home workspace, add 'kubectl ws .'
  pkg/cliplugins/workspace/cmd/cmd.go
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/cliplugins/workspace/plugin/kubeconfig_test.go
Labels: milestone-blocker, approved, lgtm

#1527 cli/workload/sync: MaxSyncTargetNameLength decreased by SyncerIDPrefix length
  pkg/cliplugins/workload/plugin/sync.go
Labels: approved, lgtm

#1523 server/home: avoid returning an uninitialized ~ workspace
  pkg/server/home_workspaces.go
  pkg/server/home_workspaces_test.go
  pkg/virtual/workspaces/registry/rest.go
  test/e2e/homeworkspaces/home_workspaces_test.go
Labels: area/workspaces, priority/urgent, approved, lgtm, kind/flake

#1448 test/e2e: make tests shard aware
  Makefile
  cmd/kcp-front-proxy/options/authentication.go
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/main.go
  config/root/clusterrole-kcp-admin-maximal-permission-policy.yaml
  config/root/clusterrolebinding-kcp-admin-maximal-permission-policy.yaml
  pkg/authorization/bootstrap/policy.go
  pkg/authorization/toplevel_org_authorizer.go
  pkg/authorization/workspace_content_authorizer.go
  pkg/server/options/authentication.go
  pkg/server/options/options.go
  pkg/server/server.go
  pkg/virtual/framework/wrappers/rbac/merging.go
  test/e2e/apibinding/apibinding_authorizer_test.go
  test/e2e/apibinding/apibinding_deletion_test.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
  test/e2e/apibinding/apibinding_protected_test.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/apibinding/apibinding_webhook_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/authorizer/rootcacertconfigmap_test.go
  test/e2e/authorizer/serviceaccounts_test.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/conformance/webhook_test.go
  test/e2e/customresourcedefinition/customresourcedefinition_test.go
  test/e2e/framework/config.go
  test/e2e/framework/fixture.go
  test/e2e/framework/kcp.go
  test/e2e/framework/util.go
  test/e2e/homeworkspaces/home_workspaces_test.go
  test/e2e/reconciler/apiexport/apiexport_controller_test.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/clusterworkspace/controller_test.go
  test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
  test/e2e/reconciler/clusterworkspaceshard/controller_test.go
  test/e2e/reconciler/ingress/controller_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
  test/e2e/watchcache/watchcache_enabled_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm

#1533 cli: require absolute type with --ignore-existing
  pkg/cliplugins/workspace/cmd/cmd.go
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/cliplugins/workspace/plugin/kubeconfig_test.go
Labels: approved

#1540 Fix typos in APIExport bootstrapped `ClusterRoleBinding`s
  config/root/clusterrolebinding-apiresource-apiexport-bind.yaml
  config/root/clusterrolebinding-scheduling-apiexport-bind.yaml
  config/root/clusterrolebinding-tenancy-apiexport-bind.yaml
  config/root/clusterrolebinding-workload-apiexport-bind.yaml
Labels: approved, lgtm

#1537 [release-0.6] server/home: create home workspace with final URL on '~' access
  pkg/server/home_workspaces.go
  pkg/server/home_workspaces_test.go
  test/e2e/homeworkspaces/home_workspaces_test.go
Labels: approved, lgtm

#1542 server: add --shard-external-url
  pkg/admission/clusterworkspaceshard/admission.go
  pkg/admission/clusterworkspaceshard/admission_test.go
  pkg/admission/initializers/initializer.go
  pkg/admission/initializers/interfaces.go
  pkg/server/options/flags.go
  pkg/server/options/options.go
  pkg/server/server.go
Labels: approved, lgtm

#1550 ddsif: fix lost event handlers
  pkg/informer/informer.go
Labels: approved, lgtm

#1524 Add shortName ws for workspace
  config/crds/tenancy.kcp.dev_workspaces.yaml
  config/root-phase0/apiexport-tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-workspaces.tenancy.kcp.dev.yaml
  pkg/apis/tenancy/v1beta1/types.go
Labels: approved, lgtm, ok-to-test

#1554 cli: take URL from Workspace also in absolute references
  pkg/cliplugins/workspace/plugin/kubeconfig.go
Labels: approved, lgtm

#1473 ddsif: replace discovery polling
  pkg/informer/informer.go
  pkg/informer/informer_test.go
  pkg/server/options/flags.go
  pkg/server/options/options.go
  pkg/server/server.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/framework/fixture.go
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: approved, lgtm

#1552 sharded-test-server: set shard external URL to front-proxy
  cmd/sharded-test-server/shard.go
Labels: approved, lgtm

#1504 Part 2: Scoping controllers in pkg/server
  pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_reconcile.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile.go
  pkg/reconciler/tenancy/clusterworkspaceshard/clusterworkspaceshard_controller.go
  pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller.go
  pkg/server/controllers.go
Labels: approved, lgtm

#1558 Part 3: Make APIResource controller client calls scoped
  cmd/cluster-controller/main.go
  pkg/reconciler/apis/apiresource/controller.go
  pkg/reconciler/apis/apiresource/negotiation.go
  pkg/server/controllers.go
Labels: approved, lgtm

#1549 server/home: improve log output
  pkg/server/home_workspaces.go
Labels: approved, lgtm

#1493 server/home: check owner properly
  Makefile
  pkg/admission/clusterworkspace/admission.go
  pkg/admission/clusterworkspace/admission_test.go
  pkg/admission/reservedmetadata/admission.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata_test.go
  pkg/server/home_workspaces.go
  pkg/server/home_workspaces_test.go
  pkg/softimpersonation/softimpersonation.go
Labels: approved, lgtm

#1569 Part 4: Wrap client calls in API Binding and Heartbeat controller
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_permissionclaim.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go
  pkg/reconciler/workload/basecontroller/controller.go
  pkg/reconciler/workload/heartbeat/heartbeat_controller.go
  pkg/server/controllers.go
Labels: approved, lgtm

#1576 e2e/clusterworkspacedeletion: deflake
  test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
Labels: approved, lgtm

#1566 syncer/namespace-locator: Rename path to workspace
  pkg/syncer/shared/namespace.go
  pkg/syncer/shared/namespace_test.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
Labels: approved, lgtm

#1529 Adding CEL Validation for Permission Claim
  Makefile
  config/crds/apis.kcp.dev_apibindings.yaml
  config/crds/apis.kcp.dev_apibindings.yaml-patch
  config/crds/apis.kcp.dev_apiexports.yaml
  config/crds/apis.kcp.dev_apiexports.yaml-patch
  pkg/apis/apis/v1alpha1/api_cel_test.go
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/tenancy/initialization/utils_test.go
  pkg/features/kcp_features.go
Labels: approved, lgtm

#1543 e2e: reduce client-side throttling
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/framework/kcp.go
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: approved, lgtm

#1575 kcp server: introduce root-shard-kubeconfig-file flag
  pkg/server/options/flags.go
  pkg/server/options/options.go
Labels: approved, lgtm

#1574 Syncer: Refactors KCPClusterName to SyncTargetWorkspace.
  cmd/syncer/cmd/syncer.go
  cmd/syncer/options/options.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/status/status_controller.go
  pkg/syncer/syncer.go
  test/e2e/framework/fixture.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/ingress/controller_test.go
Labels: approved, lgtm

#1586 docs: tweaks to the Location concept description
  docs/locations-and-scheduling.md
Labels: approved, lgtm, needs-ok-to-test

#1589 remove unused apiResourceSchemaIndexer from the apibinding controller
  pkg/reconciler/apis/apibinding/apibinding_controller.go
Labels: approved, lgtm

#1584 Add workspaces overview to README
  README.md
Labels: approved, lgtm, ok-to-test

#1590 Don't add /clusters/ prefix to /services/ requests
  pkg/server/handler.go
Labels: approved, lgtm

#1570 e2e/clusterworkspacedeletion: use correct root shard system:master client for deletion checks
  test/e2e/apibinding/apibinding_authorizer_test.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/framework/kcp.go
  test/e2e/homeworkspaces/home_workspaces_test.go
  test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: approved, lgtm

#1588 e2e: use a better helper for waiting for readiness
  test/e2e/framework/fixture.go
Labels: approved, lgtm

#1578 Part 5: Wrap controllers in scheduling/tenancy pkgs
  pkg/reconciler/scheduling/location/location_controller.go
  pkg/reconciler/scheduling/location/location_reconcile.go
  pkg/reconciler/scheduling/placement/placement_controller.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/clusterworkspace_deletion_controller.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor_test.go
  pkg/server/controllers.go
Labels: approved, lgtm

#1595 Part 6: Scope workload controllers
  cmd/ingress-controller/main.go
  pkg/reconciler/workload/apiexport/workload_apiexport_controller.go
  pkg/reconciler/workload/apiexport/workload_apiexport_reconcile.go
  pkg/reconciler/workload/apiexportcreate/apiexportcreate_controller.go
  pkg/reconciler/workload/defaultplacement/defaultplacement_controller.go
  pkg/reconciler/workload/ingresssplitter/ingresssplitter_controller.go
  pkg/reconciler/workload/ingresssplitter/ingresssplitter_reconcile.go
  pkg/reconciler/workload/namespace/namespace_controller.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/reconciler/workload/resource/resource_reconcile.go
  pkg/reconciler/workload/virtualworkspaceurls/virtualworkspaceurls_controller.go
  pkg/server/controllers.go
Labels: approved, lgtm

#1594 Extend README with introduction to workspaces
  README.md
Labels: approved, lgtm, ok-to-test

#1587 bootstrap the root workspace only on the root shard
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/server/server.go
Labels: approved, lgtm

#1597 run the clusterworkspaceshard controller only on the root shard
  pkg/server/controllers.go
Labels: approved, lgtm

#1596 enable ExperimentalWatchProgressNotifyInterval for etcd
  pkg/etcd/etcd.go
  pkg/server/server.go
Labels: approved, lgtm

#1585 clusterworkspace scheduling: default to assigning to the root shard
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_scheduling.go
Labels: approved, lgtm

#1606 Makefile improvements
  Makefile
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/main.go
  cmd/sharded-test-server/shard.go
Labels: approved, lgtm

#1603 apis/apis: split out CEL test helper into pkg/apis/test
  pkg/apis/apis/v1alpha1/api_cel_test.go
  pkg/apis/apis/v1alpha1/types.go
  pkg/apis/apis/v1alpha1/types_apibinding.go
  pkg/apis/apis/v1alpha1/types_apibinding_test.go
  pkg/apis/apis/v1alpha1/types_apiexport.go
  pkg/apis/apis/v1alpha1/types_apiexport_test.go
  pkg/apis/apis/v1alpha1/types_apiresourceschema.go
  pkg/apis/test/cel.go
Labels: approved, lgtm

#1607 clusterworkspacetypes: simplify system types
  config/home/bootstrap.go
  config/organization/bootstrap.go
  config/organization/clusterworkspacetype-use-clusterrole.yaml
  config/organization/clusterworkspacetype-use-clusterrolebinding.yaml
  config/root/clusterworkspacetype-home.yaml
  config/root/clusterworkspacetype-organization.yaml
  config/root/clusterworkspacetype-team.yaml
  config/team/bootstrap.go
  config/team/clusterworkspacetype-use-clusterrole.yaml
  config/team/clusterworkspacetype-use-clusterrolebinding.yaml
  pkg/reconciler/tenancy/bootstrap/bootstrap_reconcile.go
  pkg/server/controllers.go
Labels: approved, lgtm

#1613 cli/sync: create service account secret in advance to trigger token creation
  pkg/cliplugins/workload/plugin/sync_test.go
  pkg/cliplugins/workload/plugin/syncer.yaml
  test/e2e/framework/fixture.go
Labels: approved, lgtm

#1608 embeddedetcd: restructure with options/config/server pattern
  pkg/embeddedetcd/config.go
  pkg/embeddedetcd/options/embedded.go
  pkg/embeddedetcd/server.go
  pkg/server/options/options.go
  pkg/server/server.go
Labels: approved, lgtm

#1612 make: explicitly list build deps
  Makefile
Labels: approved, lgtm

#1598 apibinding controller with root shard informers
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/server/controllers.go
  pkg/server/server.go
Labels: approved, lgtm

#1616 0.6: cli/sync: create service account secret in advance to trigger token creation
  pkg/cliplugins/workload/plugin/sync_test.go
  pkg/cliplugins/workload/plugin/syncer.yaml
Labels: approved, lgtm

#1619 server/embeddedetcd: fix npe
  pkg/server/options/options.go
Labels: approved, lgtm

#1609 server: restructure with options/config/server pattern
  Makefile
  cmd/kcp/kcp.go
  go.mod
  go.sum
  pkg/admission/apibinding/apibinding_admission.go
  pkg/admission/clusterworkspacetypeexists/admission.go
  pkg/admission/initializers/initializer.go
  pkg/admission/initializers/interfaces.go
  pkg/embeddedetcd/config.go
  pkg/embeddedetcd/options/embedded.go
  pkg/embeddedetcd/server.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile.go
  pkg/reconciler/tenancy/clusterworkspaceshard/clusterworkspaceshard_controller.go
  pkg/server/controllers.go
  pkg/server/handler.go
  pkg/server/options/authentication.go
  pkg/server/options/options.go
  pkg/server/server.go
  pkg/server/virtual.go
  test/e2e/framework/kcp.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Labels: approved, lgtm

#1561 Documentation: Add Home, Homebucket, and Homeroot workspace info
  docs/workspaces.md
Labels: documentation, approved, lgtm, kind/documentation

#1571 add exports to synctarget API for location workspace
  config/crds/scheduling.kcp.dev_placements.yaml
  config/crds/workload.kcp.dev_synctargets.yaml
  config/root-phase0/apiexport-scheduling.kcp.dev.yaml
  config/root-phase0/apiexport-workload.kcp.dev.yaml
  config/root-phase0/apiresourceschema-placements.scheduling.kcp.dev.yaml
  config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
  pkg/apis/scheduling/v1alpha1/types_placement.go
  pkg/apis/workload/v1alpha1/synctarget_types.go
  pkg/apis/workload/v1alpha1/zz_generated.deepcopy.go
  pkg/openapi/zz_generated.openapi.go
  pkg/virtual/framework/internalapis/fixtures/synctargets.yaml
Labels: approved, lgtm

#1614 logging: move clusterworkspaceshard reconciler to structured logging
  pkg/logging/constants.go
  pkg/reconciler/tenancy/clusterworkspaceshard/clusterworkspaceshard_controller.go
Labels: approved, lgtm

#1601 Add owners files and notes on review/approver role to CONTRIBUTING.md
  CONTRIBUTING.md
  OWNERS_ALIASES
  cmd/OWNERS
  config/OWNERS
  config/crds/OWNERS
  contrib/OWNERS
  docs/OWNERS
  hack/OWNERS
  manifest/OWNERS
  pkg/admission/OWNERS
  pkg/admission/crdnooverlappinggvr/OWNERS
  pkg/admission/mutatingwebhook/OWNERS
  pkg/admission/namespacelifecycle/OWNERS
  pkg/admission/permissionclaims/OWNERS
  pkg/admission/reservedcrdannotations/OWNERS
  pkg/admission/validatingwebhook/OWNERS
  pkg/admission/webhook/OWNERS
  pkg/apis/OWNERS
  pkg/apis/scheduling/OWNERS
  pkg/apis/tenancy/OWNERS
  pkg/authorization/OWNERS
  pkg/cliplugins/OWNERS
  pkg/cmd/OWNERS
  pkg/crdpuller/OWNERS
  pkg/features/OWNERS
  pkg/indexers/OWNERS
  pkg/localenvoy/OWNERS
  pkg/proxy/OWNERS
  pkg/schemacompat/OWNERS
  pkg/syncer/OWNERS
  pkg/virtual/OWNERS
  test/OWNERS
Labels: approved, lgtm

#1633 home workspaces: handle slow bootstrapping
  pkg/server/home_workspaces.go
Labels: approved, lgtm, kind/flake

#1638 Fix print column on location labels
  config/crds/scheduling.kcp.dev_locations.yaml
  config/root-phase0/apiexport-scheduling.kcp.dev.yaml
  config/root-phase0/apiresourceschema-locations.scheduling.kcp.dev.yaml
  pkg/apis/scheduling/v1alpha1/types_location.go
Labels: approved, lgtm, kind/api-change

#1639 webhook: fix npe
  pkg/admission/webhook/generic_webhook.go
Labels: approved, lgtm, kind/api-change

#1618 Refactor ns scheduler for location workspace
  pkg/apis/workload/v1alpha1/types.go
  pkg/reconciler/workload/namespace/namespace_controller.go
  pkg/reconciler/workload/namespace/namespace_reconcile.go
  pkg/reconciler/workload/namespace/namespace_reconcile_scheduling.go
  pkg/reconciler/workload/namespace/namespace_reconcile_scheduling_test.go
  pkg/reconciler/workload/placement/placement_controller.go
  pkg/reconciler/workload/placement/placement_indexes.go
  pkg/reconciler/workload/placement/placement_reconcile.go
  pkg/reconciler/workload/placement/placement_reconcile_scheduling.go
  pkg/reconciler/workload/placement/placement_reconcile_scheduling_test.go
  pkg/server/controllers.go
  pkg/server/server.go
Labels: approved, lgtm, kind/api-change

#1628 Enable avoiding using podman
  contrib/demos-unmaintained/demo/clusters/kind/createKindClusters.sh
Labels: approved, lgtm

#1637 move Config to separate file
  pkg/server/config.go
  pkg/server/server.go
Labels: approved, lgtm, ok-to-test

#1236 Add initial per-workspace quota support
  config/crds/bootstrap.go
  go.mod
  go.sum
  hack/bump-k8s.sh
  pkg/admission/initializers/initializer.go
  pkg/admission/initializers/interfaces.go
  pkg/admission/kubequota/kubequota_admission.go
  pkg/admission/kubequota/kubequota_clusterworkspace_monitor.go
  pkg/admission/plugins.go
  pkg/informer/informer.go
  pkg/informer/informer_test.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_permissionclaim.go
  pkg/reconciler/kubequota/delegating_event_handler.go
  pkg/reconciler/kubequota/kubequota_controller.go
  pkg/reconciler/kubequota/scoped_generic_shared_informer_factory.go
  pkg/reconciler/kubequota/single_cluster_resource_quota_informer.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/server/config.go
  pkg/server/controllers.go
  pkg/server/server.go
  test/e2e/fixtures/kube/bootstrap.go
  test/e2e/framework/fixture.go
  test/e2e/quota/quota_test.go
Labels: approved, lgtm, kind/api-change

#1640 Part 8: Wrap clients in test/e2e/apibinding
  test/e2e/apibinding/apibinding_authorizer_test.go
  test/e2e/apibinding/apibinding_deletion_test.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
  test/e2e/apibinding/apibinding_protected_test.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/apibinding/apibinding_webhook_test.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/fixtures/apifixtures/apibinding.go
  test/e2e/fixtures/apifixtures/sheriffs.go
  test/e2e/framework/kcp.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: approved, lgtm

#1642 e2e: reduce global, trivial Sheriff fixture
  test/e2e/fixtures/apifixtures/sheriffs.go
Labels: lgtm

#1641 server: keep retrying bootstrapping
  pkg/server/server.go
Labels: approved, lgtm

#1645 remove deprecated command from use description
  pkg/cliplugins/workspace/cmd/cmd.go
Labels: approved, lgtm, ok-to-test

#1643 virtual: give VWs an order in order to control precedence
  pkg/virtual/apiexport/builder/build.go
  pkg/virtual/apiexport/options/options.go
  pkg/virtual/framework/authorization/authorizer.go
  pkg/virtual/framework/rootapiserver/root_apiserver.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/initializingworkspaces/options/options.go
  pkg/virtual/options/authorization.go
  pkg/virtual/options/options.go
  pkg/virtual/syncer/options/options.go
  pkg/virtual/workspaces/options/options.go
Labels: approved, lgtm

#1651 Update minimum Go version in CONTRIBUTING.md doc to 1.18
  .gitignore
  CONTRIBUTING.md
Labels: approved, lgtm, ok-to-test
