Repository kcp-dev/kcp, pull requests merged in 2022-12, with the labels that each got.

#2382 🐛 give the front proxy a distinct config for direct(internal) shard communication.
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/main.go
  pkg/proxy/config.go
  pkg/proxy/options/options.go
  pkg/proxy/server.go
Labels: approved, lgtm

#2329 ✨ Only schedule to synctarget with compatible APIs
  config/rootcompute/kube-1.24/apiexport-kubernetes.k8s.io.yaml
  pkg/apis/apis/v1alpha1/types_apiexport.go
  pkg/apis/scheduling/v1alpha1/types_placement.go
  pkg/apis/workload/v1alpha1/types.go
  pkg/cliplugins/bind/plugin/bind_compute.go
  pkg/cliplugins/workload/plugin/sync.go
  pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller.go
  pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller_test.go
  pkg/reconciler/workload/apiexportcreate/apiexportcreate_controller.go
  pkg/reconciler/workload/placement/placement_controller.go
  pkg/reconciler/workload/placement/placement_reconcile.go
  pkg/reconciler/workload/placement/placement_reconcile_scheduling.go
  pkg/reconciler/workload/placement/placement_reconcile_scheduling_test.go
  pkg/server/controllers.go
  pkg/server/server.go
  pkg/syncer/apiimporter.go
  test/e2e/framework/kcp.go
  test/e2e/reconciler/scheduling/api_compatibility_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
Labels: area/transparent-multi-cluster, approved, lgtm, kind/api-change

#2306 🐛 Fix double identities for wildcard requests from APIExport virtual workspace
  pkg/server/bootstrap/identity.go
  pkg/server/server.go
  pkg/virtual/apiexport/builder/forwarding.go
  pkg/virtual/framework/forwardingregistry/rest.go
  pkg/virtual/framework/forwardingregistry/rest_test.go
  pkg/virtual/framework/forwardingregistry/wrappers.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/initializingworkspaces/builder/forwarding.go
  pkg/virtual/syncer/upsyncer/storage_wrapper.go
  test/e2e/apibinding/apibinding_protected_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Labels: approved, lgtm

#2447 🐛 cliplugins/bind: fix incorrect error message
  pkg/cliplugins/bind/plugin/bind_compute.go
Labels: approved, lgtm

#2445 🌱 Contextual logging fixes
  hack/logcheck.out
  pkg/server/controllers.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
Labels: approved, lgtm

#2442 🌱 pkg/authorization: switch to audit logger, and anonymizer, improve audit log messages
  pkg/authorization/anonymizer.go
  pkg/authorization/audit_logger.go
  pkg/authorization/bootstrap_policy_authorizer.go
  pkg/authorization/decision.go
  pkg/authorization/decorator.go
  pkg/authorization/local_authorizer.go
  pkg/authorization/maximal_permission_policy_authorizer.go
  pkg/authorization/system_crd_authorizer.go
  pkg/authorization/toplevel_org_authorizer.go
  pkg/authorization/workspace_content_authorizer.go
  pkg/authorization/workspace_content_authorizer_test.go
  pkg/server/options/authorization.go
  pkg/virtual/apiexport/authorizer/content.go
  pkg/virtual/apiexport/authorizer/maximal_permission_policy.go
  pkg/virtual/apiexport/builder/build.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/homeworkspaces/home_workspaces_test.go
Labels: approved, lgtm

#2451 🐛 Remove list SyncTarget in bind compute cmd
  pkg/cliplugins/bind/plugin/bind_compute.go
  test/e2e/reconciler/namespace/controller_test.go
Labels: approved, lgtm

#2448 :seedling: remove EnableMultiCluster hack
  go.mod
  go.sum
  pkg/server/config.go
  pkg/server/filters/filters.go
  pkg/server/handler.go
Labels: approved, lgtm

#2458 ✨ Implement a scoped committer
  pkg/reconciler/committer/committer.go
Labels: approved, lgtm

#2464 :bug: go.mod: bump k8s
  go.mod
  go.sum
Labels: approved, lgtm

#2467 🐛 Fix no-op patches in committer
  pkg/reconciler/committer/committer.go
Labels: approved, lgtm

#2453 🐛Syncer: Remaining fixes on downstream namespace cleaning
  pkg/syncer/namespace/namespace_downstream_controller.go
  pkg/syncer/spec/spec_controller.go
Labels: area/transparent-multi-cluster, approved, lgtm

#2473 🐛 Avoid updating placement from getter
  pkg/reconciler/workload/placement/placement_reconcile_scheduling.go
  pkg/reconciler/workload/placement/placement_reconcile_scheduling_test.go
Labels: approved, lgtm

#2463 🌱 [0.9] Use Go 1.19, set GOMEMLIMIT
  .ci-operator.yaml
  .github/workflows/ci.yaml
  .github/workflows/goreleaser.yml
  .github/workflows/kcp-image.yaml
  .github/workflows/kcp-test-image.yaml
  .github/workflows/syncer-image.yaml
  CONTRIBUTING.md
  Dockerfile
  cmd/apigen/main.go
  cmd/compat/main.go
  cmd/crd-puller/pull-crds.go
  cmd/sharded-test-server/doc.go
  cmd/sharded-test-server/frontproxy.go
  go.mod
  manifest/kcp.yaml
  pkg/apis/go.mod
  pkg/apis/third_party/conditions/util/conditions/merge.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/embeddedetcd/config.go
  pkg/proxy/mapping.go
  pkg/proxy/proxy.go
  pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
  pkg/server/apiextensions.go
  pkg/server/controllers.go
  pkg/server/filters/filters_test.go
  pkg/server/options/authentication.go
  pkg/tunneler/integration_test.go
  pkg/virtual/framework/dynamic/apiserver/handler.go
  pkg/virtual/framework/dynamic/apiserver/handler_test.go
  pkg/virtual/framework/dynamic/doc.go
  pkg/virtual/syncer/doc.go
  test/e2e/fixtures/kcp-test-image/icc-test.go
  test/e2e/fixtures/webhook/webhook.go
  test/e2e/fixtures/wildwest/client/clientset/versioned/fake/register.go
  test/e2e/fixtures/wildwest/client/clientset/versioned/scheme/register.go
  test/e2e/framework/accessory.go
  test/e2e/framework/syncer.go
  test/e2e/framework/util.go
Labels: approved, lgtm

#2468 🌱 Use Go 1.19, set GOMEMLIMIT in kcp manifest
  .ci-operator.yaml
  .github/workflows/ci.yaml
  .github/workflows/docs-gen-and-push.yaml
  .github/workflows/e2e-ci-ppc64le.yml
  .github/workflows/goreleaser.yml
  .github/workflows/kcp-image.yaml
  .github/workflows/kcp-test-image.yaml
  .github/workflows/syncer-image.yaml
  CONTRIBUTING.md
  Dockerfile
  cmd/sharded-test-server/doc.go
  docs/content/en/main/concepts/syncer.md
  docs/go.mod
  go.mod
  manifest/kcp.yaml
  pkg/apis/go.mod
  pkg/apis/third_party/conditions/util/conditions/merge.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
  pkg/virtual/framework/dynamic/apiserver/handler.go
  pkg/virtual/framework/dynamic/doc.go
  pkg/virtual/syncer/doc.go
  pkg/virtual/syncer/transformations/types.go
  test/e2e/fixtures/wildwest/client/clientset/versioned/fake/register.go
  test/e2e/fixtures/wildwest/client/clientset/versioned/scheme/register.go
Labels: approved, lgtm

#2475 🐛 Syncer: add 'get' permission on downstream namespaces
  pkg/cliplugins/workload/plugin/sync_test.go
  pkg/cliplugins/workload/plugin/syncer.yaml
Labels: approved, lgtm

#2476 🌱 pkg/authorization: add delegation reason in audit
  pkg/authorization/bootstrap_policy_authorizer.go
  pkg/authorization/decorator.go
  pkg/authorization/decorator_test.go
  pkg/authorization/local_authorizer.go
  pkg/authorization/maximal_permission_policy_authorizer.go
  pkg/authorization/system_crd_authorizer.go
  pkg/authorization/toplevel_org_authorizer.go
  pkg/authorization/workspace_content_authorizer.go
  pkg/authorization/workspace_content_authorizer_test.go
  pkg/server/options/authorization.go
  pkg/virtual/apiexport/builder/build.go
Labels: approved, lgtm

#2336 ✨ New Deployment Splitter as a coordination controller
  .github/workflows/ci.yaml
  Makefile
  pkg/reconciler/coordination/deployment/deployment_controller.go
  pkg/reconciler/coordination/deployment/deployment_controller_test.go
  test/e2e/framework/syncer.go
  test/e2e/reconciler/deployment/deployment_coordinator_test.go
  test/e2e/reconciler/deployment/locations/east.yaml
  test/e2e/reconciler/deployment/locations/embed.go
  test/e2e/reconciler/deployment/locations/west.yaml
  test/e2e/reconciler/deployment/workloads/deployment.yaml
  test/e2e/reconciler/deployment/workloads/embed.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
  tmc/cmd/deployment-coordinator/cmd/deployment_coordinator.go
  tmc/cmd/deployment-coordinator/main.go
  tmc/cmd/deployment-coordinator/options/options.go
Labels: area/transparent-multi-cluster, approved, lgtm

#2474 🐛 Add missing battery annotation for root-compute-workspace
  config/rootcompute/kube-1.24/apiexport-kubernetes.k8s.io.yaml
  config/rootcompute/kube-1.24/clusterrole-kubernetes-maximal-permission-policy.yaml
  config/rootcompute/kube-1.24/clusterrolebinding-kubernetes-maximal-permission-policy.yaml
Labels: approved, lgtm

#2488 🌱 Add github action concurrency based on workflow-ref
  .github/workflows/ci.yaml
  .github/workflows/e2e-ci-ppc64le.yml
Labels: approved, lgtm

#2492 🌱 Test goreleaser changes in CI
  .github/workflows/goreleaser.yml
Labels: approved, lgtm

#2495 🌱 goreleaser: distinguish tags and PRs
  .github/workflows/goreleaser.yml
Labels: approved, lgtm

#2405 🐛 Fix parsing of requests to root path of a workload cluster
  pkg/server/filters/filters.go
Labels: approved, lgtm, ok-to-test

#2497 🌱 Add test for shallow copy and make partial metadata CRD
  pkg/server/apiextensions_test.go
Labels: approved, lgtm

#2499 :book: Attempt to update doc on workspaces
  docs/content/en/main/concepts/workspaces.md
Labels: approved, lgtm

#2503 🐛 docs: mkdir before moving
  .github/workflows/docs-gen-and-push.yaml
Labels: approved, lgtm

#2506 :seedling: Correct the typo in an error message
  pkg/server/options/authentication.go
Labels: approved, lgtm, needs-ok-to-test

#2505 🐛 Fix and add test to capture a race w/ partial metadata in cache
  pkg/server/apiextensions.go
  pkg/server/apiextensions_test.go
  test/e2e/conformance/crd_partial_metadata_test.go
Labels: approved, lgtm

#2509 🐛 pkg/softimpersonation: deep copy rest config
  pkg/softimpersonation/softimpersonation.go
Labels: approved, lgtm

#2514 🌱 sharded-test-server: add quiet support to front-proxy
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/main.go
Labels: approved, lgtm

#2515 🌱 Deflake apibinding immutability test
  test/e2e/apibinding/apibinding_test.go
Labels: approved, lgtm

#2520 🌱 logicalcluster deletion: switch to .Cluster()
  pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
Labels: approved, lgtm

#2519 🌱 Use deletion handling keyfunc where needed
  pkg/reconciler/core/logicalcluster/logicalcluster_controller.go
  pkg/reconciler/tenancy/logicalcluster/logicalcluster_controller.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_controller.go
Labels: approved, lgtm

#2516 🌱 Add indexers.ByPathAndName helper
  pkg/admission/apibinding/apibinding_admission.go
  pkg/admission/webhook/generic_webhook.go
  pkg/admission/workspacetypeexists/admission.go
  pkg/authorization/maximal_permission_policy_authorizer.go
  pkg/indexers/indexers.go
  pkg/permissionclaim/permissionclaim_labeler.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
  pkg/reconciler/tenancy/workspace/workspace_controller.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling_test.go
  pkg/reconciler/tenancy/workspacetype/clusterworkspacetype_controller.go
  pkg/reconciler/workload/placement/placement_reconcile.go
  pkg/reconciler/workload/synctargetexports/synctargetexports_controller.go
  pkg/server/home_workspaces.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
Labels: approved, lgtm, kind/api-change

#2521 :seedling: *: s/SystemBoundCRDSClusterName/SystemBoundCRDsClusterName/g
  pkg/admission/crdnooverlappinggvr/crdnooverlappinggvr_admission.go
  pkg/admission/reservedcrdannotations/admission.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
  pkg/reconciler/apis/apibinding/conflict_checker.go
  pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
  pkg/server/apiextensions.go
Labels: approved, lgtm, kind/api-change

#2522 :seedling: test/e2e: remove MultiClusterRoundTripper
  test/e2e/framework/syncer.go
Labels: approved, lgtm

#2512 ✨ Use distroless/static:debug as base image
  .dockerignore
  Dockerfile
  Makefile
  hack/boilerplate/boilerplate.Dockerfile.txt
Labels: approved, lgtm

#2528 🌱 Use buildx to build KCP images
  .github/workflows/kcp-image.yaml
  Dockerfile
Labels: approved, lgtm

#2511 :bug: pkg/authorization: prevent double audit logs
  pkg/authorization/decorator.go
  pkg/authorization/decorator_test.go
  pkg/server/config.go
Labels: approved, lgtm
