Repository kcp-dev/kcp, pull requests merged in 2022-11, with the labels that each got.

#2283 :bug: test/e2e/framework: Don't try to pull logs from a non-ready POD
  test/e2e/framework/syncer.go
Labels: approved, lgtm

#2294 🐛 Fix: watch a certain synctarget only
  pkg/cliplugins/workload/plugin/sync.go
  pkg/syncer/apiimporter.go
  pkg/syncer/resourcesync/controller.go
  pkg/syncer/syncer.go
Labels: approved, lgtm

#2297 :seedling: sharded-test-server: consistently use workDirPath
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/main.go
  cmd/sharded-test-server/shard.go
  cmd/sharded-test-server/virtual.go
Labels: approved, lgtm

#2240 🌱 cache: add replicateAPIResourceSchema test scenario
  test/e2e/reconciler/cache/replication_test.go
Labels: approved, lgtm

#2292 :bug: Return apierrors.StatusError inside client getters
  pkg/virtual/framework/forwardingregistry/store.go
Labels: approved, lgtm, needs-ok-to-test

#2311 🌱 cache:replication:e2e: export functions for working with the cache server
  test/e2e/reconciler/cache/helpers.go
  test/e2e/reconciler/cache/replication_test.go
Labels: approved, lgtm

#2313 🌱 cache: WithShardScope doesn't require a shard name for well-know paths
  pkg/cache/server/handler.go
Labels: approved, lgtm

#2288 🐛 Fix incorrect cleaning of deletion annotations
  pkg/reconciler/workload/resource/resource_reconcile.go
  pkg/reconciler/workload/resource/resource_reconcile_test.go
Labels: approved, lgtm

#2317 🌱 add new flag (root-directory) for the cache server binary
  cmd/cache-server/main.go
  pkg/cache/server/options/options.go
  pkg/server/options/cache.go
Labels: approved, lgtm

#2256 🌱 cache: add e2e scenarios for testing behaviour of the cache server
  test/e2e/cache/cache_server_test.go
  test/e2e/reconciler/cache/helpers.go
  test/e2e/reconciler/cache/replication_test.go
Labels: approved, lgtm

#2303 :seedling: test-server: split New/Start/Ready phases
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/main.go
  cmd/sharded-test-server/shard.go
  cmd/test-server/kcp/shard.go
  cmd/test-server/main.go
Labels: approved, lgtm

#2307 🐛 Fix root phase 0 bootstrapping sometimes failing
  config/helpers/bootstrap.go
  hack/logcheck.out
Labels: approved, lgtm

#2286 🌱 types_apiexport: make all and resourceSelector/namespace optional
  config/crds/apis.kcp.dev_apibindings.yaml
  config/crds/apis.kcp.dev_apiexports.yaml
  go.mod
  go.sum
  pkg/apis/apis/v1alpha1/types_apiexport.go
  pkg/apis/apis/v1alpha1/types_apiexport_test.go
  pkg/openapi/zz_generated.openapi.go
Labels: approved, lgtm, kind/api-change

#2330 🐛 Fix cluster authentication trust controller hotloop
  go.mod
  go.sum
Labels: approved, lgtm

#2180 :sparkles: Implements Upsyncer Virtual Workspace
  hack/logcheck.out
  pkg/virtual/syncer/builder/build.go
  pkg/virtual/syncer/builder/forwarding.go
  pkg/virtual/syncer/builder/template.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_controller.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_indexes.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
  pkg/virtual/syncer/options/options.go
  pkg/virtual/syncer/upsyncer/storage_wrapper.go
  pkg/virtual/syncer/upsyncer/transformer.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#2319 :seedling: proxy: optionally enable OIDC auth
  pkg/proxy/options/authentication.go
Labels: approved, lgtm

#2343 🐛 Support `deployments/scale` in root compute
  config/rootcompute/kube-1.24/clusterrole-kubernetes-maximal-permission-policy.yaml
  test/e2e/reconciler/locationworkspace/rootcompute_test.go
Labels: approved, lgtm

#2346 :book: Correcting the link to the developers doc
  README.md
Labels: approved, lgtm, ok-to-test

#2348 🌱 Protect imports target with Go version check
  Makefile
Labels: lgtm

#2298 :bug: Clean up shadow CRDs after API bindings are deleted
  pkg/indexers/apibinding.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go
  pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
  pkg/reconciler/apis/crdcleanup/crdcleanup_controller_test.go
  pkg/server/apiextensions.go
  pkg/server/controllers.go
  pkg/server/server.go
  test/e2e/apibinding/apibinding_deletion_test.go
Labels: approved, lgtm

#2339 🐛 sharded-test-server: fix the way we calculate the embedded etcd client ports
  cmd/sharded-test-server/shard.go
  cmd/sharded-test-server/shard_test.go
Labels: approved, lgtm

#2299 ✨ Downstream Namespace cleanup: ensure namespace is empty and delete after a grace period
  cmd/syncer/cmd/syncer.go
  cmd/syncer/options/options.go
  pkg/syncer/namespace/namespace_downstream_controller.go
  pkg/syncer/namespace/namespace_downstream_process.go
  pkg/syncer/namespace/namespace_downstream_process_test.go
  pkg/syncer/namespace/namespace_upstream_controller.go
  pkg/syncer/namespace/namespace_upstream_process.go
  pkg/syncer/namespace/namespace_upstream_process_test.go
  pkg/syncer/resourcesync/controller.go
  pkg/syncer/shared/cleaner.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_process_test.go
  pkg/syncer/syncer.go
  test/e2e/framework/syncer.go
Labels: approved, lgtm

#2354 🐛 cmd/sync: ensure port is set on cluster url
  pkg/cliplugins/workload/plugin/sync.go
Labels: approved, lgtm

#2293 :sparkles: Create one DNS nameserver per workspace
  cmd/syncer/cmd/dns.go
  cmd/syncer/cmd/syncer.go
  cmd/syncer/options/dnsoptions.go
  cmd/syncer/options/options.go
  hack/logcheck.out
  pkg/cliplugins/workload/plugin/sync.go
  pkg/cliplugins/workload/plugin/sync_test.go
  pkg/cliplugins/workload/plugin/syncer.yaml
  pkg/dns/plugin/nsmap/config.go
  pkg/syncer/namespace/namespace_downstream_process.go
  pkg/syncer/namespace/namespace_downstream_process_test.go
  pkg/syncer/shared/helpers.go
  pkg/syncer/spec/dns/deployment_dns.yaml
  pkg/syncer/spec/dns/dns_process.go
  pkg/syncer/spec/dns/resources.go
  pkg/syncer/spec/dns/role_dns.yaml
  pkg/syncer/spec/dns/rolebinding_dns.yaml
  pkg/syncer/spec/dns/service_dns.yaml
  pkg/syncer/spec/dns/serviceaccount_dns.yaml
  pkg/syncer/spec/mutators/deployment.go
  pkg/syncer/spec/mutators/deployment_test.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/syncer.go
  test/e2e/fixtures/kube/core.k8s.io_endpoints.yaml
  test/e2e/framework/syncer.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/locationworkspace/local_apiexport_test.go
  test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
  test/e2e/reconciler/locationworkspace/rootcompute_test.go
  test/e2e/reconciler/locationworkspace/synctarget_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm, ok-to-test

#2360 :bug: clusterworkspaceshard: fix admission and shard creation for multi-shard setups
  config/crds/tenancy.kcp.dev_clusterworkspaceshards.yaml
  config/root-phase0/apiexport-shards.tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspaceshards.tenancy.kcp.dev.yaml
  config/root/bootstrap.go
  config/root/clusterworkspaceshard.yaml
  config/root/secret-shard.yaml
  pkg/admission/clusterworkspaceshard/admission.go
  pkg/admission/clusterworkspaceshard/admission_test.go
  pkg/admission/clusterworkspacetypeexists/admission_test.go
  pkg/admission/initializers/initializer.go
  pkg/admission/initializers/interfaces.go
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/openapi/zz_generated.openapi.go
  pkg/server/config.go
  pkg/server/server.go
Labels: approved, lgtm, kind/api-change

#2341 ✨ relax workspace object name validation
  config/crds/tenancy.kcp.dev_clusterworkspaces.yaml
  config/crds/tenancy.kcp.dev_clusterworkspaces.yaml-patch
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml-patch
  config/crds/tenancy.kcp.dev_workspaces.yaml
  config/crds/tenancy.kcp.dev_workspaces.yaml-patch
  config/root-phase0/apiexport-tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspaces.tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspacetypes.tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-workspaces.tenancy.kcp.dev.yaml
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/server/filters/filters.go
  pkg/server/filters/filters_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Labels: approved, lgtm, ok-to-test, kind/api-change

#2361 :bug: CLI: Fix sync command apiexports option usage
  pkg/cliplugins/workload/plugin/sync.go
Labels: approved, lgtm

#2322 📖 Improve docs for developers/library-usage
  docs/content/en/main/concepts/developers/library-usage.md
Labels: approved, lgtm, ok-to-test

#2302 :bug: Add request, latency, and workqueue metrics to front proxy
  go.mod
  pkg/proxy/mapping.go
  pkg/proxy/metrics/metrics.go
  pkg/proxy/proxy.go
  pkg/proxy/server.go
Labels: approved, lgtm

#2372 :bug: test/e2e/virtual/syncer: skip tests until fixed
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#2370 🐛 syncer: Fix wrong logic in dns-related process
  pkg/syncer/namespace/namespace_downstream_controller.go
  pkg/syncer/namespace/namespace_upstream_controller.go
  pkg/syncer/resourcesync/controller.go
  pkg/syncer/spec/dns/dns_process.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_process_test.go
Labels: approved, lgtm

#2367 🐛 Lookup DNS IP in Service
  pkg/syncer/spec/mutators/deployment.go
  pkg/syncer/spec/mutators/deployment_test.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process_test.go
  test/e2e/framework/syncer.go
  test/e2e/reconciler/locationworkspace/rootcompute_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#2376 :bug: Fix group in scheduling.kcp.dev maximum permission policy cluster role
  config/root/clusterrole-scheduling-maximal-permission-policy.yaml
Labels: approved, lgtm

#2374 🐛Syncer namespace cleanup refactor
  cmd/syncer/options/options.go
  hack/logcheck.out
  pkg/cliplugins/workload/plugin/sync.go
  pkg/cliplugins/workload/plugin/sync_test.go
  pkg/cliplugins/workload/plugin/syncer.yaml
  pkg/syncer/namespace/namespace_downstream_controller.go
  pkg/syncer/namespace/namespace_downstream_process.go
  pkg/syncer/namespace/namespace_downstream_process_test.go
  pkg/syncer/namespace/namespace_upstream_controller.go
  pkg/syncer/namespace/namespace_upstream_process.go
  pkg/syncer/namespace/namespace_upstream_process_test.go
  pkg/syncer/resourcesync/controller.go
  pkg/syncer/shared/cleaner.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_process_test.go
  pkg/syncer/syncer.go
  test/e2e/framework/syncer.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: area/transparent-multi-cluster, approved, lgtm

#2386 🐛 Fix BoundWorkspace race condition
  test/e2e/framework/syncer.go
Labels: approved, lgtm

#2387 🐛 cache: do not use protobufs for self-communication
  pkg/cache/server/config.go
Labels: approved, lgtm

#2379 🐛 Further cleanup to tmc-related e2e tests
  pkg/cliplugins/workload/plugin/sync.go
  pkg/reconciler/workload/namespace/namespace_controller.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/syncer/shared/finalizer.go
  pkg/syncer/spec/spec_process.go
  test/e2e/framework/kcp.go
  test/e2e/framework/syncer.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/locationworkspace/local_apiexport_test.go
  test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
  test/e2e/reconciler/locationworkspace/rootcompute_test.go
  test/e2e/reconciler/locationworkspace/synctarget_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#2400 ✨ Upsyncer VW: Enable status subresource
  pkg/virtual/syncer/builder/forwarding.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#2408 🐛 Syncer: fix APIImporter broken after one recent rebase
  pkg/syncer/apiimporter.go
Labels: approved, lgtm

#2424 :bug: CLI: Better error messages to `bind compute`
  pkg/cliplugins/bind/plugin/bind_compute.go
Labels: approved, lgtm

#2373 :bug: fix Internal error when creating a ClusterRole while authenticated as a ServiceAccount
  go.mod
  go.sum
  pkg/authorization/bootstrap_policy_authorizer.go
  pkg/authorization/local_authorizer.go
  pkg/virtual/workspaces/authorization/cache.go
  pkg/virtual/workspaces/authorization/cache_test.go
  pkg/virtual/workspaces/authorization/reviewer.go
  pkg/virtual/workspaces/registry/rest_test.go
  test/e2e/authorizer/serviceaccounts_test.go
Labels: approved, lgtm

#2436 :seedling: Update logicalcluster dependency
  go.mod
  go.sum
Labels: approved, lgtm

#2438 :bug: Ignore APIBinding 403 errors when changing WS
  pkg/cliplugins/workspace/plugin/kubeconfig.go
Labels: approved, lgtm
