Repository kcp-dev/kcp, pull requests merged in 2022-06, with the labels that each got.

#1208 CONTRIBUTING.md: add Go Proverbs
  CONTRIBUTING.md
Labels: approved, lgtm

#1212 Replace `--use` with `--enter`
  pkg/cliplugins/workspace/cmd/cmd.go
Labels: approved, lgtm, ok-to-test

#1220 APIExport virtual workspace: add core/v1
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/fixtures/apifixtures/apibinding.go
  test/e2e/fixtures/apifixtures/sheriffs.go
  test/e2e/framework/json.go
  test/e2e/virtual/apiexport/support.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm

#1218 e2e: extract APIExport/APIBinding helpers
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/fixtures/apifixtures/apibinding.go
  test/e2e/fixtures/apifixtures/sheriffs.go
  test/e2e/framework/json.go
Labels: approved

#1216 Added ppc64le support to KCP image
  .github/workflows/kcp-image.yaml
Labels: approved, lgtm, needs-ok-to-test

#1098 Add E2E tests for cordon/uncordon/drain CLI
  test/e2e/syncer/syncer_test.go
Labels: approved, lgtm

#1226 Add virtual workspace readiness checks to the KCP server in the embedded case
  pkg/server/server.go
  pkg/server/virtual.go
  pkg/virtual/framework/rootapiserver/root_apiserver.go
Labels: approved, lgtm

#1231 e2e/apibinding: require.Eventually for discovery
  test/e2e/apibinding/apibinding_protected_test.go
Labels: approved, lgtm

#1232 e2e/virtual/initializers: fix flake in TestInitializingWorkspacesVirtualWorkspaceDiscovery
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Labels: approved, lgtm

#1237 clusterworkspacetype: stop special-casing Universal
  pkg/admission/clusterworkspacetypeexists/admission.go
  pkg/admission/clusterworkspacetypeexists/admission_test.go
Labels: approved, lgtm

#1228 Enable syncer finalizers (k8s & virtual) by default.
  pkg/reconciler/workload/resource/resource_reconcile.go
  pkg/reconciler/workload/resource/resource_reconcile_test.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_process.go
  pkg/syncer/status/status_process_test.go
  test/e2e/syncer/syncer_test.go
Labels: approved, lgtm

#1217 APIBinding reconciler checks for overlapping CRDs in a logical cluster
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibinding/apibinding_indexes.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
  pkg/reconciler/apis/apibinding/conflict_checker.go
  pkg/reconciler/apis/apibinding/conflict_checker_test.go
Labels: approved, lgtm

#1241 Fix Ingress cluster assignment based on namespace placement
  pkg/reconciler/workload/resource/resource_reconcile.go
Labels: approved, lgtm

#1251 CONTRIBUTING.md: document nested require statements
  CONTRIBUTING.md
Labels: approved, lgtm

#1247 e2e/virtual/syncer: fixing race with resource controller in TestSyncerVirtualWorkspace
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#1207 ci: turn off GitHub CI for jobs we run in Prow
  .github/workflows/ci-docs-only.yaml
  .github/workflows/ci.yaml
Labels: approved, lgtm

#1250 pkg/etcd,server: add --embedded-etcd-force-new-cluster
  pkg/etcd/etcd.go
  pkg/server/options/embeddedetcd.go
  pkg/server/options/flags.go
  pkg/server/server.go
Labels: approved, lgtm

#1252 ci: delete demos.yaml
  .github/workflows/demos.yaml
Labels: approved, lgtm

#1235 Added ppc64le and arm64 support to the Syncer image
  .github/workflows/syncer-image.yaml
Labels: approved, lgtm, ok-to-test

#1230 tenancy: qualify cluster workspace types
  config/crds/tenancy.kcp.dev_clusterworkspaces.yaml
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml-patch
  config/crds/tenancy.kcp.dev_workspaces.yaml
  config/root/clusterworkspace-default.yaml
  config/root/clusterworkspacetype-organization.yaml
  config/root/clusterworkspacetype-team.yaml
  config/root/clusterworkspacetype-universal.yaml
  config/root/clusterworkspacetype-use-clusterrole.yaml
  config/root/clusterworkspacetype-use-clusterrolebinding.yaml
  config/team/clusterworkspacetype-universal.yaml
  pkg/admission/clusterworkspace/admission.go
  pkg/admission/clusterworkspace/admission_test.go
  pkg/admission/clusterworkspaceshard/admission_test.go
  pkg/admission/clusterworkspacetype/admission.go
  pkg/admission/clusterworkspacetype/admission_test.go
  pkg/admission/clusterworkspacetypeexists/admission.go
  pkg/admission/clusterworkspacetypeexists/admission_test.go
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/tenancy/v1beta1/types.go
  pkg/apis/tenancy/v1beta1/zz_generated.deepcopy.go
  pkg/cliplugins/workspace/cmd/cmd.go
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/cliplugins/workspace/plugin/kubeconfig_test.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_reconcile.go
  pkg/server/apiextensions.go
  pkg/server/controllers.go
  pkg/virtual/workspaces/registry/rest.go
  test/e2e/framework/fixture.go
  test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm

#1260 Update video on readme to v0.4
  README.md
Labels: approved, lgtm

#1263 ClusterWorkspace+Types: allow name "org"
  config/crds/tenancy.kcp.dev_clusterworkspaces.yaml
  config/crds/tenancy.kcp.dev_clusterworkspaces.yaml-patch
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml-patch
  config/crds/tenancy.kcp.dev_workspaces.yaml
  config/crds/tenancy.kcp.dev_workspaces.yaml-patch
Labels: approved, lgtm

#1265 pkg/authorization: don't check for cluster workspace lister.
  pkg/authorization/workspace_content_authorizer.go
Labels: approved, lgtm

#1268 kubectl kcp ws: fix type printing
  pkg/cliplugins/workspace/plugin/kubeconfig.go
Labels: approved, lgtm

#1269 reconciler/workload/resource: use RF3339 timestamp format
  pkg/reconciler/workload/resource/resource_reconcile.go
  pkg/reconciler/workload/resource/resource_reconcile_test.go
Labels: approved, lgtm

#1258 Placement API
  config/crds/scheduling.kcp.dev_placements.yaml
  config/system-crds/bootstrap.go
  pkg/apis/scheduling/v1alpha1/register.go
  pkg/apis/scheduling/v1alpha1/types_placement.go
  pkg/apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_placement.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_scheduling_client.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/placement.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/scheduling_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/scheduling/v1alpha1/interface.go
  pkg/client/informers/externalversions/scheduling/v1alpha1/placement.go
  pkg/client/listers/scheduling/v1alpha1/expansion_generated.go
  pkg/client/listers/scheduling/v1alpha1/placement.go
  pkg/features/kcp_features.go
  pkg/openapi/zz_generated.openapi.go
  pkg/server/apiextensions.go
Labels: approved, lgtm

#1210 README.md: add hypercube logo and sources
  README.md
  contrib/logo/README.md
  contrib/logo/blue-green-glow.png
  contrib/logo/blue-green-high-contrast.png
  contrib/logo/blue-green-high-contrast.svg
  contrib/logo/blue-green.png
  contrib/logo/blue-green.svg
  contrib/logo/hypercube.amdn/Icon 
  contrib/logo/hypercube.amdn/Icon.png
  contrib/logo/hypercube.amdn/QuickLook/Preview.png
  contrib/logo/hypercube.amdn/project.xml
  contrib/logo/red-blue-glow.png
  contrib/logo/red-blue-high-contrast.png
  contrib/logo/red-blue-high-contrast.svg
  contrib/logo/red-blue.png
  contrib/logo/red-blue.svg
Labels: milestone-blocker, approved, lgtm

#1267 initializingworkspaces: enforce permissions
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml
  pkg/apis/tenancy/initialization/utils.go
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/initializingworkspaces/options/options.go
  pkg/virtual/options/options.go
  test/e2e/framework/util.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Labels: approved, lgtm

#1272 virtual: Remove unsupported verbs from virtual API server discovery
  pkg/virtual/apiexport/builder/forwarding.go
Labels: approved, lgtm

#1276 Remove logo icon file with invalid name
  contrib/logo/hypercube.amdn/Icon 
Labels: approved, lgtm

#1273 virtual workspaces: skips registartion of default health checks
  pkg/server/virtual.go
Labels: approved, lgtm

#1284 Added prerequisites on the README
  README.md
Labels: approved, lgtm, ok-to-test

#1286 cmd/test-server: pass flags to kcp
  cmd/test-server/main.go
Labels: approved, lgtm

#1296 cli: fix ClusterWorkspace columns output
  config/crds/tenancy.kcp.dev_clusterworkspaces.yaml
  config/crds/tenancy.kcp.dev_workspaces.yaml
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/apis/tenancy/v1beta1/types.go
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/virtual/workspaces/printers/printer.go
Labels: approved, lgtm

#1287 cmd/kcp: non-zero return code on error
  cmd/kcp/kcp.go
Labels: approved, lgtm

#1295 server: centrally create and start ddsif
  pkg/informer/informer.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/reconciler/workload/resource/resource_reconcile.go
  pkg/server/controllers.go
  pkg/server/indexes.go
  pkg/server/server.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
Labels: approved, lgtm

#1297 Reduce log noise
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/workload/resource/resource_reconcile.go
Labels: approved, lgtm

#1289 e2e: switch NewWorkspaceFixture to options
  pkg/apis/workload/v1alpha1/types.go
  test/e2e/apibinding/apibinding_authorizer_test.go
  test/e2e/apibinding/apibinding_deletion_test.go
  test/e2e/apibinding/apibinding_protected_test.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/apibinding/apibinding_webhook_test.go
  test/e2e/authorizer/rootcacertconfigmap_test.go
  test/e2e/authorizer/serviceaccounts_test.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/conformance/webhook_test.go
  test/e2e/customresourcedefinition/customresourcedefinition_test.go
  test/e2e/framework/fixture.go
  test/e2e/framework/kcp.go
  test/e2e/reconciler/apiexport/apiexport_controller_test.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/ingress/controller_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm

#1300 Clean up unused e2e helpers
  test/e2e/fixtures/apifixtures/sheriffs.go
  test/e2e/framework/expect.go
  test/e2e/framework/json.go
  test/e2e/framework/kcp.go
  test/e2e/framework/test.go
  test/e2e/framework/testhelper.go
  test/e2e/framework/testhelper_test.go
  test/e2e/framework/users.go
  test/e2e/framework/util.go
  test/e2e/reconciler/ingress/controller_test.go
Labels: approved, lgtm

#1302 admission/clusterworkspace: check errors in unit test
  pkg/admission/clusterworkspace/admission_test.go
Labels: approved, lgtm

#1304 pkg/reconciler/apis/apiexport: clarify patching strategy in case of programming errors
  pkg/reconciler/apis/apiexport/apiexport_controller.go
Labels: approved, lgtm

#1310 Makefile: add test-e2e-shared
  Makefile
  cmd/test-server/main.go
Labels: approved, lgtm

#1303 tenancy: show Deleting in phase column during ClusterWorkspace deletion
  pkg/virtual/workspaces/printers/printer.go
Labels: approved, lgtm

#1299 APIBinding/Workspace deletion improvement
  config/crds/tenancy.kcp.dev_workspaces.yaml
  pkg/admission/apibindingfinalizer/apibindingfinalizer_admission.go
  pkg/admission/clusterworkspacefinalizer/clusterworkspacefinalizer_admission.go
  pkg/admission/finalizer/finalizer_admission.go
  pkg/admission/finalizer/finalizer_admission_test.go
  pkg/admission/plugins.go
  pkg/apis/tenancy/projection/workspaces.go
  pkg/apis/tenancy/v1beta1/types.go
  pkg/apis/tenancy/v1beta1/zz_generated.deepcopy.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletor_test.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/clusterworkspace_deletion_controller.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go
  pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor_test.go
  pkg/server/controllers.go
Labels: approved, lgtm

#1311 github/ci.yaml: use test-e2e-shared make target
  .github/workflows/ci.yaml
  Makefile
Labels: approved, lgtm

#1317 e2e/syncer: less noise with framework.Eventually
  test/e2e/syncer/syncer_test.go
Labels: approved, lgtm

#1288 reconciler/clusterworkspace: split into independent reconcilers
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_indexes.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata_test.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_phase.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_scheduling.go
  test/e2e/reconciler/clusterworkspace/controller_test.go
Labels: approved, lgtm

#1312 admin.kubeconfig: remove cross-cluster context
  pkg/server/options/authentication.go
Labels: approved, lgtm

#1292 e2e/framework: wait some time until printing message in Eventually
  test/e2e/framework/util.go
Labels: approved, lgtm

#1314 authorizer: unify workspace access reason
  pkg/authorization/toplevel_org_authorizer.go
  pkg/authorization/workspace_content_authorizer.go
  pkg/authorization/workspace_content_authorizer_test.go
Labels: approved, lgtm

#1321 admission: record the user creating a workspace
  pkg/admission/clusterworkspacetypeexists/admission.go
  pkg/admission/clusterworkspacetypeexists/admission_test.go
  pkg/apis/tenancy/v1alpha1/types.go
Labels: approved, lgtm

#1322 Fix partial meta request determination logic
  go.mod
  pkg/server/apiextensions.go
  pkg/server/apiextensions_test.go
Labels: approved, lgtm

#1318 ClusterWorkspaces: add optional spec.shard scheduling constraints
  config/crds/tenancy.kcp.dev_clusterworkspaces.yaml
  config/crds/tenancy.kcp.dev_clusterworkspaces.yaml-patch
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_scheduling.go
  pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_scheduling_test.go
Labels: approved, lgtm

#1306 Update replace directive to last k/k commit
  go.mod
  go.sum
Labels: approved, lgtm

#1294 server/apiextensions: use indexes and fixes
  pkg/server/apiextensions.go
  pkg/server/indexes.go
  pkg/server/server.go
Labels: approved, lgtm

#1323 virtualworkspace: add a proxy for workspace content
  cmd/virtual-workspaces/command/cmd.go
  pkg/server/server.go
  pkg/server/virtual.go
  pkg/virtual/apiexport/options/options.go
  pkg/virtual/framework/handler/doc.go
  pkg/virtual/framework/handler/handler.go
  pkg/virtual/framework/types.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/initializingworkspaces/options/options.go
  pkg/virtual/options/options.go
  pkg/virtual/syncer/options/options.go
  pkg/virtual/workspaces/options/options.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Labels: approved, lgtm

#1240 turn the watch cache on
  go.mod
  go.sum
  pkg/server/options/options.go
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: approved, lgtm

#1328 pkg/virtual: externalize VW name and remove extra informers
  cmd/virtual-workspaces/command/cmd.go
  pkg/server/virtual.go
  pkg/virtual/apiexport/builder/build.go
  pkg/virtual/apiexport/options/options.go
  pkg/virtual/framework/authorization/authorizer.go
  pkg/virtual/framework/dynamic/example_test.go
  pkg/virtual/framework/dynamic/register.go
  pkg/virtual/framework/dynamic/types.go
  pkg/virtual/framework/fixedgvs/register.go
  pkg/virtual/framework/handler/handler.go
  pkg/virtual/framework/rootapiserver/root_apiserver.go
  pkg/virtual/framework/types.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/initializingworkspaces/options/options.go
  pkg/virtual/options/authorization.go
  pkg/virtual/options/options.go
  pkg/virtual/syncer/builder/build.go
  pkg/virtual/syncer/options/options.go
  pkg/virtual/workspaces/options/options.go
Labels: approved, lgtm

#1329 virtualworkspaces: propagate clarifying changes
  pkg/virtual/apiexport/builder/build.go
  pkg/virtual/framework/dynamic/example_test.go
  pkg/virtual/framework/dynamic/types.go
  pkg/virtual/framework/fixedgvs/register.go
  pkg/virtual/framework/fixedgvs/types.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/syncer/builder/build.go
  pkg/virtual/workspaces/builder/build.go
Labels: approved, lgtm

#1330 virtualworkspaces: allow access to remove iniitalizers
  cmd/kcp-front-proxy/filters.go
  cmd/kcp-front-proxy/main.go
  pkg/apis/apis/v1alpha1/crd_to_apiresourceschema.go
  pkg/metadata/dynamic.go
  pkg/server/requestinfo/util.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/initializingworkspaces/builder/forwarding.go
  test/e2e/framework/fixture.go
  test/e2e/framework/kcp.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Labels: approved, lgtm

#1343 pkg/admission: add reserved metadata admission plugin
  config/crds/scheduling.kcp.dev_placements.yaml
  pkg/admission/plugins.go
  pkg/admission/reservedmetadata/admission.go
  pkg/admission/reservedmetadata/admission_test.go
  pkg/apis/scheduling/v1alpha1/types_placement.go
  pkg/openapi/zz_generated.openapi.go
Labels: approved, lgtm

#1347 e2e/syncer: switch to multi-arch image
  test/e2e/syncer/deployment.yaml
Labels: approved, lgtm

#1348 Use logicalcluster.ClusterHeader constant for X-Kubernetes-Cluster
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/server/handler.go
  pkg/sharding/apiserver/delegating_storage.go
  pkg/sharding/apiserver/sharded_storage.go
Labels: approved, lgtm

#1346 Do not stomp other APIExports in a workspace with NegotatedAPIResources
  pkg/reconciler/workload/apiexport/apiexport_controller.go
  pkg/reconciler/workload/apiexport/apiexport_reconcile.go
  pkg/reconciler/workload/apiexport/apiexport_reconcile_test.go
Labels: approved, lgtm

#1345 reconciler/workload/namespace: stop hotloop
  pkg/reconciler/workload/namespace/namespace_reconcile.go
Labels: approved, lgtm

#1352 Fix hotloop in placement due to bad patch
  pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go
  pkg/reconciler/scheduling/placement/placement_reconcile_scheduling_test.go
Labels: approved, lgtm

#1356 e2e: print artifact paths
  test/e2e/framework/fixture.go
Labels: area/repo-health, approved, lgtm

#1358 reconciler/apibinding: clean up logs
  pkg/reconciler/apis/apibinding/apibinding_controller.go
Labels: approved, lgtm, kind/cleanup

#1357 e2e: cope with asynchronously served (bound) CRDs
  test/e2e/fixtures/apifixtures/sheriffs.go
Labels: approved, lgtm, kind/flake

#1360 virtual: clean up post-start errors and var names
  pkg/virtual/apiexport/builder/build.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/syncer/builder/build.go
  pkg/virtual/workspaces/builder/build.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Labels: approved, lgtm

#1363 CONTRIBUTING.md: document testing
  CONTRIBUTING.md
Labels: approved, lgtm

#1362 e2e/framework: doc Eventually
  test/e2e/framework/util.go
Labels: approved, lgtm

#1367 pkg/admission/reservedmetadata: optimize allocations
  pkg/admission/reservedmetadata/admission.go
  pkg/admission/reservedmetadata/admission_test.go
Labels: approved, lgtm

#1278 kcp CLI: error out for an non existent workspace while changing ws
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/cliplugins/workspace/plugin/kubeconfig_test.go
Labels: approved, lgtm, ok-to-test

#1365 server/apiextensions: stop serving non-wildcard identity requests
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibinding/apibinding_indexes.go
  pkg/server/apiextensions.go
  pkg/server/indexes.go
  pkg/server/server.go
Labels: approved, lgtm

#1371 cmd/kcp-front-proxy/authentication/groups.go: fix groups filtering
  cmd/kcp-front-proxy/authentication/groups.go
  cmd/kcp-front-proxy/authentication/groups_test.go
Labels: approved, lgtm

#1379 Makefile: be tolerant if local directory is not a git checkout
  Makefile
Labels: approved, lgtm

#1386 admission: only reserve our exact groups
  pkg/admission/reservedcrdgroups/admission.go
  pkg/admission/reservedcrdgroups/admission_test.go
  test/e2e/customresourcedefinition/customresourcedefinition_test.go
  test/e2e/customresourcedefinition/tenancy.kcp.dev_cowboys.yaml
Labels: approved, lgtm

#1378 Use authorization.WorkspaceAcccessNotPermittedReason
  pkg/authorization/toplevel_org_authorizer.go
  pkg/virtual/workspaces/registry/rest.go
  pkg/virtual/workspaces/registry/rest_test.go
Labels: approved, lgtm

#1390 VSCode: cleanup KCP launch configurations and use tokens
  contrib/kcp.code-workspace
Labels: lgtm

#1393 virtual: generalize label selector wrapper and get rid of panic
  pkg/virtual/framework/forwardingregistry/wrappers.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/initializingworkspaces/builder/forwarding.go
  pkg/virtual/syncer/builder/build.go
Labels: approved, lgtm

#1394 virtual/fixedgvs: import cleanup
  pkg/virtual/framework/fixedgvs/types.go
Labels: approved, lgtm

#1403 Update OWNERS to fix my name
  OWNERS
Labels: approved

#1402 kcp workspaces: improve wording for workspace creation
  pkg/cliplugins/workspace/plugin/kubeconfig.go
Labels: approved, lgtm

#1374 Workspaces VW: Fix obsolete permission management...
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/virtual/workspaces/registry/rest.go
  pkg/virtual/workspaces/registry/rest_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
Labels: approved, lgtm

#1407 Fix image build
  .dockerignore
Labels: approved, lgtm

#1396 authz: protect status subresource from non-system:masters
  pkg/authorization/system_crd_authorizer.go
  pkg/server/options/authorization.go
Labels: approved, lgtm

#1372 Various dynamic discovery shared informer factory updates
  pkg/indexers/indexers.go
  pkg/informer/informer.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/server/controllers.go
  pkg/server/server.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
Labels: approved, lgtm

#1409 Fix: Add version for kcp and syncer
  cmd/kcp/kcp.go
  cmd/syncer/cmd/syncer.go
Labels: approved, lgtm

#1414 workspaces VW: Fix CWT management
  pkg/virtual/workspaces/registry/rest.go
  pkg/virtual/workspaces/registry/rest_test.go
Labels: approved, lgtm

#1410 cmd,pkg: use constant for system:master
  cmd/sharded-test-server/main.go
  pkg/admission/finalizer/finalizer_admission.go
  pkg/admission/finalizer/finalizer_admission_test.go
  pkg/admission/reservedmetadata/admission_test.go
  pkg/server/options/authorization.go
  pkg/virtual/options/authorization.go
  pkg/virtual/workspaces/registry/rest.go
Labels: approved, lgtm

#1375 tenancy: add cluster workspace type extensions
  config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml
  config/root-phase0/apiexport-tenancy.kcp.dev.yaml
  config/root-phase0/apiresourceschema-clusterworkspacetypes.tenancy.kcp.dev.yaml
  config/root/clusterworkspace-default.yaml
  go.mod
  hack/update-codegen.sh
  pkg/admission/clusterworkspacetype/admission.go
  pkg/admission/clusterworkspacetype/admission_test.go
  pkg/admission/clusterworkspacetypeexists/admission.go
  pkg/admission/clusterworkspacetypeexists/admission_test.go
  pkg/admission/webhook/generic_webhook.go
  pkg/apis/tenancy/v1alpha1/types.go
  pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller.go
  pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller_reconcile.go
  pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller_reconcile_test.go
  pkg/server/options/authentication.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm
