Repository kcp-dev/kcp, pull requests merged in 2023-09, with the labels that each got.

#3005 :bug: make help
  Makefile
Labels: approved, lgtm, ok-to-test, size/M, release-note, dco-signoff: yes

#3010 [release-0.20] 📖 update release process doc
  docs/content/developers/publishing-a-new-kcp-release.md
Labels: approved, lgtm, size/M, dco-signoff: yes, release-note-none

#3009 :seedling: add vendor into .gitignore
  .gitignore
Labels: approved, lgtm, ok-to-test, size/XS, release-note, dco-signoff: yes

#3013 :sparkles: Add --cors-allowed-origins flag to kcp-front-proxy
  pkg/proxy/options/options.go
  pkg/proxy/server.go
Labels: approved, lgtm, size/S, release-note, dco-signoff: yes
