Repository kcp-dev/kcp, pull requests merged in 2023-10, with the labels that each got.

#3014 :book: Update README to include link to community meeting agenda doc
  README.md
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3015 :book: Add logo variants
  contrib/logo/blue-green-variants/black-horizontal.svg
  contrib/logo/blue-green-variants/black-stacked.svg
  contrib/logo/blue-green-variants/black.svg
  contrib/logo/blue-green-variants/color-horizontal.svg
  contrib/logo/blue-green-variants/color-stacked.svg
  contrib/logo/blue-green-variants/white-horizontal.svg
  contrib/logo/blue-green-variants/white-stacked.svg
  contrib/logo/blue-green-variants/white.svg
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#3020 :bug: Bump lint to 20min
  Makefile
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#3022 :seedling: Add new maintainers
  OWNERS
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3025 :seedling: Increase workspace init timeout in e2e tests to 60 seconds
  test/e2e/framework/workspaces.go
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#3027 📖 Adopt CNCF Code of Conduct
  README.md
  code-of-conduct.md
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes

#3019 :bug: prow fix go version validate
  hack/verify-go-versions.sh
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#3029 :seedling: Increase resource requests on Prow jobs but only run if code changed
  .prow.yaml
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes

#3018 :sparkles: Add CRDs to built-in types
  pkg/crdpuller/discovery.go
  pkg/informer/informer_test.go
  pkg/server/scheme/scheme.go
  pkg/virtual/apiexport/schemas/builtin/builtin.go
Labels: approved, lgtm, size/S, release-note, dco-signoff: yes

#3026 :bug: Memory leak fix in mutating & validating webhooks
  pkg/admission/mutatingwebhook/plugin.go
  pkg/admission/validatingwebhook/plugin.go
Labels: approved, lgtm, kind/api-change, size/M, release-note, dco-signoff: yes

#3023 :bug: Fix frontproxy
  pkg/proxy/options/authentication.go
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#2994 📖 docs: generate list of carry commits for rebasing
  docs/content/developers/commit-tag.png
  docs/content/developers/rebasing-kubernetes.md
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes

#3031 🌱 Bump Go Dependencies
  go.mod
  go.sum
Labels: approved, lgtm, tide/merge-method-squash, size/XL, dco-signoff: yes, release-note-none

#3024 :seedling: Add metrics-viewer 'battery'
  config/root-phase0/metrics-cluster-role-binding.yaml
  config/root-phase0/metrics-cluster-role.yaml
  config/root-phase0/metrics-service-account-secret.yaml
  config/root-phase0/metrics-service-account.yaml
  pkg/server/options/batteries/batteries.go
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes

#3030 ✨ tag container images with branch name, too
  hack/build-image.sh
Labels: approved, lgtm, size/S, release-note, dco-signoff: yes

#2958 :bug: logicalcluster-deletion: skip bound resources
  pkg/reconciler/core/logicalclusterdeletion/deletion/logicalcluster_resource_deletor.go
  pkg/reconciler/core/logicalclusterdeletion/deletion/logicalcluster_resource_deletor_test.go
  pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
  pkg/server/controllers.go
Labels: approved, lgtm, size/M, dco-signoff: yes

#3032 🌱 update SDK Go dependencies to match main go.mod
  sdk/apis/test/cel.go
  sdk/go.mod
  sdk/go.sum
Labels: approved, lgtm, size/XL, dco-signoff: yes, release-note-none

#3036 :seedling: Add owner aliases to API approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#3035 :seedling: Make LogicalCluster claimable
  config/crds/apis.kcp.io_apibindings.yaml
  config/crds/apis.kcp.io_apiexports.yaml
  pkg/informer/informer.go
  pkg/informer/informer_test.go
  pkg/server/scheme/scheme.go
  pkg/virtual/apiexport/schemas/builtin/builtin.go
  sdk/apis/apis/v1alpha1/types_apiexport.go
  sdk/apis/apis/v1alpha1/types_apiexport_test.go
  sdk/apis/core/install/install.go
  test/e2e/apibinding/apibinding_logicalcluster_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm, kind/api-change, size/L, release-note, dco-signoff: yes
