Repository kcp-dev/kcp, pull requests merged in 2023-11, with the labels that each got.

#3042 :bug: Be aware of sharding in APIBinding tests for LogicalCluster
  cmd/sharded-test-server/cache.go
  test/e2e/apibinding/apibinding_logicalcluster_test.go
  test/e2e/framework/util.go
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes

#3041 :sparkles: Add `admin` battery to kcp server and enable it by default
  pkg/server/config.go
  pkg/server/options/batteries/batteries.go
  pkg/server/options/options.go
  pkg/server/server.go
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes

#3046 🐛 Fix container image tags for tagged kcp releases
  hack/build-image.sh
Labels: approved, lgtm, size/M, dco-signoff: yes, release-note-none

#3048 :sparkles: Add basic badges
  README.md
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes
