Repository kcp-dev/kcp, pull requests merged in 2023-03, with the labels that each got.

#2852 📖 docs: simplify i18n
  .github/workflows/docs-gen-and-push.yaml
  .gitignore
  Makefile
  Makefile.venv
  docs/.gitignore
  docs/config/en/mkdocs.yml
  docs/content/.pages
  docs/content/CONTRIBUTING.md
  docs/content/GOALS.md
  docs/content/concepts/apis-in-kcp.md
  docs/content/concepts/authorization.md
  docs/content/concepts/cache-server.md
  docs/content/concepts/cluster-mapper.md
  docs/content/concepts/images/kubectl-api-resources.png
  docs/content/concepts/images/scheduling-state-machine.svg
  docs/content/concepts/index.md
  docs/content/concepts/kubectl-kcp-plugin.md
  docs/content/concepts/locations-and-scheduling.md
  docs/content/concepts/partitions.md
  docs/content/concepts/quickstart-tenancy-and-apis.md
  docs/content/concepts/storage.md
  docs/content/concepts/syncer.md
  docs/content/concepts/virtual-workspaces.md
  docs/content/concepts/workspaces.md
  docs/content/developers/github_summary.png
  docs/content/developers/index.md
  docs/content/developers/inspecting-e2e-metrics.md
  docs/content/developers/promecieus.png
  docs/content/developers/prow_link.png
  docs/content/developers/publishing-a-new-kcp-release.md
  docs/content/developers/replicate-new-resource.md
  docs/content/developers/using-kcp-as-a-library.md
  docs/content/developers/writing-kcp-aware-controllers.md
  docs/content/index.md
  docs/content/investigations/index.md
  docs/content/investigations/logical-clusters.md
  docs/content/investigations/minimal-api-server.md
  docs/content/investigations/self-service-policy.md
  docs/content/investigations/transparent-multi-cluster.md
  docs/content/reference/.gitignore
  docs/content/reference/.pages
  docs/generated/.gitignore
  docs/generated/branch/.gitignore
  docs/generated/branch/index.html
  docs/main.py
  docs/mkdocs.yml
  docs/overrides/partials/header.html
  docs/requirements.txt
  hack/build-docs.sh
  hack/deploy-docs.sh
  hack/generate/crd-ref/run-crd-ref-gen.sh
  hack/serve-docs.sh
  hack/verify-go-versions.sh
Labels: approved, lgtm

#2853 🌱 Fix docs
  .github/workflows/docs-gen-and-push.yaml
  docs/.gitignore
  docs/Dockerfile
  docs/content/developers/inspecting-e2e-metrics.md
Labels: approved, lgtm

#2854 🌱 docs: fix venv
  .github/workflows/docs-gen-and-push.yaml
  Makefile
  hack/deploy-docs.sh
  hack/serve-docs.sh
Labels: approved, lgtm

#2856 🌱 [0.11] backport docs i18n fix
  .github/workflows/docs-gen-and-push.yaml
  .gitignore
  Makefile
  Makefile.venv
  docs/.gitignore
  docs/Dockerfile
  docs/config/en/mkdocs.yml
  docs/content/.pages
  docs/content/CONTRIBUTING.md
  docs/content/GOALS.md
  docs/content/concepts/apis-in-kcp.md
  docs/content/concepts/authorization.md
  docs/content/concepts/cache-server.md
  docs/content/concepts/cluster-mapper.md
  docs/content/concepts/images/kubectl-api-resources.png
  docs/content/concepts/images/scheduling-state-machine.svg
  docs/content/concepts/index.md
  docs/content/concepts/kubectl-kcp-plugin.md
  docs/content/concepts/locations-and-scheduling.md
  docs/content/concepts/partitions.md
  docs/content/concepts/quickstart-tenancy-and-apis.md
  docs/content/concepts/storage.md
  docs/content/concepts/syncer.md
  docs/content/concepts/virtual-workspaces.md
  docs/content/concepts/workspaces.md
  docs/content/developers/index.md
  docs/content/developers/publishing-a-new-kcp-release.md
  docs/content/developers/replicate-new-resource.md
  docs/content/developers/using-kcp-as-a-library.md
  docs/content/developers/writing-kcp-aware-controllers.md
  docs/content/index.md
  docs/content/investigations/index.md
  docs/content/investigations/logical-clusters.md
  docs/content/investigations/minimal-api-server.md
  docs/content/investigations/self-service-policy.md
  docs/content/investigations/transparent-multi-cluster.md
  docs/content/reference/.gitignore
  docs/content/reference/.pages
  docs/generated/.gitignore
  docs/generated/branch/.gitignore
  docs/generated/branch/index.html
  docs/main.py
  docs/mkdocs.yml
  docs/overrides/partials/header.html
  docs/requirements.txt
  hack/build-docs.sh
  hack/deploy-docs.sh
  hack/generate/crd-ref/run-crd-ref-gen.sh
  hack/serve-docs.sh
  hack/verify-go-versions.sh
Labels: approved, lgtm

#2859 🌱 [0.11] docs: only build main+release branches
  .github/workflows/docs-gen-and-push.yaml
Labels: approved, lgtm

#2860 🌱 docs: only build main+release branches
  .github/workflows/docs-gen-and-push.yaml
Labels: approved, lgtm

#2858 🌱 0.10 - docs: redo i18n
  .github/workflows/docs-gen-and-push.yaml
  .gitignore
  Makefile
  Makefile.venv
  docs/.gitignore
  docs/Dockerfile
  docs/config/en/mkdocs.yml
  docs/content/.pages
  docs/content/CONTRIBUTING.md
  docs/content/GOALS.md
  docs/content/concepts/authorization.md
  docs/content/concepts/cache-server.md
  docs/content/concepts/cluster-mapper.md
  docs/content/concepts/images/kubectl-api-resources.png
  docs/content/concepts/images/scheduling-state-machine.svg
  docs/content/concepts/index.md
  docs/content/concepts/kubectl-kcp-plugin.md
  docs/content/concepts/locations-and-scheduling.md
  docs/content/concepts/quickstart-tenancy-and-apis.md
  docs/content/concepts/storage.md
  docs/content/concepts/syncer.md
  docs/content/concepts/virtual-workspaces.md
  docs/content/concepts/workspaces.md
  docs/content/developers/.pages
  docs/content/developers/controllers.md
  docs/content/developers/index.md
  docs/content/developers/library-usage.md
  docs/content/developers/releasing.md
  docs/content/index.md
  docs/content/investigations/index.md
  docs/content/investigations/logical-clusters.md
  docs/content/investigations/minimal-api-server.md
  docs/content/investigations/self-service-policy.md
  docs/content/investigations/transparent-multi-cluster.md
  docs/content/reference/.gitignore
  docs/content/reference/.pages
  docs/generated/.gitignore
  docs/generated/branch/.gitignore
  docs/generated/branch/index.html
  docs/main.py
  docs/mkdocs.yml
  docs/overrides/partials/header.html
  docs/overrides/partials/section-overview.html
  docs/requirements.txt
  hack/build-docs.sh
  hack/deploy-docs.sh
  hack/generate/crd-ref/run-crd-ref-gen.sh
  hack/serve-docs.sh
  hack/verify-go-versions.sh
Labels: approved, lgtm

#2862 :book: Fix link to partitions.md
  docs/content/concepts/quickstart-tenancy-and-apis.md
Labels: approved, lgtm, ok-to-test

#2861 🌱 docs: test builds for PRs, update material version
  .github/workflows/docs-gen-and-push.yaml
  docs/requirements.txt
  hack/deploy-docs.sh
Labels: approved, lgtm

#840 ✨ Add a flag to crd-puller to specify only the required CRDs that needs to be synced
  cmd/crd-puller/pull-crds.go
Labels: area/transparent-multi-cluster, approved, lgtm

#2864 📖 docs: add APIConversions to API ref
  .github/workflows/docs-gen-and-push.yaml
  Makefile
  docs/generators/cli-doc/gen-cli-doc.go
  docs/generators/crd-ref/config.yaml
  docs/generators/crd-ref/crd.template.md
  docs/generators/crd-ref/run-crd-ref-gen.sh
Labels: approved, lgtm

#2846 🐛 Fix the spec.URL in workspace using canonicalPath
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling_test.go
  test/e2e/reconciler/workspace/controller_test.go
Labels: approved, lgtm

#2866 🌱 minor docs improvements
  .github/workflows/docs-gen-and-push.yaml
  Makefile
  docs/content/concepts/apis-in-kcp.md
  docs/content/concepts/authorization.md
  docs/content/concepts/cluster-mapper.md
  docs/content/concepts/index.md
  docs/content/concepts/kubectl-kcp-plugin.md
  docs/content/concepts/partitions.md
  docs/content/concepts/placement-locations-and-scheduling.md
  docs/content/concepts/quickstart-tenancy-and-apis.md
  docs/content/concepts/registering-kubernetes-clusters-using-syncer.md
  docs/content/concepts/storage.md
  docs/content/concepts/terminology.md
  docs/content/concepts/workspaces.md
  docs/content/developers/inspecting-e2e-metrics.md
  docs/content/developers/publishing-a-new-kcp-release.md
  docs/content/developers/replicate-new-resource.md
  docs/content/developers/using-kcp-as-a-library.md
  docs/content/developers/writing-kcp-aware-controllers.md
  docs/content/index.md
  docs/scripts/deploy-docs.sh
  docs/scripts/serve-docs.sh
Labels: approved, lgtm

#2868 :seedling: adding logs to investigate E2E flake
  test/e2e/reconciler/partitionset/partitionset_test.go
Labels: approved, lgtm

#2851 :sparkles: Add Ready column to `APIBinding` and `APIExport`
  config/crds/apis.kcp.io_apibindings.yaml
  config/crds/apis.kcp.io_apiexports.yaml
  pkg/apis/apis/v1alpha1/types_apibinding.go
  pkg/apis/apis/v1alpha1/types_apiexport.go
Labels: approved, lgtm, kind/api-change

#2691 :seedling: Simplify heartbeat controller
  pkg/reconciler/workload/basecontroller/controller.go
  pkg/reconciler/workload/heartbeat/heartbeat_controller.go
  pkg/reconciler/workload/heartbeat/heartbeat_reconciler.go
  pkg/reconciler/workload/heartbeat/heartbeat_reconciler_test.go
  tmc/pkg/server/controllers.go
Labels: approved, lgtm

#2875 🌱 Move enhancements to separate repo
  docs/enhancements/0001_project_enhancements.md
Labels: approved, lgtm

#2819 🌱 Tunnel: Validate namespace/pod at the syncer side
  pkg/syncer/syncer.go
  pkg/syncer/tunneler.go
  pkg/syncer/tunneler_test.go
  pkg/tunneler/podsubresourceproxy_handler.go
  test/e2e/framework/syncer.go
  test/e2e/syncer/tunnels_test.go
Labels: approved, lgtm

#2881 ✨ Enable the SyncerTunnel featuregate by default
  pkg/features/kcp_features.go
  test/e2e/syncer/tunnels_test.go
Labels: approved, lgtm

#2829 ✨ Upsync Endpoints of synced services
  config/rootcompute/kube-1.24/apiexport-kubernetes.k8s.io.yaml
  config/rootcompute/kube-1.24/apiresourceschema_endpoints.yaml
  config/rootcompute/kube-1.24/clusterrole-kubernetes-maximal-permission-policy.yaml
  pkg/apis/workload/v1alpha1/types.go
  pkg/reconciler/workload/apiexport/workload_apiexport_reconcile.go
  pkg/syncer/endpoints/endpoint_downstream_controller.go
  pkg/syncer/endpoints/endpoint_downstream_process.go
  pkg/syncer/endpoints/endpoint_downstream_process_test.go
  pkg/syncer/status/status_controller.go
  pkg/syncer/syncer.go
  pkg/virtual/syncer/builder/build.go
  test/e2e/reconciler/locationworkspace/rootcompute_test.go
  test/e2e/syncer/endpoints/deployment-with-upsync.yaml
  test/e2e/syncer/endpoints/deployment-without-upsync.yaml
  test/e2e/syncer/endpoints/embed.go
  test/e2e/syncer/endpoints/endpoints_test.go
  test/e2e/syncer/endpoints/service-with-upsync.yaml
  test/e2e/syncer/endpoints/service-without-upsync.yaml
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm, kind/api-change

#2867 📖 docs: add rest access patterns, etcd storage path
  docs/content/concepts/rest-access-patterns.md
  docs/content/developers/etcd-structure.md
Labels: approved, lgtm

#2873 🌱 shard controller: use committer
  pkg/reconciler/core/shard/shard_controller.go
Labels: approved, lgtm

#2884 🌱 docs: make PromeCIeus a link
  docs/content/developers/inspecting-e2e-metrics.md
Labels: approved, lgtm

#2836 🌱 tmc: split apart virtual workspaces
  cmd/kcp/options/options.go
  cmd/virtual-workspaces/command/cmd.go
  cmd/virtual-workspaces/options/options.go
  pkg/reconciler/workload/synctarget/synctarget_reconcile.go
  pkg/server/config.go
  pkg/server/server.go
  pkg/server/virtual.go
  pkg/virtual/framework/authorization/authorizer.go
  pkg/virtual/framework/rootapiserver/config.go
  pkg/virtual/framework/rootapiserver/health.go
  pkg/virtual/framework/rootapiserver/root_apiserver.go
  pkg/virtual/framework/rootapiserver/server.go
  pkg/virtual/options/authorization.go
  pkg/virtual/options/options.go
  tmc/pkg/coordination/helpers.go
  tmc/pkg/server/config.go
  tmc/pkg/server/options/controllers.go
  tmc/pkg/server/options/options.go
  tmc/pkg/virtual/options/options.go
  tmc/pkg/virtual/syncer/builder/build.go
  tmc/pkg/virtual/syncer/builder/forwarding.go
  tmc/pkg/virtual/syncer/builder/template.go
  tmc/pkg/virtual/syncer/context/keys.go
  tmc/pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_controller.go
  tmc/pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_indexes.go
  tmc/pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
  tmc/pkg/virtual/syncer/doc.go
  tmc/pkg/virtual/syncer/options/options.go
  tmc/pkg/virtual/syncer/schemas/builtin/builtin.go
  tmc/pkg/virtual/syncer/schemas/builtin/builtin_test.go
  tmc/pkg/virtual/syncer/transformations/defaultsummarizing.go
  tmc/pkg/virtual/syncer/transformations/helpers.go
  tmc/pkg/virtual/syncer/transformations/specdiff.go
  tmc/pkg/virtual/syncer/transformations/transformer.go
  tmc/pkg/virtual/syncer/transformations/transformer_test.go
  tmc/pkg/virtual/syncer/transformations/types.go
  tmc/pkg/virtual/syncer/upsyncer/storage_wrapper.go
  tmc/pkg/virtual/syncer/upsyncer/transformer.go
Labels: approved, lgtm

#2888 :seedling: rename ClusterWorkspace to Workspace
  config/crds/tenancy.kcp.io_workspacetypes.yaml
  config/root-phase0/apiexport-tenancy.kcp.io.yaml
  config/root-phase0/apiresourceschema-workspacetypes.tenancy.kcp.io.yaml
  pkg/apis/tenancy/v1alpha1/types_workspacetype.go
  pkg/openapi/zz_generated.openapi.go
Labels: approved, lgtm, kind/api-change

#2890 :bug: tunneler: return retry-after when dialer not ready
  pkg/tunneler/podsubresourceproxy_handler.go
Labels: approved, lgtm

#2897 :bug: Disable default apiserver timeout (60s) for Syncer tunnel connection
  pkg/server/config.go
Labels: approved, lgtm

#2901 📖 Fix obsolete wording
  docs/content/concepts/placement-locations-and-scheduling.md
Labels: approved, lgtm

#2903 🌱 pkg/authorization/maxpermpolicy: add delegation reason
  pkg/authorization/maximal_permission_policy_authorizer.go
Labels: approved, lgtm

#2882 :bug: Decouple internal and external logical-cluster-admin access
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/main.go
  cmd/sharded-test-server/shard.go
  pkg/admission/logicalcluster/admission.go
  pkg/admission/logicalcluster/admission_test.go
  pkg/authorization/bootstrap/policy.go
  pkg/authorization/requiredgroups_authorizer.go
  pkg/authorization/requiredgroups_authorizer_test.go
  pkg/proxy/options/authentication.go
  pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
  pkg/reconciler/tenancy/workspace/workspace_controller.go
  pkg/server/config.go
  pkg/server/controllers.go
  pkg/server/options/options.go
  pkg/server/server.go
Labels: approved, lgtm, kind/api-change

#2902 📖 Update Placement, Locations, and Scheduling doc
  docs/content/concepts/placement-locations-and-scheduling.md
Labels: approved, lgtm

#2907 :bug: fix(CLI): sync command should honor provided IO streams
  pkg/cliplugins/workload/plugin/sync.go
Labels: approved, lgtm

#2927 🌱 fix some typos in the syncer documentation
  docs/content/concepts/registering-kubernetes-clusters-using-syncer.md
Labels: approved, lgtm

#2908 🌱 TMC E2E tests sharding support - step 1
  pkg/reconciler/workload/synctarget/synctarget_reconcile.go
  pkg/reconciler/workload/synctarget/synctarget_reconcile_test.go
  test/e2e/framework/kcp.go
  test/e2e/framework/syncer.go
  test/e2e/reconciler/deployment/deployment_coordinator_test.go
  test/e2e/reconciler/scheduling/upsynced_scheduling_test.go
  test/e2e/syncer/tunnels_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#2877 🐛 Remove root:compute deps in controller
  config/crds/workload.kcp.io_synctargets.yaml
  config/root-phase0/apiexport-workload.kcp.io.yaml
  config/root-phase0/apiresourceschema-synctargets.workload.kcp.io.yaml
  docs/content/concepts/registering-kubernetes-clusters-using-syncer.md
  pkg/cliplugins/workload/plugin/sync.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/workload/apiexport/apiresourceschema.go
  pkg/reconciler/workload/apiexport/workload_apiexport_controller.go
  pkg/reconciler/workload/apiexport/workload_apiexport_reconcile.go
  pkg/reconciler/workload/apiexport/workload_apiexport_reconcile_test.go
  pkg/reconciler/workload/defaultlocation/defaultlocation_controller.go
  pkg/reconciler/workload/synctargetexports/synctarget_indexes.go
  pkg/virtual/framework/internalapis/fixtures/synctargets.yaml
  sdk/apis/workload/v1alpha1/synctarget_types.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/locationworkspace/local_apiexport_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/reconciler/scheduling/upsynced_scheduling_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
  tmc/pkg/server/controllers.go
  tmc/pkg/server/server.go
  tmc/pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_indexes.go
Labels: area/transparent-multi-cluster, approved, lgtm, kind/api-change

#2915 🌱 Add cache informers for synctargets/locations in placement controller
  pkg/reconciler/workload/placement/placement_controller.go
  pkg/reconciler/workload/placement/placement_reconcile.go
  pkg/reconciler/workload/placement/placement_reconcile_scheduling.go
  pkg/reconciler/workload/placement/placement_reconcile_scheduling_test.go
  tmc/pkg/server/controllers.go
Labels: approved, lgtm

#2925 :book: Document data types that are replicated
  docs/content/CONTRIBUTING.md
Labels: approved, lgtm

#2934 🐛 Cleanup tmc e2e tests to remove data races
  test/e2e/reconciler/scheduling/upsynced_scheduling_test.go
  test/e2e/syncer/tunnels_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#2874 🌱 Switch workload/namespace controller to use committer
  pkg/reconciler/workload/namespace/namespace_controller.go
  pkg/reconciler/workload/namespace/namespace_reconcile.go
  pkg/reconciler/workload/namespace/namespace_reconcile_placementbind.go
  pkg/reconciler/workload/namespace/namespace_reconcile_placementbind_test.go
  pkg/reconciler/workload/namespace/namespace_reconcile_scheduling.go
  pkg/reconciler/workload/namespace/namespace_reconcile_scheduling_test.go
  pkg/reconciler/workload/namespace/namespace_reconcile_status.go
  pkg/reconciler/workload/namespace/namespace_reconcile_status_test.go
  sdk/apis/scheduling/v1alpha1/types_location.go
Labels: area/transparent-multi-cluster, approved, lgtm, kind/api-change
