Repository kcp-dev/kcp, pull requests merged in 2023-12, with the labels that each got.

#3056 :sparkles: Simplify index pkg
  pkg/index/index.go
  pkg/index/index_test.go
  pkg/proxy/index/index_controller.go
  pkg/server/localproxy.go
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes

#3060 :bug: Fix metrics battery
  config/root/metrics-1-cluster-role.yaml
  config/root/metrics-2-service-account.yaml
  config/root/metrics-3-cluster-role-binding.yaml
  config/root/metrics-4-service-account-secret.yaml
  pkg/server/options/options.go
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#3064 :sparkles: Add 'metrics-viewer' user to ClusterRoleBinding in `metrics-viewer` battery
  config/root/metrics-3-cluster-role-binding.yaml
  pkg/server/options/options.go
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#3057 :sparkles: Experimental mounts API
  Makefile
  config/root-phase0/apiexport-tenancy.kcp.io.yaml
  config/root-phase0/apiresourceschema-workspaces.tenancy.kcp.io.yaml
  pkg/index/index.go
  pkg/index/index_test.go
  pkg/metadata/dynamic.go
  pkg/openapi/zz_generated.openapi.go
  pkg/proxy/index/index_controller.go
  pkg/server/localproxy.go
  sdk/apis/tenancy/register.go
  sdk/apis/tenancy/v1alpha1/types_mounts.go
  sdk/apis/tenancy/v1alpha1/types_mounts_test.go
  sdk/apis/tenancy/v1alpha1/types_workspace.go
  sdk/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  sdk/client/applyconfiguration/tenancy/v1alpha1/mountstatus.go
Labels: approved, lgtm, kind/api-change, size/L, release-note, dco-signoff: yes

#3066 :book: Fix commit function signature name order
  pkg/reconciler/cache/labelclusterrolebindings/labelclusterrolebinding_controller.go
  pkg/reconciler/cache/labelclusterroles/labelclusterrole_controller.go
  pkg/reconciler/core/logicalcluster/logicalcluster_controller.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
  pkg/reconciler/tenancy/workspace/workspace_controller.go
Labels: approved, lgtm, size/S, release-note, dco-signoff: yes
