Repository kcp-dev/kcp, pull requests merged in 2023-02, with the labels that each got.

#2724 :bug: Fix typo breaking codegen: crds not stored at the right location
  config/crds/core.kcp.io_logicalclusters.yaml
  config/root-phase0/apiresourceschema-logicalclusters.core.kcp.io.yaml
  hack/update-codegen-crds.sh
Labels: approved, lgtm, kind/api-change

#2717 🌱 Trying to fix doc generation
  .github/workflows/docs-gen-and-push.yaml
  hack/generate/crd-ref/run-crd-ref-gen.sh
Labels: approved, lgtm

#2688 🐛 Deflake quota e2e
  test/e2e/quota/quota_test.go
Labels: approved, lgtm

#2712 :bug: Fix Makefile clean target and add .kcp cleanup
  Makefile
Labels: approved, lgtm

#2695 🐛 Fix API binding privilege escalation
  pkg/virtual/apiexport/builder/build.go
  pkg/virtual/apiexport/builder/forwarding.go
  pkg/virtual/apiexport/options/options.go
  pkg/virtual/framework/forwardingregistry/rest.go
  pkg/virtual/framework/forwardingregistry/rest_test.go
  pkg/virtual/framework/forwardingregistry/store.go
  pkg/virtual/initializingworkspaces/builder/forwarding.go
  pkg/virtual/syncer/builder/forwarding.go
  test/e2e/virtual/apiexport/authorizer_test.go
  test/e2e/virtual/apiexport/binding_test.go
Labels: approved, lgtm

#2707 🌱 remove deprecated home workspaces fields, add waiting for unmanaged servers in e2e
  Makefile
  cmd/sharded-test-server/main.go
  cmd/test-server/main.go
  config/root/bootstrap.go
  go.mod
  pkg/server/config.go
  pkg/server/home_workspaces.go
  pkg/server/options/flags.go
  pkg/server/options/homeworkspaces.go
  pkg/server/server.go
  test/e2e/framework/accessory.go
  test/e2e/framework/kcp.go
  test/e2e/homeworkspaces/home_workspaces_test.go
  test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
  test/e2e/virtual/apiexport/authorizer_test.go
Labels: approved, lgtm

#2703 :seedling: test/e2e: DRY up waiting on conditions
  test/e2e/apibinding/apibinding_deletion_test.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
  test/e2e/apibinding/apibinding_protected_test.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/conversion/conversion_test.go
  test/e2e/fixtures/apifixtures/apibinding.go
  test/e2e/framework/util.go
  test/e2e/garbagecollector/garbagecollector_test.go
  test/e2e/quota/quota_test.go
  test/e2e/reconciler/apiexport/apiexport_controller_test.go
  test/e2e/reconciler/locationworkspace/local_apiexport_test.go
  test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
  test/e2e/reconciler/locationworkspace/synctarget_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/api_compatibility_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/reconciler/workspace/controller_test.go
  test/e2e/reconciler/workspacedeletion/controller_test.go
  test/e2e/virtual/apiexport/authorizer_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm

#2735 🌱 More APIExport VW e2e deflaking
  test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
  test/e2e/virtual/apiexport/authorizer_test.go
Labels: approved, lgtm

#2736 🌱 Fix ready-to-test location
  Makefile
  cmd/sharded-test-server/main.go
  cmd/test-server/main.go
Labels: approved, lgtm

#2728 :seedling: Dockerfile: remove SHELL for OCI compliance
  Dockerfile
Labels: approved, lgtm

#2734 🌱 Add make target to download e2e logs from Prow
  Makefile
  hack/download-e2e-logs.sh
Labels: approved, lgtm

#2745 🌱 Use a private kcp per disruptive replication test
  test/e2e/reconciler/cache/replication_test.go
Labels: approved, lgtm

#2746 🐛 cmd/sharded-test-server: Reuse Certificates instead of generating new ones
  cmd/sharded-test-server/main.go
Labels: approved, lgtm

#2725 📖 document replicating a new resource
  docs/content/en/main/concepts/developers/replicate-new-resource.md
Labels: approved, lgtm

#2749 :book: Fix unknown flag --apiexport
  docs/content/en/main/concepts/syncer.md
Labels: approved, lgtm

#2722 :book: Brush up TMC quickstart
  README.md
Labels: approved, lgtm

#2731 🐛 Drop non-existent workspace get command from help output
  pkg/cliplugins/workspace/cmd/cmd.go
Labels: approved, lgtm

#2752 🐛 Fix frontmatter on replicating new resource doc
  docs/content/en/main/concepts/developers/replicate-new-resource.md
Labels: approved, lgtm

#2753 🌱 Small improvements to dev workflow
  .gitignore
  Makefile
Labels: approved, lgtm, ok-to-test

#2417 ✨ Add pods resource to the default Kubernetes APIExport
  config/rootcompute/kube-1.24/apiexport-kubernetes.k8s.io.yaml
  config/rootcompute/kube-1.24/apiresourceschema_pods.yaml
  config/rootcompute/kube-1.24/bootstrap.go
  config/rootcompute/kube-1.24/clusterrole-kubernetes-maximal-permission-policy.yaml
  pkg/cliplugins/workload/plugin/sync.go
  pkg/reconciler/workload/apiexport/workload_apiexport_reconcile.go
  pkg/syncer/resourcesync/controller.go
  pkg/syncer/syncer.go
  pkg/virtual/syncer/builder/build.go
  test/e2e/fixtures/kube/core.k8s.io_pods.yaml
  test/e2e/framework/kcp.go
  test/e2e/reconciler/locationworkspace/rootcompute_test.go
  test/e2e/syncer/tunnels_test.go
Labels: area/transparent-multi-cluster, approved, lgtm

#2730 🌱 tmc e2e : Split SyncerFixture
  pkg/syncer/syncer.go
  test/e2e/framework/syncer.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/deployment/deployment_coordinator_test.go
  test/e2e/reconciler/locationworkspace/local_apiexport_test.go
  test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
  test/e2e/reconciler/locationworkspace/rootcompute_test.go
  test/e2e/reconciler/locationworkspace/synctarget_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/api_compatibility_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/syncer/dns/dns_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/syncer/tunnels_test.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#2533 :bug: workload/resource: handle upsynced resources
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/reconciler/workload/resource/resource_reconcile.go
  test/e2e/framework/syncer.go
  test/e2e/reconciler/scheduling/upsynced_scheduling_test.go
Labels: area/transparent-multi-cluster, approved, lgtm

#2755 :bug: E2E failing on APIExportEndpointSlice creation (flake)
  test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
Labels: approved, lgtm

#2513 :sparkles: Partitionset reconciliation
  config/crds/topology.kcp.io_partitionsets.yaml
  config/crds/topology.kcp.io_partitionsets.yaml-patch
  config/root-phase0/apiexport-topology.kcp.io.yaml
  config/root-phase0/apiresourceschema-partitionsets.topology.kcp.io.yaml
  pkg/apis/topology/v1alpha1/types_partitionset.go
  pkg/apis/topology/v1alpha1/zz_generated.deepcopy.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/topology/partitionset/partitioning_test.go
  pkg/reconciler/topology/partitionset/partitionset_controller.go
  pkg/reconciler/topology/partitionset/partitionset_controller_test.go
  pkg/reconciler/topology/partitionset/partitionset_indexes.go
  pkg/reconciler/topology/partitionset/partitionset_reconcile.go
  pkg/reconciler/topology/partitionset/resources.go
  pkg/server/controllers.go
  pkg/server/server.go
Labels: approved, lgtm, kind/api-change

#2761 :bug: test/e2e/scheduling: don't require kind for upsynced test
  test/e2e/reconciler/scheduling/upsynced_scheduling_test.go
Labels: approved, lgtm

#2760 🐛 Fix make install doesn't exit without required tools
  Makefile
Labels: approved, lgtm, ok-to-test

#2765 🐛 Fix TMC flake in the Upsyncer VW e2e test
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#2747 🌱 /pkg/proxy/server: handle /readyz and /livez outside of the auth chain
  pkg/proxy/mapping.go
  pkg/proxy/server.go
Labels: approved, lgtm

#2766 🐛 pkg/tunneler: remove non-error verbose log
  pkg/tunneler/podsubresourceproxy_handler.go
Labels: approved, lgtm

#2767 🐛 tmc e2e: fix Syncer virtual workspace e2e test flakes
  test/e2e/framework/kcp.go
  test/e2e/virtual/syncer/virtualworkspace_test.go
Labels: approved, lgtm

#2716 🌱 manifest: remove outdated manifests
  manifest/OWNERS
  manifest/etcd.yaml
  manifest/issuer.yaml
  manifest/kcp-front-proxy.yaml
  manifest/kcp.yaml
  manifest/kustomization.yaml
Labels: approved, lgtm

#2423 :sparkles: Adding DNS network policies
  pkg/cliplugins/workload/plugin/sync_test.go
  pkg/cliplugins/workload/plugin/syncer.yaml
  pkg/syncer/shared/helpers.go
  pkg/syncer/shared/namespace.go
  pkg/syncer/spec/dns/dns_process.go
  pkg/syncer/spec/dns/dns_process_test.go
  pkg/syncer/spec/dns/networkpolicy_dns.yaml
  pkg/syncer/spec/dns/resources.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/syncer.go
  test/e2e/fixtures/kube/networking.k8s.io_networkpolicies.yaml
  test/e2e/framework/kcp.go
  test/e2e/syncer/dns/dns_test.go
Labels: area/transparent-multi-cluster, approved, lgtm

#2624 🐛 Enqueue location upon synctarget update
  pkg/reconciler/workload/placement/placement_controller.go
Labels: area/transparent-multi-cluster, approved, lgtm

#2779 🐛 bind compute: handle placement already exists correctly
  pkg/cliplugins/bind/plugin/bind_compute.go
Labels: approved, lgtm

#2751 🐛Fix multiple CRDs/workspaces/versions
  go.mod
  go.sum
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_reconcile.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/server/controllers.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/status/status_process_test.go
  test/e2e/authorizer/workspace_test.go
  test/e2e/conformance/crd_partial_metadata_test.go
Labels: approved, lgtm

#2764 🐛 Prevent gc/quota workqueue backlogs
  pkg/reconciler/garbagecollector/garbagecollector_controller.go
  pkg/reconciler/kubequota/kubequota_controller.go
Labels: approved, lgtm

#2780 🌱 syncer vw: add API definition logging
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_controller.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_indexes.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
Labels: approved, lgtm

#2744 🌱 Make syncer vw global
  Makefile
  pkg/reconciler/cache/replication/replication_controller.go
  pkg/virtual/options/options.go
  pkg/virtual/syncer/builder/build.go
  pkg/virtual/syncer/builder/template.go
  pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_controller.go
  pkg/virtual/syncer/options/options.go
Labels: approved, lgtm

#2788 📖 docs: enable manual action triggering
  .github/workflows/ci-docs-only.yaml
  .github/workflows/ci.yaml
  .github/workflows/docs-gen-and-push.yaml
  .github/workflows/kcp-image.yaml
Labels: approved

#2792 🌱 docs: fix pip install
  .github/workflows/docs-gen-and-push.yaml
Labels: approved

#2796 📖 Fix contributing link
  README.md
Labels: approved, lgtm

#2801 📖 Update link for investigations directory
  docs/content/en/GOALS.md
Labels: approved, lgtm, ok-to-test

#2214 :sparkles: Add Upsync controller
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/status/status_controller.go
  pkg/syncer/status/status_process.go
  pkg/syncer/syncer.go
  pkg/syncer/upsync/upsync_controller.go
  pkg/syncer/upsync/upsync_process_test.go
  pkg/syncer/upsync/upsync_reconcile.go
  test/e2e/syncer/tunnels_test.go
Labels: area/transparent-multi-cluster, approved, lgtm, kind/api-change

#2806 🌱 fix broken documentation links
  CONTRIBUTING.md
  docs/content/en/CONTRIBUTING.md
  docs/content/en/concepts/syncer.md
  docs/content/en/concepts/virtual-workspaces.md
  docs/content/en/index.md
  hack/deploy-docs.sh
  hack/verify-go-versions.sh
Labels: approved, lgtm

#2808 🌱 docs: document the process
  docs/README.md
  docs/config/en/mkdocs.yml
  docs/mkdocs.yml
Labels: approved, lgtm

#2809 🐛 Only validate the path component of a fully-qualified `APIExport` ref
  pkg/cliplugins/bind/plugin/bind.go
  pkg/cliplugins/bind/plugin/bind_test.go
Labels: approved, lgtm, ok-to-test

#2774 🌱 test/e2e,cmd/test: scrape metrics for test servers and e2e tests
  .github/workflows/ci.yaml
  .gitignore
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/main.go
  cmd/test-server/kcp/shard.go
  cmd/test-server/main.go
  go.mod
  hack/run-with-prometheus.sh
  test/e2e/framework/kcp.go
  test/e2e/framework/util.go
Labels: approved, lgtm

#2784 🐛 Fix location cannot be found by placement during scheduling
  pkg/reconciler/scheduling/placement/placement_controller.go
  pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go
  test/e2e/reconciler/scheduling/controller_test.go
Labels: approved, lgtm

#2782 🌱 workspace_reconcile_scheduling: allow for skipping a shard with a special annotation during scheduling
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling_test.go
Labels: approved, lgtm

#2816 :bug: cli: honor expanded `~` in kcp ws
  pkg/cliplugins/workspace/plugin/kubeconfig.go
Labels: approved, lgtm

#2742 :sparkles: cache: add a synthetic delay to the cache server
  Makefile
  cmd/sharded-test-server/cache.go
  cmd/sharded-test-server/main.go
  pkg/cache/server/config.go
  pkg/cache/server/handler.go
  pkg/cache/server/options/options.go
Labels: approved, lgtm

#2822 🐛 Fix nil pointer error in the Upsyncer reconcile
  pkg/syncer/upsync/upsync_process_test.go
  pkg/syncer/upsync/upsync_reconcile.go
Labels: approved, lgtm

#2814 🌱 Make DirectOrGoRunCommand aware of the deployment-coordinator being moved to tmc/cmd
  test/e2e/framework/kcp.go
Labels: approved, lgtm, ok-to-test

#2823 📖 Generate section overviews
  Makefile
  docs/Dockerfile
  docs/config/en/mkdocs.yml
  docs/content/en/developers/.pages
  docs/content/en/developers/index.md
  docs/content/en/developers/publishing-a-new-kcp-release.md
  docs/content/en/developers/replicate-new-resource.md
  docs/content/en/developers/using-kcp-as-a-library.md
  docs/content/en/developers/writing-kcp-aware-controllers.md
  docs/content/en/investigations/index.md
  docs/overrides/partials/section-overview.html
  docs/requirements.txt
Labels: approved, lgtm

#2825 🌱 docs: actually add main.py module to git
  docs/main.py
Labels: approved, lgtm

#2815 🌱 Add --labels to kubectl kcp workload sync
  pkg/cliplugins/workload/plugin/sync.go
  test/e2e/framework/syncer.go
  test/e2e/reconciler/deployment/deployment_coordinator_test.go
Labels: area/transparent-multi-cluster, approved, lgtm, ok-to-test

#2828 :book: Add initial APIs content
  docs/content/en/concepts/apis-in-kcp.md
Labels: approved, lgtm

#2799 :book: APIExportEndpointSlice and Partition doc
  docs/content/en/concepts/partitions.md
  docs/content/en/concepts/quickstart-tenancy-and-apis.md
Labels: approved, lgtm

#2842 🌱 Remove direct klog usage
  hack/logcheck.out
  pkg/reconciler/cache/labelclusterroles/labelclusterrole_controller.go
Labels: approved, lgtm

#2847 :bug: Add verb `access`to syncer
  pkg/cliplugins/workload/plugin/sync.go
Labels: approved, lgtm

#2845 ✨ Syncer: also mutate `StatefulSet`s and `ReplicaSet`s
  pkg/syncer/spec/mutators/podspecable.go
  pkg/syncer/spec/mutators/podspecable_test.go
  pkg/syncer/spec/mutators/secrets.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/syncer.go
Labels: approved, lgtm

#2840 📖 docs/../developers: describe metrics gathering for e2e tests
  docs/content/en/developers/github_summary.png
  docs/content/en/developers/inspecting-e2e-metrics.md
  docs/content/en/developers/promecieus.png
  docs/content/en/developers/prow_link.png
  hack/run-with-prometheus.sh
Labels: approved, lgtm
