Repository kcp-dev/kcp, pull requests merged in 2023-01, with the labels that each got.

#2536 🐛 kcp: fix waitForOptionalSync method to wait for a proper signal
  pkg/server/controllers.go
Labels: approved, lgtm

#2524 :seedling: :*: use 'logicalCluster' instead of 'this'
  config/root-phase0/bootstrap.go
  pkg/admission/logicalcluster/admission.go
  pkg/admission/logicalcluster/admission_test.go
  pkg/admission/namespacelifecycle/admission.go
  pkg/admission/pathannotation/pathannotation_admission.go
  pkg/admission/workspace/admission.go
  pkg/admission/workspace/admission_test.go
  pkg/admission/workspacetypeexists/admission.go
  pkg/admission/workspacetypeexists/admission_test.go
  pkg/authorization/requiredgroups_authorizer.go
  pkg/index/index.go
  pkg/proxy/index/index_controller.go
  pkg/reconciler/core/logicalcluster/logicalcluster_reconcile.go
  pkg/reconciler/core/logicalcluster/logicalcluster_reconcile_url.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_reconcile.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_phase.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
  pkg/server/home_workspaces.go
  pkg/server/localproxy.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Labels: approved, lgtm, kind/api-change

#2508 :seedling: Update .goreleaser.yaml to build binaries with CGO_ENABLED=0
  .goreleaser.yaml
Labels: approved, lgtm, ok-to-test

#2440 🌱 DDSIF: Make it more generally useful
  hack/logcheck.out
  pkg/informer/informer.go
  pkg/informer/informer_test.go
  pkg/metadata/dynamic.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_controller.go
  pkg/reconciler/garbagecollector/garbagecollector_controller.go
  pkg/reconciler/kubequota/kubequota_controller.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/server/config.go
  pkg/server/controllers.go
  pkg/server/server.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
Labels: approved, lgtm

#2540 :bug: Add missing CGO_ENABLED flag in the install makefile target
  Makefile
Labels: approved, lgtm

#2544 🐛 Docker build/push should not use a matrix
  .github/workflows/kcp-image.yaml
Labels: approved, lgtm

#2549 🐛 cel-go: update to pull in data race fix
  go.mod
  go.sum
Labels: area/kubernetes, approved, lgtm

#2546 🌱 Scope APIBinding logger
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
Labels: area/apiexports, approved, lgtm

#2545 🌱 Skip upsynced resources in resource scheduling
  pkg/reconciler/workload/resource/resource_reconcile.go
Labels: area/transparent-multi-cluster, approved, lgtm

#2487 🌱 Add authorizer test for static endpoints
  test/e2e/authorizer/authorizer_test.go
Labels: approved, lgtm

#2432 :sparkles: APIExportEndpointSlice reconciliation
  cmd/sharded-test-server/main.go
  config/crds/apis.kcp.io_apiexportendpointslices.yaml
  config/crds/apis.kcp.io_apiexports.yaml
  pkg/apis/apis/v1alpha1/types_apiexport.go
  pkg/apis/apis/v1alpha1/types_apiexportendpointslice.go
  pkg/apis/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/cache/server/config.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/reconciler/apis/apiexport/apiexport_reconcile.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_controller.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_controller_test.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_indexes.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_reconcile.go
  pkg/reconciler/cache/replication/replication_reconcile.go
  pkg/reconciler/cache/replication/replication_reconcile_test.go
  pkg/server/config.go
  pkg/server/controllers.go
  pkg/server/options/cache.go
  pkg/server/options/flags.go
  pkg/server/server.go
  test/e2e/apibinding/apibinding_protected_test.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/cache/cache_server_test.go
  test/e2e/reconciler/cache/replication_test.go
  test/e2e/reconciler/deployment/deployment_coordinator_test.go
  test/e2e/virtual/apiexport/authorizer_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm, kind/api-change

#2553 :seedling: follow-ups of workspace refactor
  pkg/authorization/workspace_content_authorizer_test.go
  pkg/cliplugins/bind/plugin/bind.go
  pkg/cliplugins/workload/plugin/sync.go
Labels: approved, lgtm

#2551 :seedling: Cross-compile container image binaries from host platform
  .github/workflows/kcp-image.yaml
  Dockerfile
  hack/verify-go-versions.sh
Labels: approved, lgtm

#2547 ✨ Allow home workspaces to be accessed via `user:<username>`
  pkg/server/home_workspaces.go
  test/e2e/homeworkspaces/home_workspaces_test.go
Labels: area/workspaces, approved, lgtm

#2555 🌱 Debug deployment coordinator e2e
  test/e2e/reconciler/deployment/deployment_coordinator_test.go
Labels: approved, lgtm

#2554 :bug: workspace controller: use loopback client for local shard
  pkg/reconciler/tenancy/workspace/workspace_controller.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile.go
  pkg/server/controllers.go
Labels: approved, lgtm

#2556 :seedling: Switch cel-go to upstream v0.12.6
  go.mod
  go.sum
Labels: approved, lgtm

#2558 🌱 cluster workspace rename
  pkg/admission/kubequota/kubequota_admission.go
  pkg/admission/kubequota/kubequota_clusterworkspace_monitor.go
  pkg/proxy/index/index_controller.go
  pkg/reconciler/garbagecollector/garbagecollector_controller.go
  pkg/reconciler/kubequota/kubequota_controller.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/initializingworkspaces/builder/forwarding.go
Labels: approved, lgtm, kind/api-change

#2564 🐛 Fix APIExport virtual workspace API bug
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller_test.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
Labels: approved, lgtm

#2557 ⚠️ Move Workspace.Status.{Cluster, URL} to Spec
  config/crds/tenancy.kcp.io_workspaces.yaml
  config/root-phase0/apiexport-tenancy.kcp.io.yaml
  config/root-phase0/apiresourceschema-workspaces.tenancy.kcp.io.yaml
  pkg/admission/workspace/admission.go
  pkg/admission/workspace/admission_test.go
  pkg/apis/tenancy/projection/workspaces.go
  pkg/apis/tenancy/v1beta1/types.go
  pkg/apis/tenancy/v1beta1/types_workspace_test.go
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/cliplugins/workspace/plugin/kubeconfig_test.go
  pkg/index/index.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_deletion.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_phase.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling_test.go
  pkg/server/home_workspaces.go
  test/e2e/reconciler/clusterworkspace/controller_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm, kind/api-change

#2559 :sparkles: server: wire cache informers instead of root informers
  cmd/sharded-test-server/cache.go
  pkg/cache/server/bootstrap/bootstrap.go
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/identitycache/api_export_identity_controller.go
  pkg/reconciler/apis/identitycache/api_export_identity_reconcile.go
  pkg/reconciler/apis/identitycache/api_export_identity_reconcile_test.go
  pkg/reconciler/cache/replication/replication_controller.go
  pkg/reconciler/cache/replication/replication_reconcile.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
  pkg/server/bootstrap/identity.go
  pkg/server/config.go
  pkg/server/controllers.go
  pkg/server/server.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/initializingworkspaces/builder/forwarding.go
Labels: approved, lgtm

#2565 🌱 add missing unit tests for the index
  pkg/index/index.go
  pkg/index/index_test.go
Labels: approved, lgtm

#2561 🌱 index controller rename
  pkg/proxy/index/index_controller.go
Labels: approved, lgtm, kind/api-change

#2543 :seedling: *: remove tenancy.kcp.dev/v1alpha1.ClusterWorkspace
  cmd/sharded-test-server/shard.go
  cmd/test-server/kcp/shard.go
  hack/logcheck.out
  pkg/admission/reservednames/admission_test.go
  pkg/admission/workspace/admission_test.go
  pkg/admission/workspacetypeexists/admission.go
  pkg/admission/workspacetypeexists/admission_test.go
  pkg/apis/tenancy/projection/workspaces.go
  pkg/apis/tenancy/v1alpha1/register.go
  pkg/apis/tenancy/v1alpha1/types_clusterworkspace.go
  pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/tenancy/v1beta1/types.go
  pkg/apis/tenancy/v1beta1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/cluster/typed/tenancy/v1alpha1/clusterworkspace.go
  pkg/client/clientset/versioned/cluster/typed/tenancy/v1alpha1/fake/clusterworkspace.go
  pkg/client/clientset/versioned/cluster/typed/tenancy/v1alpha1/fake/tenancy_client.go
  pkg/client/clientset/versioned/cluster/typed/tenancy/v1alpha1/tenancy_client.go
  pkg/client/clientset/versioned/typed/tenancy/v1alpha1/clusterworkspace.go
  pkg/client/clientset/versioned/typed/tenancy/v1alpha1/fake/fake_clusterworkspace.go
  pkg/client/clientset/versioned/typed/tenancy/v1alpha1/fake/fake_tenancy_client.go
  pkg/client/clientset/versioned/typed/tenancy/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/tenancy/v1alpha1/tenancy_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/tenancy/v1alpha1/clusterworkspace.go
  pkg/client/informers/externalversions/tenancy/v1alpha1/interface.go
  pkg/client/listers/tenancy/v1alpha1/clusterworkspace.go
  pkg/client/listers/tenancy/v1alpha1/clusterworkspace_expansion.go
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/cliplugins/workspace/plugin/kubeconfig_test.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling_test.go
  pkg/server/config.go
  pkg/server/controllers.go
  pkg/server/options/authorization.go
  pkg/server/options/flags.go
  pkg/virtual/options/options.go
  pkg/virtual/workspaces/builder/build.go
  pkg/virtual/workspaces/options/options.go
  pkg/virtual/workspaces/printers/printer.go
  pkg/virtual/workspaces/registry/rest.go
  test/e2e/apibinding/maximalpermissionpolicy_authorizer_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/framework/kcp.go
  test/e2e/framework/workspaces.go
  test/e2e/reconciler/cache/replication_test.go
  test/e2e/reconciler/clusterworkspace/apibinding_initializer_test.go
  test/e2e/reconciler/workspacedeletion/controller_test.go
  test/e2e/virtual/clusterworkspaces/virtual_workspace_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/watchcache/watchcache_enabled_test.go
  test/e2e/workspacetype/controller_test.go
Labels: area/workspaces, approved, lgtm, kind/api-change

#2573 🌱 crdcleanup: strongly type enqueue params
  pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
Labels: approved, lgtm

#2574 🌱 vw/apiexport: strongly type enqueue params
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
Labels: approved, lgtm

#2542 🌱 Add e2e DNS tests
  test/e2e/framework/util.go
  test/e2e/reconciler/deployment/deployment_coordinator_test.go
  test/e2e/syncer/dns/dns_test.go
  test/e2e/syncer/dns/workspace1/0-namespace1.yaml
  test/e2e/syncer/dns/workspace1/0-namespace2.yaml
  test/e2e/syncer/dns/workspace1/embed.go
  test/e2e/syncer/dns/workspace1/ping-across-namespace.yaml
  test/e2e/syncer/dns/workspace1/ping-fully-qualified.yaml
  test/e2e/syncer/dns/workspace1/ping-not-qualified.yaml
  test/e2e/syncer/dns/workspace1/service.yaml
  test/e2e/syncer/dns/workspace2/0-namespace.yaml
  test/e2e/syncer/dns/workspace2/embed.go
  test/e2e/syncer/dns/workspace2/ping-fully-qualified-fail.yaml
Labels: area/transparent-multi-cluster, approved, lgtm

#2575 🌱 apiexport: strongly type enqueue params
  pkg/reconciler/apis/apiexport/apiexport_controller.go
Labels: approved, lgtm

#2569 🌱 Rename ClusterWorkspace
  config/crds/tenancy.kcp.io_workspaces.yaml
  config/crds/tenancy.kcp.io_workspacetypes.yaml
  config/root-phase0/apiexport-tenancy.kcp.io.yaml
  config/root-phase0/apiresourceschema-workspaces.tenancy.kcp.io.yaml
  config/root-phase0/apiresourceschema-workspacetypes.tenancy.kcp.io.yaml
  pkg/admission/kubequota/kubequota_admission.go
  pkg/admission/kubequota/kubequota_clusterworkspace_monitor.go
  pkg/admission/logicalcluster/admission.go
  pkg/admission/reservednames/admission_test.go
  pkg/admission/shard/admission.go
  pkg/admission/workspace/admission.go
  pkg/admission/workspacetype/admission.go
  pkg/admission/workspacetypeexists/admission.go
  pkg/apis/core/types.go
  pkg/apis/tenancy/initialization/utils.go
  pkg/apis/tenancy/v1alpha1/types_clusterworkspace.go
  pkg/apis/tenancy/v1alpha1/types_workspacetype.go
  pkg/apis/tenancy/v1beta1/types.go
  pkg/authorization/bootstrap/policy.go
  pkg/cliplugins/bind/plugin/bind.go
  pkg/cliplugins/claims/plugin/claims.go
  pkg/cliplugins/helpers/helpers.go
  pkg/cliplugins/workload/plugin/sync.go
  pkg/cliplugins/workspace/plugin/kubeconfig.go
  pkg/cliplugins/workspace/plugin/kubeconfig_test.go
  pkg/index/index.go
  pkg/openapi/zz_generated.openapi.go
  pkg/proxy/index/index_controller.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go
  pkg/reconciler/core/logicalcluster/logicalcluster_controller.go
  pkg/reconciler/core/logicalclusterdeletion/deletion/logicalcluster_resource_deletor.go
  pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
  pkg/reconciler/kubequota/kubequota_controller.go
  pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_reconcile.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
  pkg/reconciler/tenancy/workspacetype/clusterworkspacetype_controller_reconcile.go
  pkg/reconciler/tenancy/workspacetype/clusterworkspacetype_controller_reconcile_test.go
  pkg/reconciler/workload/apiexportcreate/apiexportcreate_controller.go
  pkg/server/filters/filters_test.go
  pkg/server/options/authentication.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/conformance/webhook_test.go
  test/e2e/framework/workspaces.go
  test/e2e/reconciler/cache/replication_test.go
  test/e2e/reconciler/workspace/apibinding_initializer_test.go
  test/e2e/reconciler/workspace/apiresourceschema_cowboys.yaml
  test/e2e/reconciler/workspace/controller_test.go
  test/e2e/reconciler/workspace/support.go
  test/e2e/reconciler/workspacedeletion/controller_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/virtual/workspaces/virtual_workspace_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm, kind/api-change

#2570 ✨ Synctarget: Have URLs for both syncer and upsyncer
  config/crds/workload.kcp.io_synctargets.yaml
  config/root-phase0/apiexport-workload.kcp.io.yaml
  config/root-phase0/apiresourceschema-synctargets.workload.kcp.io.yaml
  pkg/apis/workload/v1alpha1/synctarget_types.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/workload/synctarget/synctarget_reconcile.go
  pkg/reconciler/workload/synctarget/synctarget_reconcile_test.go
  pkg/syncer/syncer.go
  pkg/virtual/framework/internalapis/fixtures/synctargets.yaml
  test/e2e/framework/syncer.go
Labels: approved, lgtm, kind/api-change

#2577 🌱 verify-contextual-logging should diff from old to new
  hack/verify-contextual-logging.sh
Labels: approved, lgtm

#2580 :book: crd-ref: update for core group
  hack/generate/crd-ref/config.yaml
Labels: approved, lgtm

#2452 ✨ Refactor Syncer based on the enhanced ddsif, with controller manager and endpoints controller
  hack/logcheck.out
  pkg/informer/informer.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/syncer/controllermanager/controllermanager.go
  pkg/syncer/endpoints/endpoint_downstream_controller.go
  pkg/syncer/indexers/indexes.go
  pkg/syncer/namespace/namespace_downstream_controller.go
  pkg/syncer/resourcesync/controller.go
  pkg/syncer/shared/finalizer.go
  pkg/syncer/shared/helpers.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_controller.go
  pkg/syncer/status/status_process.go
  pkg/syncer/status/status_process_test.go
  pkg/syncer/syncer.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
Labels: area/transparent-multi-cluster, approved, lgtm

#2587 🌱 Update logcheck to 0.4.0
  Makefile
  hack/verify-contextual-logging.sh
Labels: approved, lgtm

#2588 🐛 WorkspaceType admission should respect LimitAllow{Parents, Children}.None
  config/crds/tenancy.kcp.io_workspacetypes.yaml
  config/crds/tenancy.kcp.io_workspacetypes.yaml-patch
  config/root-phase0/apiexport-tenancy.kcp.io.yaml
  config/root-phase0/apiresourceschema-workspacetypes.tenancy.kcp.io.yaml
  pkg/admission/workspacetypeexists/admission.go
  pkg/admission/workspacetypeexists/admission_test.go
Labels: approved, lgtm, kind/api-change

#2590 :sparkles: DRY committer factory functions
  pkg/reconciler/committer/committer.go
Labels: approved, lgtm

#2599 🌱 Stop checking PR descriptions in CI
  .github/workflows/pr-verifier.yaml
Labels: approved, lgtm

#2594 :bug: reconciler/cache: remove reflection and fix replicate+NotFound logic
  .golangci.yaml
  pkg/reconciler/cache/replication/replication_reconcile.go
  pkg/reconciler/cache/replication/replication_reconcile_test.go
  pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
Labels: approved, lgtm

#2602 :bug: committer: fix equality check in statusless committer
  pkg/reconciler/committer/statusless_committer.go
Labels: approved, lgtm

#2477 🌱 Use caching authorizers per-workspace in initializingworkspaces/builder
  pkg/admission/apibinding/apibinding_admission.go
  pkg/admission/apibinding/apibinding_admission_test.go
  pkg/admission/workspacetypeexists/admission.go
  pkg/admission/workspacetypeexists/admission_test.go
  pkg/authorization/delegated/authorizer.go
  pkg/authorization/delegated/caching_authorizer.go
  pkg/virtual/apiexport/authorizer/content.go
  pkg/virtual/apiexport/authorizer/maximal_permission_policy.go
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/syncer/builder/template.go
Labels: approved, lgtm, kind/api-change

#2600 🌱 resource controller: log each gvr by itself instead of accumulating
  pkg/reconciler/workload/resource/resource_controller.go
Labels: approved, lgtm

#2591 :bug: e2e: PrivateKcpServer enable audit-policy
  test/e2e/framework/kcp.go
Labels: approved, lgtm

#2606 🐛 IndexByLogicalClusterPathAndName should return clusterpath and name
  pkg/indexers/indexers.go
Labels: approved, lgtm

#2609 :seedling: reconciler/cache/reconciler: simplify and generalize
  pkg/reconciler/cache/replication/replication_controller.go
  pkg/reconciler/cache/replication/replication_reconcile.go
  pkg/reconciler/cache/replication/replication_reconcile_test.go
  pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
  pkg/reconciler/cache/replication/replication_reconcile_unstructured_test.go
  pkg/server/controllers.go
Labels: approved, lgtm

#2610 :seedling: e2e: TestAuditLogs remove duplicate audit-log-path
  test/e2e/audit/audit_log_test.go
Labels: approved, lgtm

#2604 :bug: Role and ClusterRole merger should not modify cache objects
  pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
  pkg/virtual/framework/wrappers/rbac/merging.go
  pkg/virtual/framework/wrappers/rbac/merging_test.go
Labels: approved, lgtm

#2605 🌱 Enable KUBE_CACHE_MUTATION_DETECTOR in e2e tests
  .github/workflows/ci.yaml
  Makefile
Labels: approved, lgtm

#2431 :sparkles: Install Calico in kind for CI testing
  .github/workflows/ci.yaml
  test/e2e/kind/config-calico.yaml
Labels: area/transparent-multi-cluster, approved, lgtm

#2560 :sparkles: Admission for APIExportEndpointSlice
  pkg/admission/apibinding/apibinding_admission.go
  pkg/admission/apibinding/binding_permissions.go
  pkg/admission/apiexportendpointslice/apiexportendpointslice_admission.go
  pkg/admission/apiexportendpointslice/apiexportendpointslice_admission_test.go
  pkg/admission/apiexportendpointslice/validation.go
  pkg/admission/plugins.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_reconcile.go
Labels: approved, lgtm, kind/api-change

#2618 🐛 Add bind permission for kubernetes apiexport
  config/rootcompute/kube-1.24/clusterrole-kubernetes-apiexport-bind.yaml
  config/rootcompute/kube-1.24/clusterrolebinding-kubernetes-apiexport-bind.yaml
Labels: approved, lgtm

#2611 🌱 test/e2e/virtual/apiexport: make authorizer test self-contained
  test/e2e/virtual/apiexport/authorizer_test.go
Labels: approved, lgtm

#2620 🌱 run replication tests on a shared kcp instance
  cmd/sharded-test-server/main.go
  test/e2e/framework/kcp.go
  test/e2e/reconciler/cache/replication_test.go
Labels: approved, lgtm

#2629 :seedling: Admission cleanup
  pkg/admission/apibinding/apibinding_admission.go
Labels: approved, lgtm, kind/api-change

#2636 :seedling: permissionclaimlabel_controller uses committer
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
Labels: approved, lgtm

#2638 :seedling: location_controller uses committer
  pkg/reconciler/scheduling/location/location_controller.go
Labels: approved, lgtm

#2628 🐛 pkg/server: ensure that home workspace handler gets authz with audit …
  pkg/server/config.go
  test/e2e/audit/audit_log_test.go
Labels: approved, lgtm

#2646 🌱 extraannotationsync: use function pointers
  pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller.go
Labels: approved, lgtm

#2645 🐛 pkg/reconciler/apis/apibinding: return error in case of conflicts
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
Labels: approved, lgtm

#2632 🐛 e2e/watchcache: use cluster client for creating content in a workspace
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: approved, lgtm

#2639 🐛 e2e/reconciler/workspace: use cluster client
  test/e2e/reconciler/workspace/controller_test.go
Labels: approved, lgtm

#2641 🐛 reconciler/apiexport: use the gloabl informer to get Shards
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/server/controllers.go
Labels: approved, lgtm

#2644 🐛 e2e/conversion: wrap create in eventually
  test/e2e/conversion/conversion_test.go
Labels: approved, lgtm

#2407 :bug: add support for standalone virtualworkspace server
  Makefile
  cmd/sharded-test-server/main.go
  cmd/sharded-test-server/shard.go
  cmd/sharded-test-server/virtual.go
  cmd/virtual-workspaces/command/cmd.go
  pkg/server/config.go
  pkg/server/controllers.go
  pkg/server/handler.go
  pkg/server/options/flags.go
  pkg/server/options/options.go
Labels: approved, lgtm

#2653 :seedling: bootstrap_controller uses committer
  pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
Labels: approved, lgtm

#2659 :bug: server: relax ShardVirtualWorkspace flag validation
  pkg/server/controllers.go
Labels: approved, lgtm

#2651 🐛 e2e: temporarily schedule all workspaces on the root shard for tmc-related tests
  test/e2e/framework/workspaces.go
  test/e2e/reconciler/cluster/controller_test.go
  test/e2e/reconciler/deployment/deployment_coordinator_test.go
  test/e2e/reconciler/locationworkspace/local_apiexport_test.go
  test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
  test/e2e/reconciler/locationworkspace/rootcompute_test.go
  test/e2e/reconciler/locationworkspace/synctarget_test.go
  test/e2e/reconciler/namespace/controller_test.go
  test/e2e/reconciler/scheduling/api_compatibility_test.go
  test/e2e/reconciler/scheduling/controller_test.go
  test/e2e/reconciler/scheduling/multi_placements_test.go
  test/e2e/reconciler/scheduling/placement_scheduler_test.go
  test/e2e/syncer/dns/dns_test.go
  test/e2e/syncer/syncer_test.go
  test/e2e/syncer/tunnels_test.go
Labels: approved, lgtm

#2660 🐛 controller: use the global informer to get Shards
  pkg/server/controllers.go
Labels: approved, lgtm

#2637 🐛 Use APIExport cluster names within webhooks
  config/crds/apis.kcp.io_apibindings.yaml
  pkg/admission/webhook/generic_webhook.go
  pkg/admission/webhook/generic_webhook_test.go
  pkg/apis/apis/v1alpha1/types_apibinding.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
Labels: approved, lgtm, kind/api-change

#2670 🌱 Remove trailing parentheses in ASCII diagram link
  docs/content/en/main/concepts/authorization.md
Labels: approved, lgtm

#2674 :seedling: clusterworkspacetype_controller uses committer.
  pkg/reconciler/tenancy/workspacetype/clusterworkspacetype_controller.go
Labels: approved, lgtm

#2640 🌱 test/e2e: add support for dynamic users using client certs
  cmd/test-server/main.go
  test/e2e/apibinding/maximalpermissionpolicy_authorizer_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/framework/kcp.go
  test/e2e/framework/util.go
  test/e2e/virtual/apiexport/authorizer_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm

#2667 :bug: server: revert non-standalone VW URL
  pkg/server/controllers.go
Labels: approved, lgtm

#2677 🐛 Add a kcp RequestInfoResolver
  pkg/server/config.go
  pkg/server/requestinfo/kcp_request_info_resolver.go
Labels: approved, lgtm

#2661 :seedling: logicalcluster_deletion_controller uses committer
  pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
Labels: approved, lgtm

#2678 🌱 pkg/authorization: enable audit logging for SAR requests
  pkg/authorization/decorator.go
  pkg/authorization/decorator_test.go
  pkg/authorization/requiredgroups_authorizer_test.go
  pkg/authorization/workspace_content_authorizer_test.go
  pkg/server/config.go
  pkg/server/options/authorization.go
  test/e2e/audit/audit_log_test.go
Labels: approved, lgtm

#2680 🐛 Use status.phase as printer column on workspaces and logical clusters
  pkg/apis/core/v1alpha1/logicalcluster_types.go
  pkg/apis/tenancy/v1alpha1/types_workspace.go
Labels: approved, lgtm, kind/api-change

#2683 :bug: *: update listers to have correct NotFound messages
  Makefile
  go.mod
  go.sum
  pkg/client/listers/apiresource/v1alpha1/apiresourceimport.go
  pkg/client/listers/apiresource/v1alpha1/negotiatedapiresource.go
  pkg/client/listers/apis/v1alpha1/apibinding.go
  pkg/client/listers/apis/v1alpha1/apiconversion.go
  pkg/client/listers/apis/v1alpha1/apiexport.go
  pkg/client/listers/apis/v1alpha1/apiexportendpointslice.go
  pkg/client/listers/apis/v1alpha1/apiresourceschema.go
  pkg/client/listers/core/v1alpha1/logicalcluster.go
  pkg/client/listers/core/v1alpha1/shard.go
  pkg/client/listers/scheduling/v1alpha1/location.go
  pkg/client/listers/scheduling/v1alpha1/placement.go
  pkg/client/listers/tenancy/v1alpha1/workspace.go
  pkg/client/listers/tenancy/v1alpha1/workspacetype.go
  pkg/client/listers/topology/v1alpha1/partition.go
  pkg/client/listers/topology/v1alpha1/partitionset.go
  pkg/client/listers/workload/v1alpha1/synctarget.go
  test/e2e/fixtures/wildwest/client/listers/wildwest/v1alpha1/cowboy.go
Labels: approved, lgtm

#2684 🐛 Deflake TestSpecSyncerProcess
  pkg/syncer/spec/spec_process_test.go
Labels: approved, lgtm

#2694 :bug: test/e2e: remove a data race
  test/e2e/framework/workspaces.go
Labels: approved, lgtm

#2690 🐛 Do not look up APIExports in the generic webhook
  pkg/admission/webhook/generic_webhook.go
  pkg/admission/webhook/generic_webhook_test.go
  pkg/reconciler/workload/resource/resource_controller.go
Labels: approved, lgtm, kind/api-change

#2698 :seedling: reconcilers/workspace: add logging to outgoing client calls
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
Labels: approved, lgtm

#2701 🌱 correctly log unstructured group/resource with k8s reflector
  go.mod
  go.sum
Labels: approved, lgtm

#2401 ✨ Support for pod logs and other subresources
  pkg/cliplugins/workload/plugin/sync.go
  pkg/server/config.go
  pkg/tunneler/integration_test.go
  pkg/tunneler/listener.go
  pkg/tunneler/listener_test.go
  pkg/tunneler/podsubresourceproxy_handler.go
  pkg/tunneler/podsubresourceproxy_handler_test.go
  pkg/tunneler/syncertunnel_handler.go
  pkg/tunneler/tunnel.go
  pkg/tunneler/tunnel_test.go
  pkg/virtual/syncer/builder/build.go
  test/e2e/syncer/tunnels_test.go
Labels: area/transparent-multi-cluster, approved, lgtm, kind/api-change

#2608 :seedling: End-to-end tests for APIExportEndpointSlice
  test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
Labels: approved, lgtm, kind/api-change

#2705 🌱 tests: gather metrics
  cmd/sharded-test-server/main.go
  cmd/test-server/kcp/shard.go
  cmd/test-server/main.go
  test/e2e/framework/kcp.go
Labels: approved, lgtm

#2708 :book: document kcp bind commmand to allow to sync deployment in quickstart
  README.md
Labels: approved, lgtm

#2673 :book: fix docs versioning and permissions for gh-pages
  .github/workflows/docs-gen-and-push.yaml
  docs/config.toml
Labels: approved, lgtm

#2720 🐛 Fix gap in APIExport virtual workspace queues
  pkg/indexers/apiexport.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
  test/e2e/virtual/apiexport/authorizer_test.go
Labels: approved, lgtm
