Repository kcp-dev/kcp, pull requests merged in 2023-06, with the labels that each got.

#2966 🐛 Track kcp-dev/kube fix wrt local admin cluster
  go.mod
  go.sum
Labels: approved, lgtm

#2968 ✨ Consolidate sdk/apis
  cmd/apigen/go.mod
  cmd/apigen/go.sum
  docs/content/concepts/quickstart-tenancy-and-apis.md
  docs/content/developers/publishing-a-new-kcp-release.md
  hack/update-codegen-crds.sh
  sdk/cmd/apigen/main.go
  sdk/go.mod
  sdk/go.sum
Labels: approved, lgtm

#2957 :bug: tenancy: only delete LogicalCluster if needed
  pkg/reconciler/tenancy/workspace/workspace_reconcile_deletion.go
Labels: approved, lgtm

#2959 :bug: cache: only enqueue ClusterRoleBindings for the right logical cluster
  pkg/reconciler/cache/labelclusterrolebindings/labelclusterrolebinding_controller.go
  pkg/reconciler/core/replicateclusterrolebinding/replicateclusterrolebinding_controller.go
Labels: approved, lgtm

#2975 :seedling: Add Prowjobs
  .ci-operator.yaml
  .prow.yaml
  hack/verify-go-versions.sh
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#2971 :warning: Remove TMC bootstrap assets
  config/crds/scheduling.kcp.io_locations.yaml
  config/crds/scheduling.kcp.io_locations.yaml-patch
  config/crds/scheduling.kcp.io_placements.yaml
  config/crds/workload.kcp.io_synctargets.yaml
  config/crds/workload.kcp.io_synctargets.yaml-patch
  config/root-phase0/apiexport-scheduling.kcp.io.yaml
  config/root-phase0/apiexport-workload.kcp.io.yaml
  config/root-phase0/apiresourceschema-locations.scheduling.kcp.io.yaml
  config/root-phase0/apiresourceschema-placements.scheduling.kcp.io.yaml
  config/root-phase0/apiresourceschema-synctargets.workload.kcp.io.yaml
  config/root-phase0/bootstrap.go
  config/root/clusterrole-scheduling-apiexport-bind.yaml
  config/root/clusterrole-scheduling-maximal-permission-policy.yaml
  config/root/clusterrole-workload-apiexport-bind.yaml
  config/root/clusterrole-workload-maximal-permission-policy.yaml
  config/root/clusterrolebinding-scheduling-apiexport-bind.yaml
  config/root/clusterrolebinding-scheduling-maximal-permission-policy.yaml
  config/root/clusterrolebinding-workload-apiexport-bind.yaml
  config/root/clusterrolebinding-workload-maximal-permission-policy.yaml
  config/root/workspacetype-universal.yaml
  config/rootcompute/bootstrap.go
  config/rootcompute/clusterworkspace-compute.yaml
  config/rootcompute/kube-1.24/apiexport-kubernetes.k8s.io.yaml
  config/rootcompute/kube-1.24/apiresourceschema_deployments.apps.yaml
  config/rootcompute/kube-1.24/apiresourceschema_endpoints.yaml
  config/rootcompute/kube-1.24/apiresourceschema_ingresses.networking.k8s.io.yaml
  config/rootcompute/kube-1.24/apiresourceschema_pods.yaml
  config/rootcompute/kube-1.24/apiresourceschema_services.yaml
  config/rootcompute/kube-1.24/bootstrap.go
  config/rootcompute/kube-1.24/clusterrole-kubernetes-apiexport-bind.yaml
  config/rootcompute/kube-1.24/clusterrole-kubernetes-maximal-permission-policy.yaml
  config/rootcompute/kube-1.24/clusterrolebinding-kubernetes-apiexport-bind.yaml
  config/rootcompute/kube-1.24/clusterrolebinding-kubernetes-maximal-permission-policy.yaml
  config/shard/bootstrap.go
  docs/generators/crd-ref/config.yaml
  pkg/cache/server/bootstrap/bootstrap.go
  pkg/server/bootstrap/identity.go
  pkg/server/options/batteries/batteries.go
  test/e2e/reconciler/workspace/apibinding_initializer_test.go
Labels: approved, lgtm, kind/api-change, size/XXL, release-note, dco-signoff: yes

#2976 🌱 Add images Prowjob
  .github/workflows/kcp-image.yaml
  .prow.yaml
  Dockerfile
  hack/build-image.sh
  hack/verify-go-versions.sh
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#2980 🌱 Remove GitHub Actions for image builds
  .github/workflows/kcp-image.yaml
  .github/workflows/syncer-image.yaml
Labels: approved, lgtm, ok-to-test, size/M, dco-signoff: yes, release-note-none

#2979 :bug: Remove replace stanzas
  sdk/go.mod
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#2974 :seedling: Add release notes into PR template
  .github/pull_request_template.md
Labels: approved, lgtm, size/S, dco-signoff: yes, release-note-none

#2985 :book: Remove TMC from docs
  docs/README.md
  docs/content/CONTRIBUTING.md
  docs/content/concepts/placement-locations-and-scheduling.md
  docs/content/concepts/registering-kubernetes-clusters-using-syncer.md
  docs/content/concepts/storage.md
  docs/content/concepts/terminology.md
  docs/content/index.md
Labels: approved, lgtm, size/XL, release-note, dco-signoff: yes

#2988 :book: Update release process doc
  docs/content/developers/publishing-a-new-kcp-release.md
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes
