Repository kcp-dev/kcp, pull requests merged in 2023-04, with the labels that each got.

#2933 🌱 Replicating SyncTarget-related rbac and logicalclusters objects
  pkg/reconciler/workload/replicateclusterrole/replicateclusterrole_controller.go
  pkg/reconciler/workload/replicateclusterrolebinding/replicateclusterrolebinding_controller.go
  pkg/reconciler/workload/replicatelogicalcluster/replicatelogicalcluster_controller.go
  test/e2e/reconciler/cache/replication_test.go
  tmc/pkg/server/controllers.go
  tmc/pkg/server/server.go
Labels: approved, lgtm

#2941 :seedling: Unify workload[s] names in the tmc controller.go
  tmc/pkg/server/controllers.go
  tmc/pkg/server/server.go
Labels: approved, lgtm, ok-to-test

#2944 :sparkles: pkg/indexers: add helers for cache server fallback
  pkg/admission/apibinding/apibinding_admission.go
  pkg/admission/apiexportendpointslice/apiexportendpointslice_admission.go
  pkg/admission/workspacetypeexists/admission.go
  pkg/authorization/maximal_permission_policy_authorizer.go
  pkg/indexers/indexers.go
  pkg/permissionclaim/permissionclaim_labeler.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
  pkg/reconciler/workload/placement/placement_controller.go
Labels: approved, lgtm, kind/api-change

#2939 :seedling: Add cache lookup to TMC controllers
  pkg/informer/fallback_lookup.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/workload/resource/resource_controller.go
  pkg/reconciler/workload/synctarget/synctarget_controller.go
  pkg/reconciler/workload/synctargetexports/synctargetexports_controller.go
  tmc/pkg/server/controllers.go
Labels: area/transparent-multi-cluster, approved, lgtm

#2948 🌱 Use cached informers in scheduling controllers
  pkg/reconciler/scheduling/placement/placement_controller.go
  pkg/reconciler/scheduling/placement/placement_reconcile.go
  pkg/reconciler/workload/placement/placement_controller.go
  tmc/pkg/server/controllers.go
Labels: approved, lgtm

#2675 ✨ Syncer: support multiple shards
  cmd/sharded-test-server/shard.go
  cmd/sharded-test-server/virtual.go
  cmd/virtual-workspaces/command/cmd.go
  cmd/virtual-workspaces/options/options.go
  pkg/server/config.go
  pkg/server/virtual.go
  pkg/syncer/namespace/namespace_downstream_controller.go
  pkg/syncer/resourcesync/controller.go
  pkg/syncer/shared/finalizer.go
  pkg/syncer/spec/dns/dns_process.go
  pkg/syncer/spec/dns/dns_process_test.go
  pkg/syncer/spec/mutators/podspecable.go
  pkg/syncer/spec/mutators/podspecable_test.go
  pkg/syncer/spec/spec_controller.go
  pkg/syncer/spec/spec_process.go
  pkg/syncer/spec/spec_process_test.go
  pkg/syncer/status/status_controller.go
  pkg/syncer/status/status_process.go
  pkg/syncer/status/status_process_test.go
  pkg/syncer/syncer.go
  pkg/syncer/synctarget/gvr_source.go
  pkg/syncer/synctarget/shard_manager.go
  pkg/syncer/synctarget/synctarget_controller.go
  pkg/syncer/synctarget/synctarget_reconciler.go
  pkg/syncer/upsync/upsync_cleanup_controller.go
  pkg/syncer/upsync/upsync_cleanup_reconcile.go
  pkg/syncer/upsync/upsync_controller.go
  pkg/syncer/upsync/upsync_process_test.go
  pkg/syncer/upsync/upsync_reconcile.go
  pkg/virtual/options/options.go
  sdk/apis/workload/v1alpha1/types.go
  test/e2e/syncer/multishard/multishard_test.go
  test/e2e/syncer/multishard/workspace1/deployment.yaml
  test/e2e/syncer/multishard/workspace1/embed.go
  test/e2e/syncer/multishard/workspace2/deployment.yaml
  test/e2e/syncer/multishard/workspace2/embed.go
  tmc/pkg/server/config.go
  tmc/pkg/virtual/options/options.go
  tmc/pkg/virtual/syncer/builder/build.go
  tmc/pkg/virtual/syncer/options/options.go
  tmc/pkg/virtual/syncer/transformations/transformer.go
  tmc/pkg/virtual/syncer/transformations/transformer_test.go
Labels: area/transparent-multi-cluster, approved, lgtm, kind/api-change

#2937 📖 Update CONTRIBUTING.md re golang version
  docs/content/CONTRIBUTING.md
Labels: approved, lgtm

#2946 :sparkles: Make the tunneler shard-aware
  config/crds/workload.kcp.io_synctargets.yaml
  config/root-phase0/apiexport-workload.kcp.io.yaml
  config/root-phase0/apiresourceschema-synctargets.workload.kcp.io.yaml
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/workload/synctarget/synctarget_reconcile.go
  pkg/reconciler/workload/synctarget/synctarget_reconcile_test.go
  pkg/server/config.go
  pkg/syncer/syncer.go
  pkg/syncer/synctarget/synctarget_controller.go
  pkg/syncer/synctarget/synctarget_reconciler.go
  pkg/syncer/synctarget/tunneler_reconciler.go
  pkg/tunneler/podsubresourceproxy_handler.go
  pkg/virtual/framework/internalapis/fixtures/synctargets.yaml
  sdk/apis/workload/v1alpha1/synctarget_types.go
  sdk/apis/workload/v1alpha1/zz_generated.deepcopy.go
  sdk/client/applyconfiguration/utils.go
  sdk/client/applyconfiguration/workload/v1alpha1/synctargetstatus.go
  sdk/client/applyconfiguration/workload/v1alpha1/tunnelworkspace.go
  test/e2e/syncer/multishard/multishard_test.go
  test/e2e/syncer/tunnels_test.go
Labels: approved, lgtm, kind/api-change
