Repository kcp-dev/kcp, pull requests merged in 2024-09, with the labels that each got.

#3159 :book: Add `ADOPTERS.md` and adopters form
  .github/ISSUE_TEMPLATE/adopters.yaml
  ADOPTERS.md
Labels: approved, lgtm, size/M, dco-signoff: yes, release-note-none

#3157 :book: Refresh documentation and improve "Concepts" structure
  docs/content/GOALS.md
  docs/content/concepts/.pages
  docs/content/concepts/apis/built-in.md
  docs/content/concepts/apis/exporting-apis.md
  docs/content/concepts/apis/index.md
  docs/content/concepts/apis/rest-access-patterns.md
  docs/content/concepts/authorization/authorizers.md
  docs/content/concepts/authorization/index.md
  docs/content/concepts/cluster-mapper.md
  docs/content/concepts/miscellaneous/braindump.md
  docs/content/concepts/miscellaneous/index.md
  docs/content/concepts/quickstart-tenancy-and-apis.md
  docs/content/concepts/sharding/.pages
  docs/content/concepts/sharding/cache-server.md
  docs/content/concepts/sharding/index.md
  docs/content/concepts/sharding/partitions.md
  docs/content/concepts/sharding/shards.md
  docs/content/concepts/terminology.md
  docs/content/concepts/workspaces/.pages
  docs/content/concepts/workspaces/index.md
  docs/content/concepts/workspaces/virtual-workspaces.md
  docs/content/concepts/workspaces/workspace-types.md
  docs/content/contributing/index.md
  docs/content/contributing/inspecting-e2e-metrics.md
  docs/content/contributing/publishing-a-new-kcp-release.md
  docs/content/contributing/rebasing-kubernetes.md
  docs/content/contributing/replicate-new-resource.md
  docs/content/developers/controllers/writing-kcp-aware-controllers.md
  docs/content/setup/helm.md
  docs/content/setup/kubectl-plugin.md
  docs/content/setup/quickstart.md
  docs/mkdocs.yml
  docs/overrides/partials/section-overview.html
Labels: approved, lgtm, size/XL, dco-signoff: yes, release-note-none

#3163 :bug: authorization/delegated: fix typo leading to zero deny cache ttl
  pkg/authorization/delegated/authorizer.go
  test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
Labels: approved, lgtm, size/S, release-note, dco-signoff: yes

#3165 :bug: Bump kubernetes to reduce admission webhook memory consumption
  go.mod
  go.sum
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes

#3166 :bug: reconciler/apibinding: filter by cluster through index, not manually
  pkg/reconciler/apis/apibinding/apibinding_controller.go
Labels: approved, lgtm, size/S, dco-signoff: yes, release-note-none

#3167 :bug: virtual/authorization: shallow copy of RBAC objects
  pkg/virtual/framework/wrappers/rbac/merging.go
Labels: approved, lgtm, size/S, release-note, dco-signoff: yes

#3168 :bug: virtual/apiexport: don't keep recreating APIBindings storage
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3170 :bug: reconciler/apibinding: share conflict checker for all schemas in bindings
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
  pkg/reconciler/apis/apibinding/conflict_checker.go
  pkg/reconciler/apis/apibinding/conflict_checker_test.go
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3172 :seedling: cache-server: misc cleanups
  sdk/apis/core/helper/replicate.go
  test/e2e/reconciler/cache/replication_test.go
Labels: approved, lgtm, size/M, dco-signoff: yes, release-note-none

#3174 🐛 Fix 'make install' to respect plugin go module
  Makefile
Labels: approved, lgtm, ok-to-test, size/XS, dco-signoff: yes, release-note-none

#3119 :bug: tenancy/workspace-deletion: try harder with the admin client to delete the LogicalCluster
  pkg/reconciler/tenancy/workspace/workspace_reconcile.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_deletion.go
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes
