Repository kcp-dev/kcp, pull requests merged in 2024-01, with the labels that each got.

#3067 :sparkles: Build cache server into image
  Dockerfile
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#3070 🐛 Generate `admin.kubeconfig` with correct cluster for `system:admin` context
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/virtual.go
  cmd/test-server/kcp/shard.go
  docs/content/concepts/workspaces.md
  pkg/server/config.go
  pkg/server/options/authentication.go
  test/e2e/framework/kcp.go
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes

#3073 🌱 reduce log verbosity for queueing operations
  config/crds/bootstrap.go
  pkg/proxy/index/index_controller.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
  pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_reconcile.go
  pkg/reconciler/cache/labelclusterrolebindings/labelclusterrolebinding_reconcile.go
  pkg/reconciler/cache/labelclusterroles/labelclusterrole_reconcile.go
  pkg/reconciler/cache/labellogicalcluster/labellogicalcluster_reconcile.go
  pkg/reconciler/core/logicalcluster/logicalcluster_controller.go
  pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
  pkg/reconciler/core/shard/shard_controller.go
  pkg/reconciler/garbagecollector/garbagecollector_controller.go
  pkg/reconciler/kubequota/kubequota_controller.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_reconcile.go
  pkg/reconciler/tenancy/logicalcluster/logicalcluster_controller.go
  pkg/reconciler/tenancy/workspace/workspace_controller.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
  pkg/reconciler/tenancy/workspacetype/workspacetype_controller.go
  pkg/server/bootstrap/identity.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes

#3074 🌱 Bump prow jobs to use `ghcr.io/kcp-dev/infra/build:1.20.13-1`
  .prow.yaml
Labels: approved, lgtm, size/S, release-note, dco-signoff: yes

#3076 :seedling: Update otel and grpc dependencies
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3075 :book: Update release process with release note generation
  .github/pull_request_template.md
  docs/content/developers/publishing-a-new-kcp-release.md
Labels: approved, lgtm, size/M, dco-signoff: yes, release-note-none

#3077 🌱 Update `golang.org/x/crypto` to latest version
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes

#3078 📖 Update deploy-docs.sh script to also deploy on manual runs
  docs/content/developers/publishing-a-new-kcp-release.md
  docs/scripts/deploy-docs.sh
Labels: approved, lgtm, size/S, dco-signoff: yes, release-note-none

#3081 :bug: Use correct case on verb for metrics-viewer ClusterRole
  config/root/metrics-1-cluster-role.yaml
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes
