Repository kcp-dev/kcp, pull requests merged in 2024-12, with the labels that each got.

#3201 :book: add dex quickstart
  .gitignore
  contrib/kcp-dex/README.md
  contrib/kcp-dex/kcp-config.yaml
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3208 🌱 Bump golangci-lint, remove staticcheck
  .golangci.yaml
  Makefile
  cmd/virtual-workspaces/options/options.go
  pkg/admission/kubequota/kubequota_clusterworkspace_monitor.go
  pkg/admission/logicalcluster/admission.go
  pkg/cache/server/config.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go
  pkg/reconciler/apis/apiexport/apiexport_controller_test.go
  pkg/reconciler/apis/apiexport/apiexport_reconcile.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_controller_test.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_reconcile.go
  pkg/reconciler/cache/replication/replication_controller.go
  pkg/reconciler/core/logicalclusterdeletion/deletion/logicalcluster_resource_deletor.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_reconcile.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling_test.go
  pkg/reconciler/tenancy/workspacemounts/workspacemounts_reconcile_updater.go
  pkg/reconciler/tenancy/workspacetype/workspacetype_controller_reconcile.go
  pkg/reconciler/topology/partitionset/partitionset_controller_test.go
  pkg/reconciler/topology/partitionset/partitionset_reconcile.go
  pkg/virtual/framework/dynamic/apiserver/handler_test.go
  pkg/virtual/framework/dynamic/apiserver/serving_info.go
  pkg/virtual/framework/transforming/client.go
  sdk/apis/test/cel.go
  sdk/apis/test/pattern.go
  sdk/apis/third_party/conditions/util/conditions/setter_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/authorizer/serviceaccounts_test.go
  test/e2e/authorizer/workspace_test.go
  test/e2e/cache/cache_server_test.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/framework/kcp.go
  test/e2e/garbagecollector/garbagecollector_test.go
  test/e2e/mounts/mounts_machinery_test.go
  test/e2e/reconciler/cache/replication_test.go
  test/e2e/reconciler/shard/controller_test.go
  test/e2e/reconciler/workspace/controller_test.go
  test/e2e/reconciler/workspacedeletion/controller_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm, kind/api-change, size/L, release-note, dco-signoff: yes

#3211 :warning: Stop building artefacts for ppc64le
  .github/workflows/ci-docs-only.yaml
  .github/workflows/e2e-ci-ppc64le.yml
  .goreleaser.yaml
  hack/build-image.sh
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes

#3212 :seedling: Update to Go 1.22.10
  .github/workflows/docs-gen-and-push.yaml
  .github/workflows/goreleaser.yml
  .prow.yaml
  Dockerfile
Labels: approved, lgtm, size/S, release-note, dco-signoff: yes

#3213 [release-0.26] :seedling: Update to Go 1.22.10
  .github/workflows/docs-gen-and-push.yaml
  .github/workflows/goreleaser.yml
  .prow.yaml
  Dockerfile
Labels: approved, lgtm, size/S, release-note, dco-signoff: yes

#3217 📖 Add SAP (ApeiroRA) as adopters
  ADOPTERS.md
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3219 🐛 fix check `deleteError != nil` but return an other nil value `err`
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go
Labels: approved, lgtm, ok-to-test, size/XS, dco-signoff: yes, release-note-none

#3198 ✨ Enable webhook authorization options
  Makefile
  cmd/kcp/kcp.go
  docs/content/concepts/authorization/authorizers.md
  docs/content/concepts/authorization/index.md
  docs/mkdocs.yml
  hack/bump-k8s.sh
  pkg/server/config.go
  pkg/server/options/authorization.go
  pkg/server/options/options.go
  test/e2e/authorizer/webhook.kubeconfig
  test/e2e/authorizer/webhook_test.go
  test/e2e/framework/kcp.go
Labels: approved, lgtm, size/XL, release-note, dco-signoff: yes

#3220 :sparkles: Add prefix to dev images for gc
  hack/build-image.sh
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3199 ✨ Enhance local-dev for VirtualWorkspaces
  cmd/kcp/kcp.go
  cmd/kcp/options/generic.go
  pkg/proxy/handler.go
  pkg/proxy/index/index_controller.go
  pkg/proxy/mapping.go
  pkg/server/config.go
  pkg/server/localproxy.go
  pkg/server/options/options.go
  pkg/server/proxy/handler.go
  pkg/server/proxy/mapping_test.go
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes

#3229 :bug: Fix undo function of cluster annotation setter wiping annotations
  pkg/admission/validatingwebhook/plugin.go
  pkg/admission/validatingwebhook/plugin_test.go
Labels: approved, lgtm, ok-to-test, kind/api-change, size/L, release-note, dco-signoff: yes

#3234 :seedling: authz: make step logs useful
  pkg/authorization/decorator.go
Labels: approved, lgtm, size/M, dco-signoff: yes, release-note-none

#3231 :bug: Fix localproxy routing
  cmd/kcp/kcp.go
  pkg/server/localproxy.go
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3233 :bug: Fix typo in workspace api
  config/crds/tenancy.kcp.io_workspacetypes.yaml
  config/root-phase0/apiresourceschema-workspacetypes.tenancy.kcp.io.yaml
  docs/content/developers/registry.png
  docs/content/developers/storage-to-rest-patterns.md
  pkg/openapi/zz_generated.openapi.go
  sdk/apis/tenancy/v1alpha1/types_workspacetype.go
Labels: approved, lgtm, kind/api-change, size/XS, dco-signoff: yes, release-note-none

#3210 :book: Proposal for initial security policy
  SECURITY.md
Labels: approved, lgtm, size/S, dco-signoff: yes, release-note-none

#3224 :book: Create CLI docs for workspace and create workspace cli
  cli/cmd/kubectl-create-workspace/cmd/kubectlCreateWorkspace.go
  cli/cmd/kubectl-create-workspace/main.go
  cli/cmd/kubectl-ws/cmd/kubectlWs.go
  cli/cmd/kubectl-ws/main.go
  docs/generators/cli-doc/main.go
Labels: approved, lgtm, ok-to-test, size/L, release-note, dco-signoff: yes

#3228 :seedling: Update golang.org/x/net and golang.org/x/crypto to address security issues
  cli/go.mod
  cli/go.sum
  docs/generators/cli-doc/go.mod
  docs/generators/cli-doc/go.sum
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3230 :book: Create section navigation that works across any level of nesting
  docs/main.py
  docs/overrides/partials/section-overview.html
  docs/requirements.txt
  docs/scripts/serve-docs.sh
Labels: approved, lgtm, ok-to-test, size/S, release-note, dco-signoff: yes

#3237 :bug: Send options to stdout instead of stderr
  cmd/kcp/kcp.go
Labels: approved, lgtm, ok-to-test, size/XS, release-note, dco-signoff: yes
