Repository kcp-dev/kcp, pull requests merged in 2024-04, with the labels that each got.

#3037 :sparkles: Add Tilt setup to contrib
  .gitignore
  Makefile
  contrib/tilt/Dockerfile.cache
  contrib/tilt/Dockerfile.kcp
  contrib/tilt/Dockerfile.proxy
  contrib/tilt/README.md
  contrib/tilt/Tiltfile
  contrib/tilt/coredns.yaml
  contrib/tilt/dex-values.yaml
  contrib/tilt/generate-admin-kubeconfig.sh
  contrib/tilt/grafana-values.yaml
  contrib/tilt/ingress-values.yaml
  contrib/tilt/kcp-values.yaml
  contrib/tilt/kernel-limits-job.yaml
  contrib/tilt/kind.sh
  contrib/tilt/loki-values.yaml
  contrib/tilt/prometheus-values.yaml
  contrib/tilt/promtail-values.yaml
  contrib/tilt/tempo-values.yaml
Labels: approved, lgtm, size/XXL, release-note, dco-signoff: yes

#3090 ✨ Webhook URL based CRD conversions
  config/crds/apis.kcp.io_apiresourceschemas.yaml
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
  sdk/apis/apis/v1alpha1/crd_to_apiresourceschema.go
  sdk/apis/apis/v1alpha1/types_apiresourceschema.go
  sdk/apis/apis/v1alpha1/zz_generated.deepcopy.go
  sdk/client/applyconfiguration/apis/v1alpha1/apiresourceschemaspec.go
  sdk/client/applyconfiguration/apis/v1alpha1/customresourceconversion.go
  sdk/client/applyconfiguration/apis/v1alpha1/webhookclientconfig.go
  sdk/client/applyconfiguration/apis/v1alpha1/webhookconversion.go
  sdk/client/applyconfiguration/utils.go
Labels: approved, lgtm, kind/api-change, size/XL, release-note, dco-signoff: yes

#3109 :book: Update documentation dependencies and add dark mode
  docs/OWNERS
  docs/content/.pages
  docs/content/index.md
  docs/mkdocs.yml
  docs/overrides/favicons/android-144x144.png
  docs/overrides/favicons/android-192x192.png
  docs/overrides/favicons/android-36x36.png
  docs/overrides/favicons/android-48x48.png
  docs/overrides/favicons/android-72x72.png
  docs/overrides/favicons/android-96x96.png
  docs/overrides/favicons/android-chrome-192x192.png
  docs/overrides/favicons/android-chrome-512x512.png
  docs/overrides/favicons/apple-touch-icon-180x180.png
  docs/overrides/favicons/apple-touch-icon.png
  docs/overrides/favicons/favicon-1024.png
  docs/overrides/favicons/favicon-16x16.png
  docs/overrides/favicons/favicon-256.png
  docs/overrides/favicons/favicon-32x32.png
  docs/overrides/favicons/favicon.ico
  docs/overrides/favicons/mstile-150x150.png
  docs/overrides/favicons/pwa-192x192.png
  docs/overrides/favicons/pwa-512x512.png
  docs/overrides/favicons/tile150x150.png
  docs/overrides/favicons/tile310x310.png
  docs/overrides/favicons/tile70x70.png
  docs/overrides/logo.png
  docs/overrides/logo.svg
  docs/overrides/partials/outdated.html
  docs/requirements.txt
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3097 ✨ Implement `RulesFor` for `GlobalAuthorizer` and `LocalAuthorizer` to enable `SelfSubjectRulesReview`
  pkg/authorization/OWNERS
  pkg/authorization/global_authorizer.go
  pkg/authorization/local_authorizer.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/framework/auth-tokens.csv
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes

#3108 :book: Add architecture brain-dump.
  docs/content/concepts/braindump.md
Labels: approved, lgtm, size/XL, dco-signoff: yes, release-note-none

#3114 :seedling: Bump etcd dependencies to 3.5.13
  go.mod
  go.sum
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes

#3112 :seedling: Set controller rest config timeout to 30secs
  pkg/server/config.go
Labels: approved, lgtm, ok-to-test, size/XS, dco-signoff: yes, release-note-none

#3118 :sparkles: Implement cluster-aware OpenAPI v3
  pkg/server/config.go
  pkg/server/controllers.go
  pkg/server/openapiv3/controller.go
  pkg/server/openapiv3/servicecache.go
  pkg/server/server.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/openapi/openapi_test.go
Labels: approved, lgtm, size/XL, release-note, dco-signoff: yes

#3120 :bug: Implement RoundTripperWrapper everywhere to allow cancellation
  pkg/cache/client/round_tripper.go
  pkg/metadata/dynamic.go
  pkg/server/bootstrap/identity.go
Labels: approved, lgtm, size/M, dco-signoff: yes, release-note-none

#3122 :sparkles: Bump go to 1.21
  .github/workflows/docs-gen-and-push.yaml
  .github/workflows/goreleaser.yml
  .prow.yaml
  Dockerfile
  cli/go.mod
  cli/go.sum
  docs/content/contributing/index.md
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes
