Repository kcp-dev/kcp, pull requests merged in 2024-07, with the labels that each got.

#3139 :bug: Fix race issues in leader relection
  pkg/permissionclaim/permissionclaim_labeler.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_controller.go
  pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
  pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_controller.go
  pkg/reconciler/cache/labelclusterrolebindings/labelclusterrolebinding_controller.go
  pkg/reconciler/cache/labelclusterroles/labelclusterrole_controller.go
  pkg/reconciler/cache/replication/replication_controller.go
  pkg/reconciler/cache/replication/replication_reconcile.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
  pkg/reconciler/tenancy/workspace/workspace_controller.go
  pkg/server/controllers.go
  pkg/server/server.go
Labels: approved, lgtm, ok-to-test, size/L, release-note, dco-signoff: yes

#3141 :book: Update link to contributing guide
  README.md
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3142 :book: README.md: update videos
  README.md
Labels: approved, lgtm, size/S, dco-signoff: yes, release-note-none

#3145 :seedling: Bump to Go 1.22.5
  .github/workflows/docs-gen-and-push.yaml
  .github/workflows/goreleaser.yml
  .prow.yaml
  Dockerfile
  docs/content/contributing/index.md
Labels: approved, lgtm, size/S, release-note, dco-signoff: yes
