Repository kcp-dev/kcp, pull requests merged in 2024-03, with the labels that each got.

#3084 :sparkles: Move kubectl plugins into github.com/kcp-dev/kcp/cli module
  .gitignore
  .goreleaser.yaml
  Dockerfile
  FAQ.md
  Makefile
  cli/cmd/kubectl-kcp/cmd/kubectlKcp.go
  cli/cmd/kubectl-kcp/main.go
  cli/cmd/kubectl-workspace/main.go
  cli/go.mod
  cli/go.sum
  cli/pkg/OWNERS
  cli/pkg/base/options.go
  cli/pkg/bind/cmd/cmd.go
  cli/pkg/bind/plugin/bind.go
  cli/pkg/bind/plugin/bind_test.go
  cli/pkg/claims/cmd/cmd.go
  cli/pkg/claims/plugin/claims.go
  cli/pkg/crd/cmd/cmd.go
  cli/pkg/crd/plugin/snapshot.go
  cli/pkg/crd/plugin/snapshot_test.go
  cli/pkg/help/doc.go
  cli/pkg/helpers/helpers.go
  cli/pkg/helpers/helpers_test.go
  cli/pkg/workspace/cmd/cmd.go
  cli/pkg/workspace/plugin/kubeconfig.go
  cli/pkg/workspace/plugin/kubeconfig_test.go
  cli/pkg/workspace/plugin/scheme.go
  cmd/cache-server/main.go
  cmd/crd-puller/pull-crds.go
  cmd/kcp-core/kcpcore.go
  cmd/kcp/kcp.go
  contrib/kcp.code-workspace
  docs/content/developers/publishing-a-new-kcp-release.md
  docs/generators/cli-doc/gen-cli-doc.go
  go.mod
  pkg/cmd/OWNERS
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes

#3086 :book: Update link for community meetings in documentation
  docs/content/CONTRIBUTING.md
  docs/content/index.md
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3085 :sparkles: Index mounting ordering & few debug nits
  cli/pkg/workspace/plugin/kubeconfig.go
  config/crds/bootstrap.go
  pkg/index/index.go
  pkg/proxy/mapping.go
  pkg/proxy/mapping_test.go
  pkg/reconciler/cache/replication/replication_reconcile.go
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes

#3058 :sparkles: Add workspace mount battery & controller
  cmd/virtual-workspaces/command/cmd.go
  pkg/features/OWNERS
  pkg/features/kcp_features.go
  pkg/reconciler/tenancy/workspacemounts/README.md
  pkg/reconciler/tenancy/workspacemounts/workspacemounts_controller.go
  pkg/reconciler/tenancy/workspacemounts/workspacemounts_reconcile.go
  pkg/reconciler/tenancy/workspacemounts/workspacemounts_reconcile_updater.go
  pkg/server/controllers.go
  pkg/server/server.go
  sdk/apis/tenancy/v1alpha1/types_workspace.go
Labels: approved, lgtm, kind/api-change, size/L, release-note, dco-signoff: yes

#3089 :seedling: add mount test into index
  pkg/index/index_test.go
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3095 :bug: fix mount workspace reload
  pkg/index/index.go
  pkg/index/index_test.go
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes

#3094 :sparkles: add krew index build
  .github/workflows/goreleaser.yml
  .goreleaser.yaml
Labels: approved, lgtm, size/S, release-note, dco-signoff: yes

#3096 ✨ Feature: Re-enable webhook token authentication
  pkg/server/options/flags.go
  pkg/server/options/options.go
Labels: approved, lgtm, ok-to-test, size/M, release-note, dco-signoff: yes

#1905 📖 Document how storage keys are computed for workspaces
  docs/developers/registry.png
  docs/developers/storage-to-rest-patterns.md
Labels: approved, lgtm, size/M, dco-signoff: yes

#3101 :book: Update documentation with CNCF community group
  README.md
  docs/content/index.md
Labels: approved, lgtm, size/S, dco-signoff: yes, release-note-none

#3102 :book: Deploy most recent release documentation as 'latest' alias
  .github/workflows/docs-gen-and-push.yaml
  docs/scripts/deploy-docs.sh
  docs/scripts/serve-docs.sh
Labels: approved, lgtm, size/S, dco-signoff: yes, release-note-none

#3088 :sparkles: kubectl support ../../ & ..:..:
  cli/go.mod
  cli/go.sum
  cli/pkg/workspace/cmd/cmd.go
  cli/pkg/workspace/plugin/context.go
  cli/pkg/workspace/plugin/context_test.go
  cli/pkg/workspace/plugin/create.go
  cli/pkg/workspace/plugin/create_test.go
  cli/pkg/workspace/plugin/kubeconfig.go
  cli/pkg/workspace/plugin/tree.go
  cli/pkg/workspace/plugin/use.go
  cli/pkg/workspace/plugin/use_test.go
  go.mod
  go.sum
  sdk/apis/core/types.go
Labels: approved, lgtm, do-not-merge/hold, kind/api-change, size/XXL, release-note, dco-signoff: yes

#3103 :sparkles: cli/use: simplify tests and add tests for relative paths
  cli/pkg/workspace/plugin/use_test.go
Labels: approved, lgtm, kind/api-change, size/XL, dco-signoff: yes, release-note-none

#3105 :seedling: Publish RC candidates
  .github/workflows/goreleaser.yml
  .goreleaser.yaml
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none
