Repository kcp-dev/kcp, pull requests merged in 2024-05, with the labels that each got.

#3124 :bug: admission/webhooks: set kcp.io/cluster annotation on create
  pkg/admission/mutatingwebhook/plugin.go
  pkg/admission/validatingwebhook/plugin.go
  pkg/admission/webhook/OWNERS
  pkg/admission/webhook/generic_webhook.go
  pkg/admission/webhook/generic_webhook_test.go
  test/e2e/apibinding/apibinding_webhook_test.go
  test/e2e/conformance/webhook_test.go
  test/e2e/fixtures/webhook/webhook.go
Labels: approved, lgtm, kind/api-change, size/XL, release-note, dco-signoff: yes

#3125 :bug: Partially revert 3105 to not run goreleaser multiple times
  .github/workflows/goreleaser.yml
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3123 :seedling: Cleanup last traces of `ClusterWorkspaces` resource
  config/crds/tenancy.kcp.io_clusterworkspaces.yaml
  config/root-phase0/apiexport-tenancy.kcp.io.yaml
  config/root-phase0/apiresourceschema-clusterworkspaces.tenancy.kcp.io.yaml
  docs/content/concepts/quickstart-tenancy-and-apis.md
  docs/content/concepts/workspaces.md
  pkg/admission/logicalcluster/admission_test.go
  pkg/admission/shard/admission_test.go
  pkg/admission/workspace/admission_test.go
  pkg/server/bootstrap/identity.go
Labels: approved, lgtm, kind/api-change, size/XL, release-note, dco-signoff: yes

#3128 :book: Redirect aliases instead of symlinking to their targets
  docs/mkdocs.yml
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3129 :sparkles: apiexports: make SubjectAccessReview and LocalSubjectAccessReview claimable
  pkg/permissionclaim/permissionclaim_labeler.go
  pkg/virtual/apiexport/schemas/builtin/builtin.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: approved, lgtm, kind/api-change, size/L, release-note, dco-signoff: yes

#3131 :bug: apibindings/reconciler/labeller: fix informer error on non-persisted resources
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
Labels: approved, lgtm, size/S, dco-signoff: yes, release-note-none

#3133 ✨ cli: write diagnostics in `kubectl-workspace` to stderr
  cli/pkg/OWNERS
  cli/pkg/workspace/plugin/use.go
  cli/pkg/workspace/plugin/use_test.go
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes

#3135 ✨ Add version to kubectl-workspace
  cli/pkg/workspace/cmd/cmd.go
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#3132 ✨ Add installControllers and uninstallControllers for leaderElectionStopping
  pkg/reconciler/cache/replication/replication_controller.go
  pkg/reconciler/cache/replication/replication_reconcile.go
  pkg/server/controllers.go
  pkg/server/server.go
Labels: approved, lgtm, ok-to-test, size/XL, release-note, dco-signoff: yes
