Repository kcp-dev/kcp, pull requests merged in 2025-09, with the labels that each got.

#3553 Add CachedResourceSchemaSource for CachedResource
  cmd/virtual-workspaces/command/cmd.go
  config/crds/cache.kcp.io_cachedresources.yaml
  config/root-phase0/apiexport-cache.kcp.io.yaml
  config/root-phase0/apiresourceschema-cachedresources.cache.kcp.io.yaml
  pkg/cache/server/bootstrap/bootstrap.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/apis/apibinding/logical_cluster_lock.go
  pkg/reconciler/cache/cachedresources/cachedresources_controller.go
  pkg/reconciler/cache/cachedresources/cachedresources_reconcile.go
  pkg/reconciler/cache/cachedresources/cachedresources_reconcile_schema_replication.go
  pkg/reconciler/cache/cachedresources/cachedresources_reconcile_schema_replication_test.go
  pkg/reconciler/cache/cachedresources/cachedresources_reconcile_schemasource.go
  pkg/reconciler/cache/cachedresources/cachedresources_reconcile_schemasource_test.go
  pkg/server/controllers.go
  pkg/virtual/replication/builder/build.go
  pkg/virtual/replication/options/options.go
  sdk/apis/cache/v1alpha1/types_cachedresource.go
  sdk/apis/cache/v1alpha1/zz_generated.deepcopy.go
  sdk/client/applyconfiguration/cache/v1alpha1/apiresourceschemasource.go
  sdk/client/applyconfiguration/cache/v1alpha1/cachedresourceschemasource.go
  sdk/client/applyconfiguration/cache/v1alpha1/cachedresourcestatus.go
  sdk/client/applyconfiguration/cache/v1alpha1/crdschemasource.go
  sdk/client/applyconfiguration/utils.go
Labels: kind/feature, approved, lgtm, kind/api-change, size/XXL, dco-signoff: yes, release-note-none

#3561 Fix create-workspace --create-context pointing at the old workspace
  cli/pkg/workspace/plugin/context.go
  cli/pkg/workspace/plugin/create.go
  cli/pkg/workspace/plugin/create_test.go
Labels: kind/bug, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, release-note-none, area/cli

#3566 Move e2e mockoidc to authfixtures
  test/e2e/authentication/workspace_test.go
  test/e2e/fixtures/authfixtures/authfixtures.go
  test/e2e/fixtures/authfixtures/mockoidc.go
Labels: kind/feature, approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3568 Rename authentication.{kubernetes=>kcp}.io/cluster-name and add to workspace auth
  go.mod
  go.sum
  pkg/authentication/authenticators.go
  pkg/authorization/resolver_test.go
  pkg/proxy/proxy.go
  pkg/server/localproxy.go
  test/e2e/authentication/workspace_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note, dco-signoff: yes

#3560 Docs: added a note in kubectl-plugin docs to guide users when to use kubectl create workspace
  docs/content/setup/kubectl-plugin.md
Labels: approved, lgtm, ok-to-test, size/XS, kind/documentation, dco-signoff: yes, release-note-none

#3571 Filter extra keys containing `kcp.io` on per-workspace authentication
  docs/content/concepts/authentication/workspace.md
  pkg/authentication/extra.go
  pkg/authentication/extra_test.go
  pkg/authentication/groups_test.go
  pkg/authentication/index.go
  pkg/authentication/index_test.go
  test/e2e/authentication/workspace_test.go
  test/e2e/fixtures/authfixtures/mockoidc.go
Labels: approved, lgtm, kind/cleanup, size/L, dco-signoff: yes, release-note-none

#3558 Add security self-assessment
  docs/content/contributing/.pages
  docs/content/contributing/governance/security-self-assessment.md
Labels: approved, lgtm, kind/documentation, size/L, dco-signoff: yes, release-note-none

#3575 add a quick how to start section to README
  README.md
Labels: approved, lgtm, ok-to-test, size/S, kind/documentation, dco-signoff: yes, release-note-none

#3588 Add integrations page to documentation
  docs/content/setup/.pages
  docs/content/setup/integrations.md
Labels: approved, lgtm, size/M, kind/documentation, dco-signoff: yes, release-note-none

#3590 Fix some minor documentation typos
  docs/content/concepts/quickstart-tenancy-and-apis.md
  docs/content/contributing/governance/security-self-assessment.md
  docs/content/contributing/guides/rebasing-kubernetes.md
Labels: approved, lgtm, size/XS, kind/documentation, dco-signoff: yes, release-note-none

#3589 Fix sdk/testing panicking when used outside of a kcp clone
  cmd/sharded-test-server/cache.go
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/virtual.go
  cmd/test-server/kcp/shard.go
  sdk/testing/helpers/repo.go
  sdk/testing/server/fixture.go
  sdk/testing/server/metrics.go
  test/e2e/framework/flags.go
  test/e2e/framework/kcp.go
  test/e2e/framework/kubectl.go
Labels: kind/bug, approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3602 [release-0.28] Free disk space in release workflow
  .github/workflows/goreleaser.yml
Labels: approved, lgtm, kind/cleanup, size/L, dco-signoff: yes, release-note-none

#3603 [release-0.28] Fix goreleaser workflow YAML
  .github/workflows/goreleaser.yml
Labels: kind/bug, approved, lgtm, size/XS, dco-signoff: yes, release-note-none, kind/regression

#3608 Documentation fix: code documentation for required-groups annotation
  pkg/authorization/requiredgroups_authorizer.go
Labels: approved, lgtm, ok-to-test, size/XS, kind/documentation, dco-signoff: yes, release-note-none
