Repository kcp-dev/kcp, pull requests merged in 2025-04, with the labels that each got.

#3357 🐛 fix: mermaid mkdocs error and add make target to run mkdocs locally
  .gitignore
  Makefile
  docs/content/concepts/authentication/index.md
  docs/content/concepts/authentication/oidc.md
Labels: approved, lgtm, size/S, dco-signoff: yes, release-note-none

#3361 🐛 Do not set up local mini-front-proxy without additional mappings file
  pkg/server/localproxy.go
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#3363 🌱 Remove emojis from PR template and verification
  .github/pull_request_template.md
  .github/workflows/pr-verifier.yaml
Labels: approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, release-note-none

#3368 Fix npe
  pkg/admission/apiexport/admission.go
Labels: kind/bug, approved, lgtm, kind/api-change, size/XS, dco-signoff: yes, release-note-none, kind/regression

#3370 Wait for test-server processes to exit in make targets
  Makefile
Labels: approved, lgtm, kind/cleanup, size/XS, kind/flake, dco-signoff: yes, release-note-none

#3377 Clean gomod deps
  docs/generators/cli-doc/go.mod
  docs/generators/cli-doc/go.sum
Labels: approved, lgtm, kind/cleanup, size/L, dco-signoff: yes, release-note-none

#3379 Ensure all PRs into `cli/` are marked with area/cli label
  cli/OWNERS
Labels: approved, lgtm, size/XS, kind/documentation, dco-signoff: yes, release-note-none

#3380 Promote mounts to stable - part 1
  cli/pkg/workspace/plugin/create.go
  cli/pkg/workspace/plugin/create_test.go
  cli/pkg/workspace/plugin/use.go
  cli/pkg/workspace/plugin/use_test.go
  config/crds/tenancy.kcp.io_workspaces.yaml
  config/root-phase0/apiexport-tenancy.kcp.io.yaml
  config/root-phase0/apiresourceschema-workspaces.tenancy.kcp.io.yaml
  pkg/admission/workspace/admission.go
  pkg/admission/workspace/admission_test.go
  pkg/admission/workspacetypeexists/admission.go
  pkg/admission/workspacetypeexists/admission_test.go
  pkg/index/index.go
  pkg/index/index_test.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/tenancy/workspace/workspace_controller.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_metadata.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_phase.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling_test.go
  pkg/reconciler/tenancy/workspacemounts/workspace_indexes.go
  pkg/reconciler/tenancy/workspacemounts/workspacemounts_controller.go
  pkg/reconciler/tenancy/workspacemounts/workspacemounts_reconcile.go
  pkg/reconciler/tenancy/workspacemounts/workspacemounts_reconcile_updater.go
  pkg/virtual/framework/internalapis/fixtures/workspaces.yaml
  pkg/virtual/framework/internalapis/import_test.go
  sdk/apis/tenancy/v1alpha1/types_mounts.go
  sdk/apis/tenancy/v1alpha1/types_mounts_test.go
  sdk/apis/tenancy/v1alpha1/types_workspace.go
  sdk/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  sdk/client/applyconfiguration/tenancy/v1alpha1/mount.go
  sdk/client/applyconfiguration/tenancy/v1alpha1/objectreference.go
  sdk/client/applyconfiguration/tenancy/v1alpha1/workspacespec.go
  sdk/client/applyconfiguration/utils.go
  sdk/testing/workspaces.go
  test/e2e/mounts/crd_kubecluster.yaml
  test/e2e/mounts/mounts_machinery_test.go
  test/e2e/reconciler/workspacedeletion/controller_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/workspacetype/controller_test.go
Labels: kind/feature, approved, lgtm, kind/api-change, size/XXL, release-note, dco-signoff: yes, area/cli

#3386 kube-front-proxy/authentication: enable webhook and request header authn
  pkg/proxy/options/authentication.go
Labels: kind/feature, approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3385 kube-front-proxy: add named flags
  cmd/kcp-front-proxy/main.go
  cmd/kcp-front-proxy/options/options.go
  pkg/proxy/options/options.go
Labels: kind/feature, approved, lgtm, size/M, release-note, dco-signoff: yes
