Repository kcp-dev/kcp, pull requests merged in 2025-02, with the labels that each got.

#3286 📖 change the order of authorizers in the docs
  docs/content/concepts/authorization/authorizers.md
Labels: approved, lgtm, ok-to-test, size/M, dco-signoff: yes, release-note-none

#3287 ✨ authorizer: swap Webhook and RBAC in the default order
  docs/content/concepts/authorization/authorizers.md
  pkg/server/options/authorization.go
  test/e2e/authorizer/authorizationorder_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/authorizer/testdata/webhook1.kubeconfig
  test/e2e/authorizer/testdata/webhook2.kubeconfig
  test/e2e/authorizer/testdata/webhook3.kubeconfig
  test/e2e/authorizer/testdata/workspace1-resources.yaml
  test/e2e/authorizer/utils.go
  test/e2e/authorizer/webhook_test.go
Labels: approved, lgtm, ok-to-test, size/L, dco-signoff: yes, release-note-none

#3295 ✨ Enable structured authentication config flag
  contrib/kcp-dex/README.md
  contrib/kcp-dex/auth-config.yaml
  pkg/server/options/flags.go
Labels: approved, lgtm, ok-to-test, size/M, release-note, dco-signoff: yes

#3298 :bug: fix(admission): rename allOf to anyOf for type extension
  pkg/admission/workspacetypeexists/admission.go
Labels: approved, lgtm, ok-to-test, kind/api-change, size/XS, dco-signoff: yes, release-note-none

#3256 :sparkles: make APIExportEndpointSlice consumer aware
  Makefile
  config/crds/apis.kcp.io_apiexportendpointslices.yaml
  pkg/authorization/bootstrap/policy.go
  pkg/indexers/apiexport.go
  pkg/indexers/apiexport_test.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_controller.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_controller_test.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_indexes.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_reconcile.go
  pkg/reconciler/apis/apiexportendpointsliceurls/apiexportendpointsliceurls_controller.go
  pkg/reconciler/apis/apiexportendpointsliceurls/apiexportendpointsliceurls_controller_test.go
  pkg/reconciler/apis/apiexportendpointsliceurls/apiexportendpointsliceurls_reconcile.go
  pkg/reconciler/cache/replication/replication_controller.go
  pkg/server/controllers.go
  pkg/server/server.go
  sdk/apis/apis/v1alpha1/types_apiexportendpointslice.go
  sdk/client/applyconfiguration/apis/v1alpha1/apiexportendpointslicestatus.go
  test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
  test/e2e/reconciler/apiexportendpointslice/apiresourceschema_cowboys.yaml
Labels: approved, lgtm, kind/api-change, size/XXL, release-note, dco-signoff: yes

#3305 🌱 compress all build artifacts after e2e tests
  .prow.yaml
  hack/run-with-prow.sh
Labels: approved, lgtm, size/M, dco-signoff: yes, release-note-none

#3290 :seedling: Fix flaky SA test
  go.mod
  go.sum
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3246 ✨ Add OpenAPI v3 schema support to the Virtual Workspace framework
  pkg/virtual/framework/dynamic/apiserver/apiserver.go
  pkg/virtual/framework/dynamic/apiserver/openapi.go
  test/e2e/virtual/apiexport/openapi_test.go
Labels: approved, lgtm, size/XL, release-note, dco-signoff: yes

#3251 :bug: reconciler/apibinding: make group resources of APIBindings + CRD race-free
  config/shard/logicalcluster.yaml
  pkg/admission/crdnooverlappinggvr/crdnooverlappinggvr_admission.go
  pkg/admission/crdnooverlappinggvr/crdnooverlappinggvr_admission_test.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
  pkg/reconciler/apis/apibinding/conflict_checker.go
  pkg/reconciler/apis/apibinding/conflict_checker_test.go
  pkg/reconciler/apis/apibinding/logical_cluster_lock.go
  pkg/reconciler/apis/apibinding/logical_cluster_lock_test.go
  pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
  pkg/reconciler/apis/logicalclustercleanup/logicalclustercleanup_controller.go
  pkg/reconciler/apis/logicalclustercleanup/logicalclustercleanup_controller_test.go
  pkg/server/controllers.go
  pkg/server/server.go
  sdk/apis/apis/v1alpha1/types_apibinding.go
Labels: approved, lgtm, kind/api-change, size/XXL, release-note, dco-signoff: yes

#3308 :bug: Dockerfile: fix constructing URL for kubectl
  Dockerfile
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3311 :book: notice in TMC investigation docs
  docs/content/developers/investigations/transparent-multi-cluster.md
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3313 :book: remove superflous output from make install command
  docs/content/setup/kubectl-plugin.md
Labels: approved, lgtm, ok-to-test, size/XS, release-note, dco-signoff: yes

#3315 :bug: Fix update handler in pkg/proxy/index controller
  pkg/proxy/index/index_controller.go
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none
