Repository kcp-dev/kcp, pull requests merged in 2025-05, with the labels that each got.

#3388 Update sdk/testing/server
  sdk/testing/server/config.go
  sdk/testing/server/external.go
  sdk/testing/server/fixture.go
  sdk/testing/server/interface.go
  test/e2e/framework/inprocess.go
Labels: kind/feature, approved, lgtm, ok-to-test, kind/cleanup, size/L, release-note, dco-signoff: yes

#3392 Honour `WORK_DIR`
  Makefile
  cmd/test-server/kcp/shard.go
  cmd/test-server/main.go
  sdk/testing/config.go
  sdk/testing/kcp.go
  test/e2e/reconciler/cache/replication_test.go
Labels: kind/bug, approved, lgtm, ok-to-test, size/M, dco-signoff: yes, release-note-none

#3393 Fix (some of) the flakes
  .prow.yaml
  sdk/testing/workspaces.go
  test/e2e/apibinding/maximalpermissionpolicy_authorizer_test.go
  test/e2e/authorizer/serviceaccounts_test.go
  test/e2e/authorizer/utils.go
  test/e2e/authorizer/workspace_test.go
  test/e2e/conformance/crd_partial_metadata_test.go
  test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
  test/e2e/reconciler/workspacedeletion/controller_test.go
  test/e2e/watchcache/watchcache_enabled_test.go
Labels: kind/bug, approved, lgtm, ok-to-test, size/M, kind/flake, dco-signoff: yes, release-note-none

#3405 test: APIBinding: wrap listing VWs between shards with Eventually
  test/e2e/apibinding/apibinding_test.go
Labels: approved, lgtm, size/M, kind/flake, dco-signoff: yes, release-note-none

#3400 Bootstrap with pre-defined identities
  config/root-identities/bootstrap.go
  config/root-identities/namespace/bootstrap.go
  config/root-identities/namespace/namespace-kcp-system.yaml
  config/root-identities/secret-identity.yaml
  pkg/server/options/options.go
  pkg/server/server.go
Labels: kind/feature, approved, lgtm, size/L, release-note, dco-signoff: yes

#3316 ✨ Add DynamicRESTMapper
  Makefile
  hack/gen-patch-defaultrestmapper.sh
  pkg/reconciler/apis/apibinding/logical_cluster_lock.go
  pkg/reconciler/dynamicrestmapper/defaultrestmapper_kcp.go
  pkg/reconciler/dynamicrestmapper/defaultrestmapper_mutable.go
  pkg/reconciler/dynamicrestmapper/dynamicrestmapper.go
  pkg/reconciler/dynamicrestmapper/dynamicrestmapper_controller.go
  pkg/reconciler/dynamicrestmapper/dynamicrestmapper_test.go
  pkg/reconciler/dynamicrestmapper/forcluster.go
  pkg/reconciler/dynamicrestmapper/typemeta.go
  pkg/server/controllers.go
  pkg/server/server.go
Labels: kind/feature, approved, lgtm, size/XXL, dco-signoff: yes, release-note-none

#3408 Fix DynamicRestMapper bash
  hack/gen-patch-defaultrestmapper.sh
Labels: kind/bug, approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3391 update golangci-lint to v2
  .golangci.yaml
  Makefile
  cli/cmd/kubectl-create-workspace/cmd/kubectlCreateWorkspace.go
  cli/cmd/kubectl-ws/cmd/kubectlWs.go
  cli/pkg/workspace/plugin/context_test.go
  cli/pkg/workspace/plugin/create_test.go
  cli/pkg/workspace/plugin/use.go
  cli/pkg/workspace/plugin/use_test.go
  cmd/virtual-workspaces/options/options.go
  hack/third_party/github.com/spf13/cobra/doc/md_docs.go
  hack/third_party/github.com/spf13/cobra/doc/util.go
  pkg/admission/kubequota/kubequota_clusterworkspace_monitor.go
  pkg/admission/logicalcluster/admission.go
  pkg/cache/server/config.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/core/logicalclusterdeletion/deletion/logicalcluster_resource_deletor.go
  pkg/virtual/framework/forwardingregistry/store.go
  sdk/apis/apis/v1alpha1/types_apiexportendpointslice.go
  sdk/apis/apis/v1alpha1/types_apiresourceschema.go
  sdk/apis/apis/v1alpha2/types_apiexport_conversion.go
  sdk/apis/core/install/install.go
  sdk/apis/core/types.go
  sdk/apis/core/v1alpha1/logicalcluster_types.go
  sdk/apis/roundtrip_test.go
  sdk/apis/third_party/conditions/apis/conditions/v1alpha1/constants.go
  sdk/apis/third_party/conditions/apis/conditions/v1alpha1/register.go
  sdk/apis/third_party/conditions/util/conditions/getter.go
  sdk/apis/third_party/conditions/util/conditions/getter_test.go
  sdk/apis/third_party/conditions/util/conditions/matcher.go
  sdk/apis/third_party/conditions/util/conditions/matcher_test.go
  sdk/apis/third_party/conditions/util/conditions/matchers.go
  sdk/apis/third_party/conditions/util/conditions/merge.go
  sdk/apis/third_party/conditions/util/conditions/merge_strategies_test.go
  sdk/apis/third_party/conditions/util/conditions/merge_test.go
  sdk/apis/third_party/conditions/util/conditions/patch.go
  sdk/apis/third_party/conditions/util/conditions/patch_test.go
  sdk/apis/third_party/conditions/util/conditions/setter.go
  sdk/apis/third_party/conditions/util/conditions/setter_test.go
  sdk/testing/fuzzer.go
  sdk/testing/kcp.go
  sdk/testing/server/external.go
  sdk/testing/server/fixture.go
  sdk/testing/third_party/library-go/crypto/crypto.go
  sdk/testing/third_party/library-go/crypto/crypto_test.go
Labels: approved, lgtm, kind/api-change, size/XL, dco-signoff: yes, release-note-none, area/cli

#3372 Add `test/integration`
  .prow.yaml
  Makefile
  go.mod
  pkg/network/dialer.go
  pkg/server/config.go
  pkg/server/options/controllers.go
  sdk/testing/kcp.go
  sdk/testing/server/fixture.go
  test/e2e/framework/inprocess.go
  test/integration/framework/goleak.go
  test/integration/framework/goleak_test.go
  test/integration/framework/server.go
  test/integration/framework/server_test.go
Labels: kind/feature, approved, lgtm, ok-to-test, size/L, dco-signoff: yes, release-note-none

#3402 Implement support for verbs in PermissionClaims
  cli/pkg/workspace/plugin/use.go
  config/crds/apis.kcp.io_apibindings.yaml
  config/crds/apis.kcp.io_apiexports.yaml
  pkg/admission/apibinding/apibinding_admission.go
  pkg/admission/apibinding/apibinding_admission_test.go
  pkg/admission/apiexport/admission.go
  pkg/admission/apiexport/admission_test.go
  pkg/openapi/zz_generated.openapi.go
  pkg/virtual/apiexport/authorizer/binding.go
  pkg/virtual/apiexport/authorizer/binding_test.go
  pkg/virtual/apiexport/builder/build.go
  sdk/apis/apis/fuzzer/fuzzer.go
  sdk/apis/apis/v1alpha2/permissionclaims/labels.go
  sdk/apis/apis/v1alpha2/types_apiexport.go
  sdk/apis/apis/v1alpha2/types_apiexport_conversion.go
  sdk/apis/apis/v1alpha2/types_apiexport_conversion_test.go
  sdk/apis/apis/v1alpha2/zz_generated.conversion.go
  sdk/apis/apis/v1alpha2/zz_generated.deepcopy.go
  sdk/apis/roundtrip_test.go
  sdk/client/applyconfiguration/apis/v1alpha2/acceptablepermissionclaim.go
  sdk/client/applyconfiguration/apis/v1alpha2/permissionclaim.go
  test/e2e/apibinding/apibinding_logicalcluster_test.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
  test/e2e/reconciler/workspace/apibinding_initializer_test.go
  test/e2e/virtual/apiexport/authorizer_test.go
  test/e2e/virtual/apiexport/binding_test.go
  test/e2e/virtual/apiexport/openapi_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: kind/feature, approved, lgtm, kind/api-change, size/XXL, release-note, dco-signoff: yes, area/cli

#3418 Fix `--bind-address`
  cmd/sharded-test-server/cache.go
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/main.go
  cmd/sharded-test-server/virtual.go
  cmd/test-server/kcp/shard.go
  pkg/server/config.go
  pkg/server/options/options.go
  sdk/testing/config.go
  sdk/testing/kcp.go
  sdk/testing/server/config.go
  sdk/testing/server/fixture.go
  test/e2e/apibinding/apibinding_webhook_test.go
  test/e2e/conformance/webhook_test.go
  test/e2e/fixtures/webhook/webhook.go
  test/integration/framework/server.go
Labels: kind/bug, approved, lgtm, size/L, release-note, dco-signoff: yes

#3424 Close etcd after kcp
  test/e2e/framework/inprocess.go
Labels: kind/bug, approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3425 Point PermissionClaim verbs test to the correct workspace
  test/e2e/virtual/apiexport/binding_test.go
Labels: approved, lgtm, size/XS, kind/flake, dco-signoff: yes, release-note-none

#3414 Improvements for webhooks docs and tests
  docs/content/concepts/apis/admission-webhooks.md
  test/e2e/apibinding/apibinding_webhook_test.go
  test/e2e/conformance/webhook_test.go
  test/e2e/fixtures/webhook/webhook.go
Labels: approved, lgtm, kind/documentation, size/L, dco-signoff: yes, release-note-none

#3430 Serve both v1alpha1 and v1alpha2 APIBindings in APIExport VW, fix virtual workspace OpenAPI v3 panics
  pkg/virtual/apiexport/builder/build.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
  pkg/virtual/framework/dynamic/apiserver/openapi.go
  test/e2e/virtual/apiexport/apiresourceschema_cowboys_versions.yaml
  test/e2e/virtual/apiexport/binding_test.go
  test/e2e/virtual/apiexport/openapi_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note, dco-signoff: yes
