Repository kcp-dev/kcp, pull requests merged in 2025-07, with the labels that each got.

#3464 Add references on docs landing page to other projects
  README.md
  docs/content/index.md
  docs/mkdocs.yml
Labels: approved, lgtm, size/S, kind/documentation, dco-signoff: yes, release-note-none

#3471 Allow docker image to run without mounting `/.kcp`
  Dockerfile
Labels: kind/bug, approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3466 Add a bundled crds to the release
  .goreleaser.yaml
  config/crds/crd-bundler.sh
Labels: kind/feature, approved, lgtm, ok-to-test, size/M, release-note, dco-signoff: yes

#3473 Rely on user-installed tools
  .gitignore
  contrib/tilt/kind.sh
Labels: approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, release-note-none

#3476 Add admission plugin for CachedResources
  pkg/admission/cachedresource/admission.go
  pkg/admission/cachedresource/admission_test.go
  pkg/admission/plugins.go
  pkg/reconciler/cache/cachedresources/indexers.go
  pkg/virtual/framework/transforming/transformer_test.go
Labels: kind/bug, approved, lgtm, kind/api-change, size/L, release-note, dco-signoff: yes

#3475 Update kcp-dev/code-generator and /client-go
  cli/go.mod
  cli/go.sum
  go.mod
  go.sum
  sdk/client/clientset/versioned/cluster/clientset.go
  sdk/client/listers/apis/v1alpha1/apibinding.go
  sdk/client/listers/apis/v1alpha1/apiconversion.go
  sdk/client/listers/apis/v1alpha1/apiexport.go
  sdk/client/listers/apis/v1alpha1/apiexportendpointslice.go
  sdk/client/listers/apis/v1alpha1/apiresourceschema.go
  sdk/client/listers/apis/v1alpha2/apibinding.go
  sdk/client/listers/apis/v1alpha2/apiexport.go
  sdk/client/listers/cache/v1alpha1/cachedobject.go
  sdk/client/listers/cache/v1alpha1/cachedresource.go
  sdk/client/listers/cache/v1alpha1/cachedresourceendpointslice.go
  sdk/client/listers/core/v1alpha1/logicalcluster.go
  sdk/client/listers/core/v1alpha1/shard.go
  sdk/client/listers/tenancy/v1alpha1/workspace.go
  sdk/client/listers/tenancy/v1alpha1/workspacetype.go
  sdk/client/listers/topology/v1alpha1/partition.go
  sdk/client/listers/topology/v1alpha1/partitionset.go
  sdk/go.mod
  sdk/go.sum
  test/e2e/fixtures/wildwest/client/clientset/versioned/cluster/clientset.go
  test/e2e/fixtures/wildwest/client/listers/wildwest/v1alpha1/cowboy.go
  test/e2e/fixtures/wildwest/client/listers/wildwest/v1alpha1/sheriff.go
  test/integration/framework/goleak.go
Labels: approved, lgtm, kind/cleanup, size/L, release-note, dco-signoff: yes, area/cli

#3489 Improve authorizer webhook tests
  test/e2e/authorizer/authorizationorder_test.go
  test/e2e/authorizer/utils.go
Labels: approved, lgtm, size/M, kind/flake, dco-signoff: yes, release-note-none

#3491 Prevent workspace deletion leaks
  go.mod
  go.sum
  pkg/admission/mutatingwebhook/plugin.go
  pkg/admission/validatingwebhook/plugin.go
  pkg/informer/informer.go
  pkg/reconciler/cache/cachedresources/cachedresources_reconcile_replication.go
  pkg/reconciler/garbagecollector/garbagecollector_controller.go
  pkg/reconciler/kubequota/kubequota_controller.go
  test/integration/framework/goleak.go
  test/integration/framework/goleak_test.go
  test/integration/framework/leak_test.go
  test/integration/workspace/leak_test.go
Labels: kind/bug, approved, lgtm, kind/api-change, size/L, release-note, dco-signoff: yes

#3501 Normalize events via claims
  pkg/permissionclaim/permissionclaim_labeler.go
Labels: kind/bug, approved, lgtm, size/S, release-note, dco-signoff: yes
