Repository kcp-dev/kcp, pull requests merged in 2025-03, with the labels that each got.

#3312 :sparkles: hack/verify-go-modules.sh: compare dependency versions
  hack/verify-go-modules.sh
Labels: approved, lgtm, size/M, dco-signoff: yes, release-note-none

#3314 :seedling: Limit several jobs to not run for doc changes
  .prow.yaml
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3321 :seedling: test/e2e: cleanup framework
  cmd/sharded-test-server/cache.go
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/virtual.go
  cmd/test-server/kcp/shard.go
  test/e2e/apibinding/apibinding_webhook_test.go
  test/e2e/audit/audit_log_test.go
  test/e2e/authorizer/authorizationorder_test.go
  test/e2e/authorizer/workspace_test.go
  test/e2e/cache/cache_server_test.go
  test/e2e/conformance/webhook_test.go
  test/e2e/framework/accessory.go
  test/e2e/framework/bind.go
  test/e2e/framework/env/env.go
  test/e2e/framework/expect.go
  test/e2e/framework/flags.go
  test/e2e/framework/helpers/repo.go
  test/e2e/framework/kcp.go
  test/e2e/framework/kubectl.go
  test/e2e/framework/server/config.go
  test/e2e/framework/server/external.go
  test/e2e/framework/server/fixture.go
  test/e2e/framework/server/interface.go
  test/e2e/framework/server/metrics.go
  test/e2e/framework/server/port.go
  test/e2e/framework/server/ready.go
  test/e2e/framework/server/temp.go
  test/e2e/framework/util.go
  test/e2e/framework/workspaces.go
  test/e2e/homeworkspaces/home_workspaces_test.go
  test/e2e/reconciler/cache/helpers.go
  test/e2e/reconciler/cache/replication_test.go
  test/e2e/reconciler/shard/controller_test.go
  test/e2e/reconciler/workspace/controller_test.go
  test/e2e/reconciler/workspacedeletion/controller_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm, size/XXL, dco-signoff: yes, release-note-none

#3322 :seedling: test/e2e/framework: move more helpers
  test/e2e/apibinding/apibinding_deletion_test.go
  test/e2e/apibinding/apibinding_logicalcluster_test.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
  test/e2e/apibinding/apibinding_protected_test.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/apibinding/apibinding_webhook_test.go
  test/e2e/apibinding/maximalpermissionpolicy_authorizer_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/authorizer/scopes_test.go
  test/e2e/authorizer/serviceaccounts_test.go
  test/e2e/authorizer/utils.go
  test/e2e/authorizer/workspace_test.go
  test/e2e/conformance/crd_partial_metadata_test.go
  test/e2e/fixtures/apifixtures/apibinding.go
  test/e2e/fixtures/apifixtures/sheriffs.go
  test/e2e/framework/helpers/eventually.go
  test/e2e/framework/helpers/kubeconfig.go
  test/e2e/framework/util.go
  test/e2e/framework/workspaces.go
  test/e2e/garbagecollector/garbagecollector_test.go
  test/e2e/mounts/mounts_machinery_test.go
  test/e2e/quota/quota_test.go
  test/e2e/reconciler/apiexport/apiexport_controller_test.go
  test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
  test/e2e/reconciler/cache/helpers.go
  test/e2e/reconciler/cache/replication_test.go
  test/e2e/reconciler/partitionset/partitionset_test.go
  test/e2e/reconciler/workspace/controller_test.go
  test/e2e/reconciler/workspacedeletion/controller_test.go
  test/e2e/virtual/apiexport/authorizer_test.go
  test/e2e/virtual/apiexport/binding_test.go
  test/e2e/virtual/apiexport/openapi_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
  test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
  test/e2e/watchcache/watchcache_enabled_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm, size/XL, dco-signoff: yes, release-note-none

#3317 :seedling: hack/verify-go-modules.sh: don't run pager with git diff
  hack/verify-go-modules.sh
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3326 :sparkles: Build apigen on releases
  .github/workflows/goreleaser.yml
  .goreleaser.yaml
  Makefile
Labels: approved, lgtm, size/S, release-note, dco-signoff: yes

#3331 :seedling: Update to Go 1.23.7
  .github/workflows/docs-gen-and-push.yaml
  .prow.yaml
  Dockerfile
  cli/go.mod
  cli/go.sum
  docs/content/contributing/index.md
  docs/generators/cli-doc/go.mod
  docs/generators/cli-doc/go.sum
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes

#3332 :seedling: Use github.com/kcp-dev/embeddedetcd
  cmd/cache-server/main.go
  cmd/kcp/kcp.go
  docs/content/contributing/index.md
  docs/generators/cli-doc/go.mod
  docs/generators/cli-doc/go.sum
  go.mod
  go.sum
  pkg/cache/server/config.go
  pkg/cache/server/options/options.go
  pkg/embeddedetcd/config.go
  pkg/embeddedetcd/options/embedded.go
  pkg/embeddedetcd/server.go
  pkg/server/config.go
  pkg/server/options/options.go
  test/e2e/framework/server/fixture.go
  test/e2e/reconciler/cache/helpers.go
Labels: approved, lgtm, size/XL, dco-signoff: yes, release-note-none

#3335 :seedling: Make exposed testing package work outside
  sdk/testing/config.go
  sdk/testing/doc.go
  sdk/testing/kcp.go
  sdk/testing/server/config.go
  sdk/testing/server/fixture.go
  sdk/testing/server/ready.go
  test/e2e/framework/flags.go
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3334 :sparkles: Add --{accept/reject}-permission-claim flag to bind cli
  cli/pkg/bind/cmd/cmd.go
  cli/pkg/bind/plugin/bind.go
  cli/pkg/bind/plugin/bind_test.go
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes

#3328 🌱 Add kube feature gate for global service account
  go.mod
  go.sum
  pkg/authorization/resolver_test.go
Labels: approved, lgtm, ok-to-test, size/L, release-note, dco-signoff: yes

#3337 :bug: cli/bind: fix parsing permission claims passed by cli args
  cli/pkg/bind/cmd/cmd.go
  cli/pkg/bind/plugin/bind.go
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3339 [release-0.26] 🐛 Add binding authorizer to APIExport virtual workspace
  pkg/virtual/apiexport/authorizer/binding.go
  pkg/virtual/apiexport/builder/build.go
  pkg/virtual/apiexport/options/options.go
  pkg/virtual/options/options.go
  test/e2e/virtual/apiexport/authorizer_test.go
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes

#3338 :bug: Add binding authorizer to APIExport virtual workspace
  pkg/virtual/apiexport/authorizer/binding.go
  pkg/virtual/apiexport/builder/build.go
  pkg/virtual/apiexport/options/options.go
  pkg/virtual/options/options.go
  test/e2e/virtual/apiexport/authorizer_test.go
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes

#3340 [release-0.26] :bug: Use normal upload-artifact action
  .github/workflows/goreleaser.yml
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3343 🌱 update goreleaser config to version 2
  .gitignore
  .goreleaser.yaml
Labels: approved, lgtm, size/S, dco-signoff: yes, release-note-none

#3344 :bug: Typo in example
  cli/pkg/bind/cmd/cmd.go
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3345 :bug: Fix purge job
  .github/workflows/gh-image-purge.yaml
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3346 :book: Update docs
  docs/content/concepts/quickstart-tenancy-and-apis.md
Labels: approved, lgtm, ok-to-test, size/S, dco-signoff: yes, release-note-none

#3304 📖 Add authentication document page
  docs/content/concepts/.pages
  docs/content/concepts/authentication/index.md
  docs/content/concepts/authentication/oidc.md
  pkg/server/options/authentication.go
Labels: approved, lgtm, ok-to-test, size/L, dco-signoff: yes, release-note-none

#3349 :bug: Bump WorkspaceType `APIResourceSchema` name
  Makefile
  config/root-phase0/apiexport-tenancy.kcp.io.yaml
  config/root-phase0/apiresourceschema-workspacetypes.tenancy.kcp.io.yaml
  hack/verify-apiresourceschemas.sh
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes

#3207 📖 Add APIBindings example
  docs/content/concepts/apis/exporting-apis.md
Labels: approved, lgtm, ok-to-test, kind/api-change, size/M, dco-signoff: yes, release-note-none

#3352 :seedling: Update `github.com/golang-jwt/jwt/v4` to v4.5.2
  go.mod
  go.sum
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#3354 :seedling: Pin GitHub Actions workflows to commits
  .github/dependabot.yaml
  .github/workflows/add-to-project.yml
  .github/workflows/docs-gen-and-push.yaml
  .github/workflows/gh-image-purge.yaml
  .github/workflows/goreleaser.yml
  .github/workflows/pr-verifier.yaml
Labels: approved, lgtm, size/M, dco-signoff: yes, release-note-none
