Repository kcp-dev/kcp, pull requests merged in 2025-01, with the labels that each got.

#3239 :seedling: Bump buildah image to v1.38.0
  .prow.yaml
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3240 :sparkles: Add wget to final image
  Dockerfile
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#3226 :sparkles: Add image prefix for PRs.
  .github/workflows/gh-image-purge.yaml
  hack/build-image.sh
Labels: approved, lgtm, size/S, dco-signoff: yes, release-note-none

#3241 🌱 initializingworkspaces virtual workspace unit tests
  pkg/virtual/initializingworkspaces/builder/build.go
  pkg/virtual/initializingworkspaces/builder/build_test.go
Labels: approved, lgtm, ok-to-test, size/L, dco-signoff: yes, release-note-none

#3238 :book: docs: rework the Terminology document
  docs/content/concepts/terminology.md
Labels: approved, lgtm, ok-to-test, size/L, dco-signoff: yes, release-note-none

#3243 :bug: Add additional impersonation check
  pkg/server/handler.go
  pkg/server/handler_test.go
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3247 📖 docs: workspace initializers and initializingworkspaces virtual workspace
  docs/content/concepts/workspaces/.pages
  docs/content/concepts/workspaces/workspace-initialization.md
Labels: approved, lgtm, ok-to-test, size/M, dco-signoff: yes, release-note-none

#3249 :seedling: server: move filters into filters package
  pkg/proxy/server.go
  pkg/server/apiexport_context.go
  pkg/server/apiextensions.go
  pkg/server/config.go
  pkg/server/filters/filters.go
  pkg/server/filters/impersonation.go
  pkg/server/filters/inactivelogicalcluster.go
  pkg/server/filters/requestidentity.go
  pkg/server/filters/requestidentity_test.go
  pkg/server/filters/serviceaccounts.go
  pkg/server/filters/useragent.go
  pkg/server/filters/wildcard.go
  pkg/server/handler.go
  pkg/server/handler_test.go
Labels: approved, lgtm, size/XXL, dco-signoff: yes, release-note-none

#3250 📖 docs: fix list in workspace initialization page
  docs/content/concepts/workspaces/workspace-initialization.md
Labels: approved, lgtm, ok-to-test, size/XS, dco-signoff: yes, release-note-none

#3235 ✨ auth: Implement user scopes
  docs/content/concepts/authorization/authorizers.md
  go.mod
  go.sum
  pkg/authorization/requiredgroups_authorizer.go
  pkg/authorization/requiredgroups_authorizer_test.go
  pkg/authorization/workspace_content_authorizer.go
  pkg/authorization/workspace_content_authorizer_test.go
  pkg/server/config.go
  pkg/server/filters/impersonation.go
  pkg/server/filters/impersonation_test.go
  pkg/virtual/initializingworkspaces/builder/build.go
  test/e2e/authorizer/impersonate_test.go
  test/e2e/authorizer/scopes_test.go
  test/e2e/reconciler/workspace/apibinding_initializer_test.go
  test/e2e/reconciler/workspace/clusterrole_cowboys.yaml
  test/e2e/reconciler/workspace/clusterrolebinding_cowboys.yaml
Labels: approved, lgtm, size/XXL, release-note, dco-signoff: yes

#3253 :book: Add CSS to properly stylize CRD reference
  docs/mkdocs.yml
  docs/overrides/stylesheets/crd.css
  docs/overrides/stylesheets/kcp.css
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3263 :bug: Correctly check original groups against `system:masters` in scope filter
  pkg/server/filters/impersonation.go
  pkg/server/filters/impersonation_test.go
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3264 :bug: Remove scope from initializingworkspaces virtual workspace
  pkg/virtual/initializingworkspaces/builder/build.go
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none

#3266 :seedling: authorizers: misc prefactorings
  pkg/authorization/maximal_permission_policy_authorizer.go
  pkg/authorization/requiredgroups_authorizer.go
  pkg/authorization/workspace_content_authorizer.go
  pkg/authorization/workspace_content_authorizer_test.go
  pkg/server/options/authorization.go
  test/e2e/authorizer/serviceaccounts_test.go
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3267 :bug: impersonation: add missing privileged groups
  pkg/server/filters/impersonation.go
  pkg/server/filters/impersonation_test.go
Labels: approved, lgtm, size/M, dco-signoff: yes, release-note-none

#3269 :seedling: authorizer/content: simplify as scoping (and later warrant) logic moved into the resolver
  Makefile
  pkg/authorization/workspace_content_authorizer.go
  pkg/authorization/workspace_content_authorizer_test.go
  pkg/openapi/zz_generated.openapi.go
  pkg/reconciler/kubequota/kubequota_controller.go
  pkg/reconciler/tenancy/workspacemounts/workspacemounts_controller.go
  pkg/reconciler/tenancy/workspacemounts/workspacemounts_reconcile.go
  pkg/reconciler/tenancy/workspacemounts/workspacemounts_reconcile_updater.go
  pkg/server/controllers.go
  sdk/apis/tenancy/v1alpha1/types_mounts.go
  sdk/apis/tenancy/v1alpha1/types_mounts_test.go
  sdk/apis/tenancy/v1alpha1/types_workspace.go
  sdk/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  test/e2e/apibinding/apibinding_logicalcluster_test.go
  test/e2e/authorizer/serviceaccounts_test.go
  test/e2e/framework/kcp.go
  test/e2e/mounts/mounts_machinery_test.go
Labels: approved, lgtm, kind/api-change, size/XL, dco-signoff: yes, release-note-none

#3268 :seedling: e2e: add SelfSubjectRulesReview test
  test/e2e/authorizer/scopes_test.go
Labels: approved, lgtm, kind/api-change, size/L, dco-signoff: yes, release-note-none

#3156 :sparkles: Add user warrants
  docs/content/concepts/authorization/authorizers.md
  go.mod
  go.sum
  pkg/authorization/deep_sar.go
  pkg/authorization/maximal_permission_policy_authorizer.go
  pkg/authorization/requiredgroups_authorizer.go
  pkg/authorization/resolver_test.go
  pkg/authorization/warrants.go
  pkg/authorization/workspace_content_authorizer.go
  pkg/server/options/authorization.go
  pkg/virtual/apiexport/builder/build.go
  test/e2e/authorizer/scopes_test.go
  test/e2e/virtual/apiexport/binding_test.go
Labels: approved, lgtm, kind/api-change, size/XL, release-note, dco-signoff: yes

#3273 :bug: index: fix how error codes are stored for unavailable workspaces
  pkg/index/index.go
  pkg/index/index_test.go
  test/e2e/authorizer/serviceaccounts_test.go
  test/e2e/mounts/mounts_machinery_test.go
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3272 :seedling: Configure prow artifacts correctly
  .prow.yaml
  Makefile
  cmd/sharded-test-server/cache.go
  cmd/test-server/main.go
  test/e2e/framework/util.go
Labels: approved, lgtm, size/M, dco-signoff: yes, release-note-none

#3276 :seedling: Noop: Clean code and organize imports
  cmd/cache-server/main.go
  cmd/kcp-front-proxy/main.go
  cmd/kcp/kcp.go
  cmd/sharded-test-server/main.go
  config/crds/bootstrap.go
  config/helpers/bootstrap.go
  pkg/crdpuller/discovery.go
  pkg/reconciler/apis/apibinding/apibinding_reconcile.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
  pkg/reconciler/core/logicalcluster/logicalcluster_reconcile.go
  pkg/reconciler/tenancy/workspacemounts/workspacemounts_reconcile.go
  pkg/server/bootstrap/identity.go
  pkg/server/controllers.go
  pkg/virtual/framework/internalapis/import.go
  sdk/apis/apis/v1alpha1/crd_to_apiresourceschema.go
  test/e2e/framework/expect.go
  test/e2e/framework/kcp.go
  test/e2e/reconciler/cache/helpers.go
Labels: approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3277 :sparkles: Replicate APIExportEndpointSlices via cache server for consumer awarn…
  pkg/cache/server/bootstrap/bootstrap.go
  pkg/reconciler/cache/replication/replication_controller.go
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#3278 :seedling: noop: Fixup imports to be consistent.
  pkg/admission/kubequota/kubequota_clusterworkspace_monitor.go
  pkg/features/kcp_features.go
  pkg/proxy/index/index_controller.go
  pkg/proxy/proxy.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_controller.go
  pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
  pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller.go
  pkg/reconciler/apis/identitycache/api_export_identity_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
  pkg/reconciler/apis/replicatelogicalcluster/replicatelogicalcluster_controller.go
  pkg/reconciler/cache/labelclusterrolebindings/labelclusterrolebinding_controller.go
  pkg/reconciler/cache/labelclusterroles/labelclusterrole_controller.go
  pkg/reconciler/cache/labelclusterroles/labelclusterrole_reconcile.go
  pkg/reconciler/cache/labellogicalcluster/labellogicalcluster_controller.go
  pkg/reconciler/cache/replication/replication_controller.go
  pkg/reconciler/cache/replication/replication_reconcile.go
  pkg/reconciler/core/logicalcluster/logicalcluster_controller.go
  pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
  pkg/reconciler/core/shard/shard_controller.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
  pkg/reconciler/tenancy/logicalcluster/logicalcluster_controller.go
  pkg/reconciler/tenancy/replicatelogicalcluster/replicatelogicalcluster_controller.go
  pkg/reconciler/tenancy/workspace/workspace_controller.go
  pkg/reconciler/tenancy/workspacemounts/workspacemounts_controller.go
  pkg/reconciler/tenancy/workspacetype/workspacetype_controller.go
  pkg/reconciler/topology/partitionset/partitionset_controller.go
  pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
Labels: approved, lgtm, kind/api-change, size/L, dco-signoff: yes, release-note-none

#3275 :seedling: stop the bleeding: e2e/sharded: temporarily disable service account lookup
  cmd/sharded-test-server/shard.go
Labels: approved, lgtm, size/XS, dco-signoff: yes, release-note-none
