Repository kcp-dev/kcp, pull requests merged in 2025-08, with the labels that each got.

#3492 Make deletion relationship between workspace and logicalcluster one way
  pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_deletion.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_deletion_test.go
  test/e2e/workspace/deletion_test.go
Labels: kind/bug, approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3483 [tilt] Add script to generate a kubeconfig targeting the frontproxy
  contrib/tilt/generate-frontproxy-admin-kubeconfig.sh
Labels: kind/feature, approved, lgtm, size/M, dco-signoff: yes, release-note-none

#3516 replace NewOrganizationFixture with NewWorkspaceFixture
  test/e2e/apibinding/apibinding_deletion_test.go
  test/e2e/apibinding/apibinding_logicalcluster_test.go
  test/e2e/apibinding/apibinding_permissionclaims_test.go
  test/e2e/apibinding/apibinding_protected_test.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/apibinding/apibinding_webhook_test.go
  test/e2e/apibinding/default_apibinding_test.go
  test/e2e/apibinding/maximalpermissionpolicy_authorizer_test.go
  test/e2e/audit/audit_log_test.go
  test/e2e/authorizer/authorizer_test.go
  test/e2e/authorizer/impersonate_test.go
  test/e2e/authorizer/rootcacertconfigmap_test.go
  test/e2e/authorizer/scopes_test.go
  test/e2e/authorizer/serviceaccounts_test.go
  test/e2e/authorizer/workspace_test.go
  test/e2e/conformance/crd_partial_metadata_test.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/conformance/metadata_test.go
  test/e2e/conformance/validatingadmissionpolicy_test.go
  test/e2e/conformance/webhook_test.go
  test/e2e/customresourcedefinition/customresourcedefinition_test.go
  test/e2e/garbagecollector/garbagecollector_test.go
  test/e2e/openapi/openapi_test.go
  test/e2e/quota/quota_test.go
  test/e2e/reconciler/apiexport/apiexport_controller_test.go
  test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
  test/e2e/reconciler/cache/replication_test.go
  test/e2e/reconciler/partitionset/partitionset_test.go
  test/e2e/reconciler/workspace/apibinding_initializer_test.go
  test/e2e/reconciler/workspace/controller_test.go
  test/e2e/reconciler/workspacedeletion/controller_test.go
  test/e2e/virtual/apiexport/authorizer_test.go
  test/e2e/virtual/apiexport/binding_test.go
  test/e2e/virtual/apiexport/openapi_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
  test/e2e/virtual/replication/virtualworkspace_test.go
  test/e2e/watchcache/watchcache_enabled_test.go
  test/e2e/workspacetype/controller_test.go
Labels: approved, lgtm, kind/cleanup, size/L, dco-signoff: yes, release-note-none

#3538 fix flaky TestServiceAccounts
  test/e2e/authorizer/serviceaccounts_test.go
Labels: approved, lgtm, size/S, kind/flake, dco-signoff: yes, release-note-none

#3546 Bump to kcp-1.33.1-1
  go.mod
  go.sum
Labels: kind/bug, approved, lgtm, size/L, dco-signoff: yes, release-note-none

#3548 [release-0.28] Fix `Cluster` kind and multiple `/clusters/` in URLs
  pkg/server/config.go
  pkg/server/filters/filters.go
  pkg/server/filters/filters_test.go
  pkg/server/filters/inactivelogicalcluster.go
  pkg/server/requestinfo/kcp_request_info_resolver.go
  test/e2e/server/url_test.go
  test/e2e/workspace/inactive_test.go
Labels: kind/bug, approved, lgtm, kind/cleanup, size/L, release-note, dco-signoff: yes

#3549 Update `github.com/golang-jwt/jwt/v5` and `github.com/go-jose/go-jose/v3`
  go.mod
  go.sum
Labels: approved, lgtm, kind/cleanup, size/S, dco-signoff: yes, release-note-none

#3551 Add CEL validation to WorkspaceAuthenticationConfiguration
  config/crds/tenancy.kcp.io_workspaceauthenticationconfigurations.yaml
  config/root-phase0/apiexport-tenancy.kcp.io.yaml
  config/root-phase0/apiresourceschema-workspaceauthenticationconfigurations.tenancy.kcp.io.yaml
  pkg/openapi/zz_generated.openapi.go
  sdk/apis/tenancy/v1alpha1/types_workspaceauthentication.go
  test/e2e/authentication/workspace_test.go
Labels: kind/bug, approved, lgtm, kind/api-change, size/L, dco-signoff: yes, release-note-none

#3554 Add new kcp-dev Slack channel to getting in touch section
  README.md
  docs/content/index.md
Labels: approved, lgtm, size/M, kind/documentation, dco-signoff: yes, release-note-none

#3557 Update goleak test
  test/integration/workspace/leak_test.go
Labels: approved, lgtm, kind/cleanup, size/M, kind/flake, dco-signoff: yes, release-note-none

#3482 Add kcp_indexed_logicalclusters metric
  pkg/index/index.go
  pkg/index/metrics.go
Labels: kind/feature, approved, lgtm, size/M, release-note, dco-signoff: yes
