Repository kcp-dev/kcp, pull requests merged in 2025-06, with the labels that each got.

#3434 Remove VOLUME directive from Dockerfile
  Dockerfile
Labels: kind/bug, approved, lgtm, kind/cleanup, size/XS, release-note, dco-signoff: yes

#3436 CachedResources reconciler should check for missing label selector
  pkg/reconciler/cache/cachedresources/cachedresources_reconcile.go
  pkg/reconciler/cache/cachedresources/cachedresources_reconcile_replication.go
Labels: kind/bug, approved, lgtm, size/S, dco-signoff: yes, release-note-none

#3440 Add the PermissionClaims verbs to the docs
  docs/content/concepts/apis/exporting-apis.md
  docs/content/concepts/quickstart-tenancy-and-apis.md
Labels: approved, lgtm, size/M, kind/documentation, dco-signoff: yes, release-note-none

#3411 Disable APIExport VirtualWorkspace URL population
  Makefile
  pkg/features/kcp_features.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/reconciler/apis/apiexport/apiexport_controller_test.go
  pkg/reconciler/apis/apiexport/apiexport_reconcile.go
  pkg/server/controllers.go
  pkg/server/server.go
  sdk/apis/apis/v1alpha2/types_apiexport.go
  test/e2e/apibinding/apibinding_logicalcluster_test.go
  test/e2e/apibinding/apibinding_protected_test.go
  test/e2e/apibinding/apibinding_test.go
  test/e2e/framework/util.go
  test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
  test/e2e/virtual/apiexport/authorizer_test.go
  test/e2e/virtual/apiexport/binding_test.go
  test/e2e/virtual/apiexport/openapi_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: kind/feature, approved, lgtm, kind/api-change, size/XL, release-note, dco-signoff: yes, kind/deprecation

#3439 Authorize server-side apply as create in `forwardingregistry`
  pkg/virtual/framework/forwardingregistry/store.go
  test/e2e/virtual/apiexport/binding_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note, dco-signoff: yes

#3433 Rework test/integration framework
  sdk/testing/server/config.go
  sdk/testing/server/external.go
  sdk/testing/server/fixture.go
  test/e2e/framework/inprocess.go
  test/integration/framework/server.go
  test/integration/framework/server_test.go
Labels: kind/feature, approved, lgtm, kind/cleanup, size/L, release-note, dco-signoff: yes

#3441 Use 'core' group to replicate core API objects
  pkg/reconciler/cache/cachedresources/cachedresources_reconcile.go
  pkg/reconciler/cache/cachedresources/replication/replication_reconcile.go
Labels: kind/bug, approved, lgtm, size/S, dco-signoff: yes, release-note-none

#3448 Implement kcptestingserver.RunningServer
  test/integration/framework/server.go
Labels: kind/feature, approved, lgtm, size/M, dco-signoff: yes, release-note-none

#3447 Start using dynamicRestMapper & fix it usage
  pkg/reconciler/apis/logicalclustercleanup/logicalclustercleanup_controller.go
  pkg/reconciler/dynamicrestmapper/dynamicrestmapper_controller.go
  pkg/reconciler/dynamicrestmapper/forcluster.go
  pkg/reconciler/tenancy/workspacemounts/workspace_indexes.go
  pkg/server/controllers.go
  test/integration/dynamicrestmapper/assets/assets.go
  test/integration/dynamicrestmapper/assets/crd_kubecluster.yaml
  test/integration/dynamicrestmapper/dynamicrestmapper_test.go
Labels: approved, lgtm, kind/cleanup, size/L, release-note, dco-signoff: yes

#3438 Do not set the owner annotation on `LogicalClusters` to empty value
  pkg/reconciler/tenancy/logicalcluster/logicalcluster_controller.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
Labels: kind/bug, approved, lgtm, size/S, release-note, dco-signoff: yes

#3450 Add Upbound as adopter
  ADOPTERS.md
Labels: approved, lgtm, size/XS, kind/documentation, dco-signoff: yes, release-note-none

#3437 docs: Convert ASCII diagrams to mermaid
  docs/content/concepts/apis/admission-webhooks.md
  docs/content/concepts/apis/exporting-apis.md
Labels: approved, lgtm, ok-to-test, kind/cleanup, kind/documentation, size/L, dco-signoff: yes, release-note-none

#3454 Bump github.com/golang-jwt/jwt/v4 to 4.5.2
  go.mod
  go.sum
Labels: kind/bug, approved, lgtm, size/XS, release-note, dco-signoff: yes

#3458 fix a bunch of typos
  .typos.toml
  GOVERNANCE.md
  Makefile
  docs/content/concepts/authorization/authorizers.md
  docs/content/concepts/sharding/shards.md
  docs/content/concepts/workspaces/workspace-types.md
  docs/content/contributing/index.md
  pkg/admission/workspace/admission.go
  pkg/authorization/workspace_content_authorizer_test.go
  pkg/network/dialer.go
  pkg/network/dialer_linux.go
  pkg/network/dialer_other.go
  pkg/reconciler/apis/apibinding/logical_cluster_lock.go
  pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
  pkg/reconciler/cache/cachedresources/cachedresources_controller.go
  pkg/reconciler/cache/cachedresources/cachedresources_finalizer.go
  pkg/reconciler/cache/cachedresources/cachedresources_reconcile.go
  pkg/reconciler/dynamicrestmapper/dynamicrestmapper_test.go
  pkg/reconciler/tenancy/workspace/workspace_reconcile_phase.go
  pkg/server/apiextensions_test.go
  pkg/server/filters/impersonation.go
  pkg/server/filters/impersonation_test.go
  pkg/virtual/apiexport/authorizer/binding.go
  pkg/virtual/framework/rootapiserver/config.go
  sdk/apis/apis/group.go
  sdk/apis/core/v1alpha1/logicalcluster_types.go
  sdk/apis/roundtrip_test.go
  sdk/apis/tenancy/v1alpha1/types_workspacetype.go
  test/e2e/reconciler/workspacedeletion/controller_test.go
Labels: approved, lgtm, kind/cleanup, kind/api-change, size/L, dco-signoff: yes, release-note-none

#3461 bump logcheck to 0.9
  Makefile
Labels: approved, lgtm, kind/cleanup, size/XS, dco-signoff: yes, release-note-none

#3457 Improve linting config
  .golangci.yaml
  cmd/sharded-test-server/cache.go
  cmd/sharded-test-server/frontproxy.go
  cmd/sharded-test-server/main.go
  cmd/sharded-test-server/shard.go
  cmd/sharded-test-server/virtual.go
  cmd/test-server/main.go
  pkg/proxy/index/index_controller.go
  pkg/reconciler/apis/apibinding/apibinding_controller.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go
  pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go
  pkg/reconciler/apis/apiexport/apiexport_controller.go
  pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_controller.go
  pkg/reconciler/apis/apiexportendpointsliceurls/apiexportendpointsliceurls_controller.go
  pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
  pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller.go
  pkg/reconciler/apis/logicalclustercleanup/logicalclustercleanup_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
  pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_controller.go
  pkg/reconciler/cache/cachedresources/cachedresources_controller.go
  pkg/reconciler/cache/cachedresources/replication/replication_controller.go
  pkg/reconciler/cache/labelclusterrolebindings/labelclusterrolebinding_controller.go
  pkg/reconciler/cache/labelclusterroles/labelclusterrole_controller.go
  pkg/reconciler/cache/labellogicalcluster/labellogicalcluster_controller.go
  pkg/reconciler/cache/replication/replication_controller.go
  pkg/reconciler/core/logicalcluster/logicalcluster_controller.go
  pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
  pkg/reconciler/core/shard/shard_controller.go
  pkg/reconciler/dynamicrestmapper/dynamicrestmapper_controller.go
  pkg/reconciler/garbagecollector/garbagecollector_controller.go
  pkg/reconciler/kubequota/kubequota_controller.go
  pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
  pkg/reconciler/tenancy/defaultapibindinglifecycle/default_apibinding_lifecycle_controller.go
  pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
  pkg/reconciler/tenancy/logicalcluster/logicalcluster_controller.go
  pkg/reconciler/tenancy/workspace/workspace_controller.go
  pkg/reconciler/tenancy/workspacemounts/workspacemounts_controller.go
  pkg/reconciler/tenancy/workspacetype/workspacetype_controller.go
  pkg/reconciler/topology/partitionset/partitionset_controller.go
  pkg/server/filters/filters_test.go
  pkg/virtual/framework/forwardingregistry/store_test.go
  sdk/apis/apis/fuzzer/fuzzer.go
  sdk/apis/roundtrip_test.go
  sdk/cmd/help/doc.go
  sdk/testing/third_party/library-go/crypto/crypto.go
  test/e2e/apibinding/default_apibinding_test.go
  test/e2e/audit/audit_log_test.go
  test/e2e/conformance/cross_logical_cluster_list_test.go
  test/e2e/framework/kcp.go
  test/e2e/garbagecollector/garbagecollector_test.go
  test/e2e/quota/quota_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
  test/e2e/watchcache/watchcache_enabled_test.go
  test/integration/framework/goleak.go
Labels: approved, lgtm, kind/cleanup, size/L, dco-signoff: yes, release-note-none

#3460 update gotestsum to 1.12.3
  Makefile
Labels: approved, lgtm, kind/cleanup, size/XS, dco-signoff: yes, release-note-none

#3468 :bug: [release-0.27] Fix virutal workspace OpenAPI v3 endpoint panics
  pkg/virtual/framework/dynamic/apiserver/openapi.go
  test/e2e/virtual/apiexport/apiresourceschema_cowboys_versions.yaml
  test/e2e/virtual/apiexport/openapi_test.go
  test/e2e/virtual/apiexport/virtualworkspace_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note, dco-signoff: yes
